--修改日期：2012.12.21
--修改人：李程
--修改内容：德豪国际结算
--修改原因：新增字段，添加菜单
DECLARE
  VN_COUNT     NUMBER;
  VC_STR       VARCHAR2(1000);
BEGIN
  SELECT COUNT(*) 
    INTO VN_COUNT
    FROM USER_TAB_COLUMNS 
   WHERE TABLE_NAME = 'LC_ENROL' AND COLUMN_NAME = 'SECURITY_CURRENCY';
  IF VN_COUNT < 1 THEN
    VC_STR := 'ALTER TABLE  LC_ENROL ADD SECURITY_CURRENCY VARCHAR2(2)';
    EXECUTE IMMEDIATE VC_STR;
  END IF;
END;
/

DECLARE
  VN_COUNT     NUMBER;
  VC_STR       VARCHAR2(1000);
BEGIN
  SELECT COUNT(*) 
    INTO VN_COUNT
    FROM USER_TAB_COLUMNS 
   WHERE TABLE_NAME = 'LC_BILL_ARRIVAL' AND COLUMN_NAME = 'INV_NO';
  IF VN_COUNT < 1 THEN
    VC_STR := 'ALTER TABLE  LC_BILL_ARRIVAL ADD INV_NO VARCHAR2(50)';
    EXECUTE IMMEDIATE VC_STR;
  END IF;
END;
/

DECLARE
  VN_COUNT     NUMBER;
  VC_STR       VARCHAR2(1000);
BEGIN
  SELECT COUNT(*) 
    INTO VN_COUNT
    FROM USER_TAB_COLUMNS 
   WHERE TABLE_NAME = 'LC_BILL_ARRIVAL' AND COLUMN_NAME = 'AMOUNT_MONEY';
  IF VN_COUNT < 1 THEN
    VC_STR := 'ALTER TABLE  LC_BILL_ARRIVAL ADD AMOUNT_MONEY NUMBER';
    EXECUTE IMMEDIATE VC_STR;
  END IF;
END;
/

DECLARE
  VN_COUNT     NUMBER;
  VC_STR       VARCHAR2(1000);
BEGIN
  SELECT COUNT(*) 
    INTO VN_COUNT
    FROM USER_TAB_COLUMNS 
   WHERE TABLE_NAME = 'LC_BILL_ARRIVAL' AND COLUMN_NAME = 'PRESENTING_DATE';
  IF VN_COUNT < 1 THEN
    VC_STR := 'ALTER TABLE  LC_BILL_ARRIVAL ADD PRESENTING_DATE DATE';
    EXECUTE IMMEDIATE VC_STR;
  END IF;
END;
/

DECLARE
  VN_COUNT     NUMBER;
  VC_STR       VARCHAR2(1000);
BEGIN
  SELECT COUNT(*) 
    INTO VN_COUNT
    FROM USER_TAB_COLUMNS 
   WHERE TABLE_NAME = 'LC_BILL_ARRIVAL' AND COLUMN_NAME = 'SHIPNENT_DATE';
  IF VN_COUNT < 1 THEN
    VC_STR := 'ALTER TABLE  LC_BILL_ARRIVAL ADD SHIPNENT_DATE DATE';
    EXECUTE IMMEDIATE VC_STR;
  END IF;
END;
/

DECLARE
  VN_COUNT     NUMBER;
  VC_STR       VARCHAR2(1000);
BEGIN
  SELECT COUNT(*) 
    INTO VN_COUNT
    FROM USER_TAB_COLUMNS 
   WHERE TABLE_NAME = 'LC_BILL_ARRIVAL' AND COLUMN_NAME = 'RECEIVED_DATE';
  IF VN_COUNT < 1 THEN
    VC_STR := 'ALTER TABLE  LC_BILL_ARRIVAL ADD RECEIVED_DATE DATE';
    EXECUTE IMMEDIATE VC_STR;
  END IF;
END;
/

DECLARE
  VN_COUNT     NUMBER;
  VC_STR       VARCHAR2(1000);
BEGIN
  SELECT COUNT(*) 
    INTO VN_COUNT
    FROM USER_TAB_COLUMNS 
   WHERE TABLE_NAME = 'LC_BILL_ARRIVAL' AND COLUMN_NAME = 'PO';
  IF VN_COUNT < 1 THEN
    VC_STR := 'ALTER TABLE  LC_BILL_ARRIVAL ADD PO VARCHAR2(50)';
    EXECUTE IMMEDIATE VC_STR;
  END IF;
END;
/

DECLARE
  VN_COUNT     NUMBER;
  VC_STR       VARCHAR2(1000);
BEGIN
  SELECT COUNT(*) 
    INTO VN_COUNT
    FROM USER_TAB_COLUMNS 
   WHERE TABLE_NAME = 'LC_BILL_ARRIVAL' AND COLUMN_NAME = 'CUSTOMER';
  IF VN_COUNT < 1 THEN
    VC_STR := 'ALTER TABLE  LC_BILL_ARRIVAL ADD CUSTOMER VARCHAR2(50)';
    EXECUTE IMMEDIATE VC_STR;
  END IF;
END;
/

COMMENT ON COLUMN LC_ENROL.SECURITY_CURRENCY IS '保证金币别';
COMMENT ON COLUMN LC_BILL_ARRIVAL.INV_NO IS '商业发票号';
COMMENT ON COLUMN LC_BILL_ARRIVAL.AMOUNT_MONEY IS '发票金额';
COMMENT ON COLUMN LC_BILL_ARRIVAL.PRESENTING_DATE IS '交单日期';
COMMENT ON COLUMN LC_BILL_ARRIVAL.SHIPNENT_DATE IS '装运日期';
COMMENT ON COLUMN LC_BILL_ARRIVAL.RECEIVED_DATE IS '接收日期';
COMMENT ON COLUMN LC_BILL_ARRIVAL.PO IS '订单';
COMMENT ON COLUMN LC_BILL_ARRIVAL.CUSTOMER IS '客户';

DECLARE
  N_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO N_COUNT FROM BT_SYS_RES T WHERE T.SYS_CODE='LCS' AND T.RES_NAME='交单查询';
  IF N_COUNT < 1 THEN
  INSERT INTO BT_SYS_RES (RES_CODE,RES_NAME,SYS_CODE,FATHER_CODE,RES_URL,FUNC_FLAG,RES_TYPE,LINK_TARGET,STATUS,RES_ORDER,RMK,REVERSE1,REVERSE2,REVERSE3,REVERSE4,REVERSE5,REVERSE6,REVERSE7,REVERSE8,REVERSE9,REVERSE10,RES_LEVEL)
      SELECT (SELECT MAX(RES_CODE ) + 1 FROM BT_SYS_RES),'交单查询','LCS',RES_CODE,'/credit/allQueryPresenting.jsp','0','1','0','0',4,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,2
  FROM BT_SYS_RES
   WHERE RES_NAME = '查询'
   AND SYS_CODE='LCS';
    END IF;
END;
/

COMMIT;
