DECLARE
  @VN_COUNT    INT;
BEGIN
  SELECT @VN_COUNT = COUNT(*)
    FROM bt_sys_res t1, bt_sys_res t2 WHERE t1.sys_code='cms' AND t1.res_name='融资保证金计息' AND t1.father_code=t2.res_code AND t2.res_name='贷款管理';
  IF @VN_COUNT < 1 
  BEGIN
   INSERT INTO BT_SYS_RES (RES_CODE, RES_NAME, SYS_CODE, FATHER_CODE, RES_URL, FUNC_FLAG, RES_TYPE, LINK_TARGET, STATUS, RES_ORDER, RMK, REVERSE1, 
   REVERSE2, REVERSE3, REVERSE4, REVERSE5, REVERSE6, REVERSE7, REVERSE8, REVERSE9, REVERSE10, RES_LEVEL, RES_ROLE)
   SELECT (SELECT MAX(T1.RES_CODE) + 1 FROM BT_SYS_RES T1), '融资保证金计息', 'cms', RES_CODE, '/cms/outFinancInterestQueryLoad.jsp', '0', '1', '0', '0', 
   (SELECT MAX(T2.RES_ORDER)+1 FROM BT_SYS_RES T2 WHERE T2.FATHER_CODE = T3.RES_CODE AND T2.SYS_CODE = 'cms'), 
   NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, '' FROM BT_SYS_RES T3 WHERE T3.RES_NAME = '贷款管理' AND T3.SYS_CODE = 'cms';
  END;
END;
GO

CREATE TABLE OUTFINANC_INTEREST (
   INTERESTID VARCHAR(32) NOT NULL,   --计息id
   INTERESTCODE  VARCHAR(16),  --计息code
   CORP_ID VARCHAR(10),   --计息申请单位
   INTEREST_STARTDATE DATETIME,--计息开始时间
   INTEREST_ENDDATE DATETIME,  --计息截止时间
   INTERESTMONEY NUMERIC(15,2), --计息金额 
   TOUCHDATE DATETIME,  --制单时间
   APPROVES      VARCHAR(200), --操作人
   CONSTRAINT PK_OUTFINANCR_INTEREST PRIMARY KEY (INTERESTID)
);
GO