--修改人:陈春燕
--修改时间:2012-12-25
--修改内容: lc_enrol 表将reserve3 ，reserve2 更改为：数据来源（ORIGIN）和同步时间(SYNCHRONIZATION_TIME)

DECLARE
  VN_COUNT     NUMBER;
  VC_STR        VARCHAR2(1000);
BEGIN  
  SELECT COUNT(*) 
    INTO VN_COUNT
    FROM USER_TAB_COLUMNS 
   WHERE TABLE_NAME = 'LC_ENROL' AND COLUMN_NAME = 'ORIGIN'; 
  IF VN_COUNT < 1 THEN
    VC_STR := 'ALTER TABLE LC_ENROL  rename column reserve3 to ORIGIN';
    EXECUTE IMMEDIATE VC_STR;
  END IF;
END;
/


 ALTER TABLE lc_enrol  MODIFY origin VARCHAR2(20);

DECLARE
  VN_COUNT     NUMBER;
  VC_STR        VARCHAR2(1000);
BEGIN  
  SELECT COUNT(*) 
    INTO VN_COUNT
    FROM USER_TAB_COLUMNS 
   WHERE TABLE_NAME = 'LC_ENROL' AND COLUMN_NAME = 'SYNCHRONIZATION_TIME'; 
  IF VN_COUNT < 1 THEN
    VC_STR := 'ALTER TABLE LC_ENROL  rename column reserve2 to SYNCHRONIZATION_TIME';
    EXECUTE IMMEDIATE VC_STR;
  END IF;
END;
/


 ALTER TABLE lc_enrol  MODIFY SYNCHRONIZATION_TIME DATE;