--修改人:陈春燕
--修改时间:2012-12-25
--修改内容: lc_enrol 表将reserve3 ，reserve2 更改为：数据来源（ORIGIN）和同步时间(SYNCHRONIZATION_TIME)

IF NOT EXISTS(SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('LC_ENROL') AND NAME='ORIGIN')  
EXEC sp_rename 'lc_enrol.[reserve3]','origin','COLUMN' 
go
 
ALTER TABLE LC_ENROL ALTER COLUMN origin VARCHAR(20)
GO

IF NOT EXISTS(SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('LC_ENROL') AND NAME='SYNCHRONIZATION_TIME')  
EXEC sp_rename 'lc_enrol.[reserve2]','SYNCHRONIZATION_TIME','COLUMN' 
go

ALTER TABLE LC_ENROL ALTER COLUMN SYNCHRONIZATION_TIME DATETIME
go