--修改日期：20121009
--修改人：叶爱军
--需求编号：SX-AKS1-001 系统功能-授信品种类型维护
--修改内容：系统菜单 增加 授信品种类型维护
--参数设置：
INSERT INTO BT_SYS_RES (RES_CODE, RES_NAME, SYS_CODE, FATHER_CODE, RES_URL, FUNC_FLAG, RES_TYPE, LINK_TARGET, STATUS, RES_ORDER, RMK, REVERSE1, REVERSE2, REVERSE3, REVERSE4, REVERSE5, REVERSE6, REVERSE7, REVERSE8, REVERSE9, REVERSE10, RES_LEVEL, RES_ROLE)
SELECT (SELECT MAX(T1.RES_CODE) + 1 FROM BT_SYS_RES T1), '授信品种类型维护', 'rat', RES_CODE, '/rat/ratItemTypeAction.do?method=doQuery', '0', '0', '0', '0', (SELECT MAX(T2.RES_ORDER)+1 FROM BT_SYS_RES T2 WHERE T2.FATHER_CODE = T3.RES_CODE AND T2.SYS_CODE = 'rat'), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, '' FROM BT_SYS_RES T3 WHERE T3.RES_NAME = '授信维护' AND T3.SYS_CODE = 'rat';
GO

INSERT INTO RAT_SYS_ITEM (CODE, NAME, TYPE) SELECT (SELECT ISNULL(MAX(convert(int, CODE)), 0) + 1 FROM RAT_SYS_ITEM), '保兑仓', 0
GO;
INSERT INTO RAT_SYS_ITEM (CODE, NAME, TYPE) SELECT (SELECT ISNULL(MAX(convert(int, CODE)), 0) + 1 FROM RAT_SYS_ITEM), '票据贴现', 0
GO;
INSERT INTO RAT_SYS_ITEM (CODE, NAME, TYPE) SELECT (SELECT ISNULL(MAX(convert(int, CODE)), 0) + 1 FROM RAT_SYS_ITEM), '国内信用证', 0
GO;
INSERT INTO RAT_SYS_ITEM (CODE, NAME, TYPE) SELECT (SELECT ISNULL(MAX(convert(int, CODE)), 0) + 1 FROM RAT_SYS_ITEM), '贸易融资', 0
GO;
INSERT INTO RAT_SYS_ITEM (CODE, NAME, TYPE) SELECT (SELECT ISNULL(MAX(convert(int, CODE)), 0) + 1 FROM RAT_SYS_ITEM), '保函', 0
GO;
INSERT INTO RAT_SYS_ITEM (CODE, NAME, TYPE) SELECT (SELECT ISNULL(MAX(convert(int, CODE)), 0) + 1 FROM RAT_SYS_ITEM), '保理', 0
GO;

ALTER TABLE RAT_ITEM_CUSTOM ADD RIT_CODE VARCHAR(20);
GO

CREATE TABLE RAT_ITEM_TYPE (
   RIT_GUID             VARCHAR(40)          NOT NULL,
   OP_CODE              CHAR(40)             NULL,
   CREATET_TIME         DATETIME             NULL,
   CORP_CODE            CHAR(40)             NULL,
   STATUS               NUMERIC              NULL,
   UPDATE_TIME          DATETIME             NULL,
   UPDATER_CODE         CHAR(40)             NULL,
   APPROVES             CHAR(300)            NULL,
   NEXT_CHCKER          CHAR(40)             NULL,
   RIT_CODE             VARCHAR(10)          NULL,
   RIT_NAME             VARCHAR(255)         NULL,
   RIT_DESC             VARCHAR(255)         NULL,
   CONSTRAINT PK_RAT_ITEM_TYPE PRIMARY KEY NONCLUSTERED (RIT_GUID)
)
GO