--修改时间2012-11-08
--修改人 蔡瑾钊
--修改内容  CMS_PROVIDE_LOAN_INFO增加字段：中间业务费、使用人、信贷合同号、内部合同号、项目名称 

ALTER TABLE CMS_PROVIDE_LOAN_INFO ADD USERS VARCHAR(80)
GO

ALTER TABLE CMS_PROVIDE_LOAN_INFO ADD CREDIT_CONTRACT_NO VARCHAR(40)
GO

ALTER TABLE CMS_PROVIDE_LOAN_INFO ADD INSIDE_CONTRACT_NO VARCHAR(40)
GO

ALTER TABLE CMS_PROVIDE_LOAN_INFO ADD PROJECT_NAME VARCHAR(80)
GO

INSERT INTO CMS_LOAN_CLASS (CLC_ID, CLC_PARENT_ID, CLC_CODE, CLC_NAME, CLC_MEMO, CLC_ISVALID) select (SELECT ISNULL(MAX(CLC.CLC_ID), 0) + 1 FROM CMS_LOAN_CLASS CLC), (SELECT CLC.CLC_ID FROM CMS_LOAN_CLASS CLC WHERE CLC.CLC_CODE = '02'), '024', '流动资金贷款', '是为满足在生产经营过程中短期资金需求，保证生产经营活动正常进行而发放的贷款。', 1
GO

INSERT INTO CMS_LOAN_CLASS (CLC_ID, CLC_PARENT_ID, CLC_CODE, CLC_NAME, CLC_MEMO, CLC_ISVALID) select (SELECT ISNULL(MAX(CLC.CLC_ID), 0) + 1 FROM CMS_LOAN_CLASS CLC), (SELECT CLC.CLC_ID FROM CMS_LOAN_CLASS CLC WHERE CLC.CLC_CODE = '02'), '025', '项目贷款', '指为某一特定工程项目而融通资金的方法。', 1
GO

UPDATE CMS_PROVIDE_LOAN_INFO SET CLC_ID = (SELECT CLC.CLC_CODE FROM CMS_LOAN_CLASS CLC WHERE CLC.CLC_NAME = '流动资金贷款')
GO
