--修改日期：20121009
--修改人：叶爱军
--需求编号：SX-AKS1-001 系统功能-授信品种类型维护
--修改内容：系统菜单 增加 授信品种类型维护
--参数设置：
INSERT INTO BT_SYS_RES (RES_CODE, RES_NAME, SYS_CODE, FATHER_CODE, RES_URL, FUNC_FLAG, RES_TYPE, LINK_TARGET, STATUS, RES_ORDER, RMK, REVERSE1, REVERSE2, REVERSE3, REVERSE4, REVERSE5, REVERSE6, REVERSE7, REVERSE8, REVERSE9, REVERSE10, RES_LEVEL, RES_ROLE)
SELECT (SELECT MAX(T1.RES_CODE) + 1 FROM BT_SYS_RES T1), '授信品种类型维护', 'rat', RES_CODE, '/rat/ratItemTypeAction.do?method=doQuery', '0', '0', '0', '0', (SELECT MAX(T2.RES_ORDER)+1 FROM BT_SYS_RES T2 WHERE T2.FATHER_CODE = T3.RES_CODE AND T2.SYS_CODE = 'rat'), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, '' FROM BT_SYS_RES T3 WHERE T3.RES_NAME = '授信维护' AND T3.SYS_CODE = 'rat';
COMMIT;

INSERT INTO RAT_SYS_ITEM (CODE, NAME, TYPE) VALUES ((SELECT NVL(MAX(TO_NUMBER(CODE)), 0) + 1 FROM RAT_SYS_ITEM), '保兑仓', 0);
INSERT INTO RAT_SYS_ITEM (CODE, NAME, TYPE) VALUES ((SELECT NVL(MAX(TO_NUMBER(CODE)), 0) + 1 FROM RAT_SYS_ITEM), '票据贴现', 0);
INSERT INTO RAT_SYS_ITEM (CODE, NAME, TYPE) VALUES ((SELECT NVL(MAX(TO_NUMBER(CODE)), 0) + 1 FROM RAT_SYS_ITEM), '国内信用证', 0);
INSERT INTO RAT_SYS_ITEM (CODE, NAME, TYPE) VALUES ((SELECT NVL(MAX(TO_NUMBER(CODE)), 0) + 1 FROM RAT_SYS_ITEM), '贸易融资', 0);
INSERT INTO RAT_SYS_ITEM (CODE, NAME, TYPE) VALUES ((SELECT NVL(MAX(TO_NUMBER(CODE)), 0) + 1 FROM RAT_SYS_ITEM), '保函', 0);
INSERT INTO RAT_SYS_ITEM (CODE, NAME, TYPE) VALUES ((SELECT NVL(MAX(TO_NUMBER(CODE)), 0) + 1 FROM RAT_SYS_ITEM), '保理', 0);
COMMIT;

ALTER TABLE RAT_ITEM_CUSTOM ADD RIT_CODE VARCHAR2(20);
COMMIT;

CREATE TABLE RAT_ITEM_TYPE  (
   RIT_GUID             VARCHAR2(40)                    NOT NULL,
   OP_CODE              CHAR(40),
   CREATET_TIME         DATE,
   CORP_CODE            CHAR(40),
   STATUS               NUMBER,
   UPDATE_TIME          DATE,
   UPDATER_CODE         CHAR(40),
   APPROVES             CHAR(300),
   NEXT_CHCKER          CHAR(40),
   RIT_CODE             VARCHAR2(10),
   RIT_NAME             VARCHAR2(255),
   RIT_DESC             VARCHAR2(255),
   CONSTRAINT PK_RAT_ITEM_TYPE PRIMARY KEY (RIT_GUID)
);