--修改日期：20121016
--修改人：叶爱军
--修改内容：SX-AKS1-005 系统功能-借款申请界面
--修改内容：CMS_PROVIDE_LOAN_INFO 增加字段 付息方式
--参数设置：
ALTER TABLE CMS_PROVIDE_LOAN_INFO ADD CPL_INTEREST_PAYMENT VARCHAR(3);
GO

UPDATE CMS_PROVIDE_LOAN_INFO SET CPL_INTEREST_PAYMENT = '001';
GO