--修改日期：20120907
--修改人：叶爱军[BUG]
--修改内容：XD-JD03-015 系统功能-借款申请界面
--修改内容：历史数据将借款类别字段自动赋值"022-经营贷款"
--参数设置：
UPDATE CMS_PROVIDE_LOAN_INFO SET CLC_ID = (SELECT CLC.CLC_ID FROM CMS_LOAN_CLASS CLC WHERE CLC.CLC_NAME = '经营贷款');
GO

ALTER VIEW V_CMS_LOAN_BILL AS
SELECT CLI.CORP_ID AS CORP_ID, BC.CORP_CODE, BC.CORP_NAME, CLI.CLC_ID, CONVERT(CHAR(10), CLI.LOAN_DATE, 120) AS LOAN_DATE, CLI.STATUS AS LOAN_STATE,
       SUM(CASE WHEN CLI.CONTRACT_CODE IS NULL THEN 0 ELSE CLI.LOAN_MONEY END) AS CONTRACT_SUM,
       SUM(CASE WHEN CONVERT(CHAR(4), CLI.LOAN_DATE, 120) = CONVERT(CHAR(4), GETDATE(), 120) THEN CLI.LOAN_MONEY ELSE 0 END) AS LOAN_SUM,
       SUM(ISNULL(CLI.LOAN_MONEY, 0)) AS LOAN_SUM_ALL,
       SUM(CASE WHEN CONVERT(CHAR(4), CLR.REPAY_DATE, 120) = CONVERT(CHAR(4), GETDATE(), 120) THEN CLR.REPAY_MONEY ELSE 0 END) AS REPAY_SUM,
       SUM(ISNULL(CLR.REPAY_MONEY, 0)) AS REPAY_SUM_ALL,
       SUM(ISNULL(CLI.LOAN_MONEY, 0)) AS LOAN_MONEY,
       (SUM(ISNULL(CLI.LOAN_MONEY, 0)) - SUM(ISNULL(CLR.REPAY_MONEY, 0))) AS LOAN_MONEY_LAST
  FROM CMS_LOAN_INFO CLI
  LEFT JOIN CMS_LOAN_REPAY CLR ON CLI.BILL_CODE = CLR.LI_CODE
  JOIN BT_CORP BC ON CLI.CORP_ID = BC.ID
 GROUP BY CLI.CORP_ID, BC.CORP_CODE, BC.CORP_NAME, CLI.CLC_ID, CLI.LOAN_DATE, CLI.STATUS;
GO
ALTER VIEW V_CMS_LOAN_BILL_DEATIL AS
SELECT CLI.BILL_CODE, CLI.CORP_ID, CLI.CLC_ID, CONVERT(CHAR(10), CLI.LOAN_DATE, 120) AS LOAN_DATE, CLI.CONTRACT_CODE, CLI.LOAN_ACC AS BANK_ACC, CLI.LOAN_ACC,
       ISNULL(RCD.MONEY, 0) AS MONEY, (CONVERT(CHAR(10), RCP.BEGINDATE, 120) + '至' + CONVERT(CHAR(10), RCP.ENTERDATE, 120)) AS RCP_DATE,
       SUM(CASE WHEN CLI.CONTRACT_CODE IS NULL THEN 0 ELSE CLI.LOAN_MONEY END) AS CONTRACT_SUM,
       SUM(CASE WHEN CONVERT(CHAR(4), CLI.LOAN_DATE, 120) = CONVERT(CHAR(4), GETDATE(), 120) THEN CLI.LOAN_MONEY ELSE 0 END) AS LOAN_SUM,
       SUM(ISNULL(CLI.LOAN_MONEY, 0)) AS LOAN_SUM_ALL,
       SUM(CASE WHEN CONVERT(CHAR(4), CLR.REPAY_DATE, 120) = CONVERT(CHAR(4), GETDATE(), 120) THEN CLR.REPAY_MONEY ELSE 0 END) AS REPAY_SUM,
       SUM(ISNULL(CLR.REPAY_MONEY, 0)) AS REPAY_SUM_ALL,
       SUM(ISNULL(CLI.LOAN_MONEY, 0)) AS LOAN_MONEY,
       CLI.LOAN_RATE, CLI.OVERDUE_RATE, CPLT.TYPE_NAME, CLI.SURETY_EXPLAIN,
       (CONVERT(CHAR(10), CLI.LOAN_DATE, 120) + '至' + CONVERT(CHAR(10), CLI.REPAY_DATE, 120)) AS LOAN_S_E_DATE,
       CLI.STATUS,
       (SUM(ISNULL(CLI.LOAN_MONEY, 0)) - SUM(ISNULL(CLR.REPAY_MONEY, 0))) AS LOAN_MONEY_LAST,
       CLI.RMK
 FROM CMS_LOAN_INFO CLI
 JOIN CMS_PROVIDE_LOAN_TYPE CPLT ON CLI.LOAN_TYPE = CPLT.TYPE_CODE
 JOIN BT_CORP BC ON CLI.CORP_ID = BC.ID
 LEFT JOIN CMS_LOAN_REPAY CLR ON CLI.BILL_CODE = CLR.LI_CODE
 LEFT JOIN RAT_CPRATION RCP ON RCP.COMPCODE = BC.CORP_CODE
 LEFT JOIN RAT_CPRATION_DETAIL RCD ON RCP.CODE = RCD.DISTRIBUTE_CODE AND RCD.ITEM_CODE = CLI.ITEM_CODE
 WHERE CLI.STATUS >= 95 AND CPLT.OPERATION_TYPE = 'A'
 GROUP BY CLI.BILL_CODE, CLI.CORP_ID, CLI.CLC_ID, RCD.ITEM_CODE, CLI.LOAN_DATE, CLI.REPAY_DATE, CLI.CONTRACT_CODE, CLI.LOAN_ACC, RCD.MONEY, RCP.BEGINDATE, RCP.ENTERDATE, CLI.LOAN_RATE, CLI.OVERDUE_RATE, CPLT.TYPE_NAME, CLI.SURETY_EXPLAIN, CLI.STATUS, CLI.RMK;