--修改日期：2012.12.15
--修改人：刘之三
--修改内容：自动扫描预警
--修改原因：自动扫描预警

--净流入透支
--余额连续下降

DECLARE
  VN_COUNT     NUMBER;
  VC_STR       VARCHAR2(1000);
BEGIN
  --查看该表中该字段是否存在
  SELECT COUNT(*) 
    INTO VN_COUNT 
    FROM USER_TAB_COLUMNS 
   WHERE TABLE_NAME = 'BT_WARNING_OVERFLOW' AND COLUMN_NAME = 'STRATEGY_DETAIL_STR';
  --如果小于1则说明不存在，则新增此字段
  IF VN_COUNT < 1 THEN
    VC_STR := ' ALTER TABLE BT_WARNING_OVERFLOW ADD STRATEGY_DETAIL_STR VARCHAR2(40)';
    EXECUTE IMMEDIATE VC_STR;
  END IF;
END;
/


DECLARE
  VN_COUNT     NUMBER;
  VC_STR       VARCHAR2(1000);
BEGIN
  --查看该表中该字段是否存在
  SELECT COUNT(*) 
    INTO VN_COUNT 
    FROM USER_TAB_COLUMNS 
   WHERE TABLE_NAME = 'BT_WARNING_OVERFLOW' AND COLUMN_NAME = 'BUSINESS_DATE';
  --如果小于1则说明不存在，则新增此字段
  IF VN_COUNT < 1 THEN
    VC_STR := ' ALTER TABLE BT_WARNING_OVERFLOW ADD BUSINESS_DATE DATE';
    EXECUTE IMMEDIATE VC_STR;
  END IF;
END;
/



DECLARE
  VN_COUNT     NUMBER;
  VC_STR       VARCHAR2(1000);
BEGIN
  --查看该表中该字段是否存在
  SELECT COUNT(*) 
    INTO VN_COUNT 
    FROM USER_TAB_COLUMNS 
   WHERE TABLE_NAME = 'BT_WARNING_OVERFLOW' AND COLUMN_NAME = 'WARNING_REASON';
  --如果小于1则说明不存在，则新增此字段
  IF VN_COUNT < 1 THEN
    VC_STR := ' ALTER TABLE BT_WARNING_OVERFLOW ADD WARNING_REASON VARCHAR2(400)';
    EXECUTE IMMEDIATE VC_STR;
  END IF;
END;
/


DECLARE
  VN_COUNT     NUMBER;
  VC_STR       VARCHAR2(1000);
BEGIN
  --查看该表中该字段是否存在
  SELECT COUNT(*) 
    INTO VN_COUNT 
    FROM USER_TAB_COLUMNS 
   WHERE TABLE_NAME = 'BT_WARNING_OVERFLOW' AND COLUMN_NAME = 'BANK_ACC';
  --如果小于1则说明不存在，则新增此字段
  IF VN_COUNT < 1 THEN
    VC_STR := ' ALTER TABLE BT_WARNING_OVERFLOW ADD BANK_ACC VARCHAR2(50)';
    EXECUTE IMMEDIATE VC_STR;
  END IF;
END;
/


DECLARE
  VN_COUNT     NUMBER;
  VC_STR       VARCHAR2(1000);
BEGIN
  --查看该表中该字段是否存在
  SELECT COUNT(*) 
    INTO VN_COUNT 
    FROM USER_TAB_COLUMNS 
   WHERE TABLE_NAME = 'BT_WARNING_OVERFLOW' AND COLUMN_NAME = 'STRAGE_DETAIL_ID';
  --如果小于1则说明不存在，则新增此字段
  IF VN_COUNT < 1 THEN
    VC_STR := ' ALTER TABLE BT_WARNING_OVERFLOW ADD STRAGE_DETAIL_ID NUMBER(10)';
    EXECUTE IMMEDIATE VC_STR;
  END IF;
END;
/


DECLARE
  VN_COUNT     NUMBER;
  VC_STR       VARCHAR2(1000);
BEGIN
  --查看该表中该字段是否存在
  SELECT COUNT(*) 
    INTO VN_COUNT 
    FROM USER_TAB_COLUMNS 
   WHERE TABLE_NAME = 'BT_WARNING_OVERFLOW' AND COLUMN_NAME = 'SCAN_DATE_START';
  --如果小于1则说明不存在，则新增此字段
  IF VN_COUNT < 1 THEN
    VC_STR := ' ALTER TABLE BT_WARNING_OVERFLOW ADD SCAN_DATE_START DATE';
    EXECUTE IMMEDIATE VC_STR;
  END IF;
END;
/


DECLARE
  VN_COUNT     NUMBER;
  VC_STR       VARCHAR2(1000);
BEGIN
  --查看该表中该字段是否存在
  SELECT COUNT(*) 
    INTO VN_COUNT 
    FROM USER_TAB_COLUMNS 
   WHERE TABLE_NAME = 'BT_WARNING_OVERFLOW' AND COLUMN_NAME = 'BANK_TYPE';
  --如果小于1则说明不存在，则新增此字段
  IF VN_COUNT < 1 THEN
    VC_STR := ' ALTER TABLE BT_WARNING_OVERFLOW ADD BANK_TYPE VARCHAR2(10)';
    EXECUTE IMMEDIATE VC_STR;
  END IF;
END;
/