--修改时间2012-12-25
--修改人 曾炼平
--修改内容 增加 保证金比率字段

IF NOT EXISTS(SELECT * 
FROM SYSCOLUMNS 
WHERE ID=OBJECT_ID('LC_ENROL') AND NAME='DEPOSIT_RATIO')  
ALTER TABLE LC_ENROL ADD DEPOSIT_RATIO NUMERIC(10, 2)
GO
