--日期：2012-08-28
--修改人：张培
--修改内容：新增脚本证券账户表、证券账户关系维护表主键生成方式由原来Sequence为Table
INSERT INTO TB_GENERATOR (GEN_NAME, GEN_VALUE)
SELECT 'NIS_SEC_SECURITIES_ID', 1
GO  
INSERT INTO TB_GENERATOR (GEN_NAME, GEN_VALUE)
SELECT 'NIS_SEC_RELATION_ID', 1
GO  
