--修改日期：20121031
--修改人：叶爱军
--需求编号：SX-AKS1-002
--修改内容：币别汇率
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE  name = 'V_FC_EXCRATE_ADJUST ')  
DROP VIEW V_FC_EXCRATE_ADJUST  
GO 
CREATE VIEW V_FC_EXCRATE_ADJUST AS
SELECT BC.CUR_CODE,
       BC.CUR_NAME,
       (CASE WHEN FEA.NEW_EXCHANGE_RATE IS NULL THEN BC.CUR_EXRATE ELSE FEA.NEW_EXCHANGE_RATE END) AS NEW_EXCHANGE_RATE,
       (CASE WHEN FEA.ADJUST_TIME IS NULL THEN '1900-01-01' ELSE CONVERT(CHAR(20), FEA.ADJUST_TIME, 120) END) AS ADJUST_TIME
  FROM BT_CURRENCY BC
  LEFT JOIN FC_EXCRATE_ADJUST FEA ON BC.CUR_CODE = FEA.CUR_CODE AND FEA.STATUS = '95';
GO

--修改日期：20130109
--修改人：张培
--Bug编号：user00035383
--修改内容：添加综合品种选择单项及组合项编码字段
--授信占用
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'COMP_ITEM_CODE' AND LTRIM(B.NAME) = 'RAT_URATION')
	ALTER TABLE RAT_URATION ADD COMP_ITEM_CODE VARCHAR(500)
GO
--承兑自开  
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'COMP_ITEM_CODE' AND LTRIM(B.NAME) = 'AB_EMIT')
	ALTER TABLE AB_EMIT ADD COMP_ITEM_CODE VARCHAR(500)
GO
--信用证  
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'COMP_ITEM_CODE' AND LTRIM(B.NAME) = 'LC_ENROL')
	ALTER TABLE LC_ENROL ADD COMP_ITEM_CODE VARCHAR(500)
GO
--信贷借款
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'COMP_ITEM_CODE' AND LTRIM(B.NAME) = 'CMS_PROVIDE_LOAN_INFO')
	ALTER TABLE CMS_PROVIDE_LOAN_INFO ADD COMP_ITEM_CODE VARCHAR(500)
GO
--授信申请
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'COMP_ITEM_CODE' AND LTRIM(B.NAME) = 'RAT_URATION_APPLY')
	ALTER TABLE RAT_URATION_APPLY ADD COMP_ITEM_CODE VARCHAR(500)
GO

ALTER TABLE RAT_BKRATION_DETAIL ALTER COLUMN INTERESTRATE NUMERIC(15,6);
GO

--修改日期：20121031
--修改人：叶爱军
--需求编号：SX-AKS1-002
--修改内容：综合单项的共享额度
IF EXISTS(SELECT 1  FROM SYSOBJECTS WHERE XTYPE = 'FN' AND NAME='FUN_GET_PROCESS_MONEY_SIN')
DROP FUNCTION FUN_GET_PROCESS_MONEY_SIN
GO
CREATE FUNCTION FUN_GET_PROCESS_MONEY_SIN(@V_RATION_CODE VARCHAR, @V_ITEM_CODE VARCHAR, @V_COMPCODE VARCHAR)
  RETURNS NUMERIC AS
BEGIN
  DECLARE @V_PROCESS_MONEY NUMERIC(15, 2)
  SELECT @V_PROCESS_MONEY = ISNULL(SUM(T.V_PROCESS_MONEY), 0)
  FROM (SELECT (CASE WHEN LEN(RC.ITEM_CODE) = 9 THEN RC.MONEY ELSE 0 END) AS V_PROCESS_MONEY
  FROM RAT_COMPOSITIVE_DETAIL RC JOIN RAT_URATION RU ON RC.RAT_CODE = RU.RATION_CODE AND RC.REF_CODE = RU.BILLNO
  AND PATINDEX(RU.COMP_ITEM_CODE, RC.ITEM_CODE) >= 1 WHERE RC.REF_TYPE = '6' AND RC.RAT_CODE = @V_RATION_CODE AND RU.RATION_CODE = @V_RATION_CODE
  AND PATINDEX(RC.ITEM_CODE, @V_ITEM_CODE) >= 1 AND RU.STATUS IN ('1', '2')
  AND RC.COMP_CODE IN (SELECT RBD.COMPCODE FROM RAT_BKRATION_DIS RBD WHERE RBD.RAT_CODE = @V_RATION_CODE AND RBD.DISTRIBUTE_WAY = '2') GROUP BY RC.ITEM_CODE, RC.REF_CODE, RC.MONEY) T
  RETURN @V_PROCESS_MONEY
END
GO

--修改日期：20121031
--修改人：叶爱军
--需求编号：SX-AKS1-002
--修改内容：综合组合项的共享额度
IF EXISTS(SELECT 1  FROM SYSOBJECTS WHERE XTYPE = 'FN' AND NAME='FUN_GET_PROCESS_MONEY_COM')
DROP FUNCTION FUN_GET_PROCESS_MONEY_COM
GO
CREATE FUNCTION FUN_GET_PROCESS_MONEY_COM(@V_RATION_CODE VARCHAR, @V_ITEM_CODE VARCHAR, @V_COMPCODE VARCHAR)
  RETURNS NUMERIC AS
BEGIN
  DECLARE @V_PROCESS_MONEY NUMERIC(15, 2)
  SELECT @V_PROCESS_MONEY = ISNULL(SUM(T.V_PROCESS_MONEY), 0)
  FROM (SELECT DISTINCT RC.REF_CODE, RC.MONEY AS V_PROCESS_MONEY
  FROM RAT_COMPOSITIVE_DETAIL RC JOIN RAT_URATION RU ON RC.RAT_CODE = RU.RATION_CODE AND RC.REF_CODE = RU.BILLNO
  AND PATINDEX(RU.COMP_ITEM_CODE, RC.ITEM_CODE) >= 1 WHERE RC.REF_TYPE = '6' AND RC.RAT_CODE = @V_RATION_CODE AND RU.RATION_CODE = @V_RATION_CODE
  AND PATINDEX(RC.ITEM_CODE, @V_ITEM_CODE) >= 1 AND RU.STATUS IN ('1', '2')
  AND RC.COMP_CODE IN (SELECT RBD.COMPCODE FROM RAT_BKRATION_DIS RBD WHERE RBD.RAT_CODE = @V_RATION_CODE AND RBD.DISTRIBUTE_WAY = '2') GROUP BY RC.ITEM_CODE, RC.REF_CODE, RC.MONEY) T
  RETURN @V_PROCESS_MONEY
END
GO