--修改时间：2012-12-03
--修改内容：数据补录定义表,增加客户编号参数控制
DECLARE
  @VN_COUNT int;
BEGIN
  SELECT @VN_COUNT = COUNT(*)
    FROM ERP_ADDITIONAL_DEFINE
   WHERE FIELD_CODE='VENDOR_NUM';
  IF @VN_COUNT < 1
    BEGIN
	--初始化数据
	insert into ERP_ADDITIONAL_DEFINE(ID,FIELD_CODE,FIELD_NAME,IS_ADDITIONAL,IS_NOT_NULL)values(2,'VENDOR_NUM','客户编号','1','0');
  END;
END;
GO
