--修改人：安志明
--修改时间：2012-11-9
--描述：创建会计科目凭证中间表
create table ERP_K3_ACCOUNT
(
  FACCOUNTID     NUMBER(10) not null,
  FNUMBER        VARCHAR2(40) not null,
  FNAME          VARCHAR2(80) not null,
  FLEVEL         NUMBER(5) not null,
  FDETAIL        NUMBER(1) not null,
  FPARENTID      NUMBER(10) not null,
  FROOTID        NUMBER(10) not null,
  FGROUPID       NUMBER(10) not null,
  FDC            NUMBER(10) not null,
  FHELPERCODE    VARCHAR2(40),
  FCURRENCYID    NUMBER(10) not null,
  FADJUSTRATE    NUMBER(1) not null,
  FEARNACCOUNTID NUMBER(10),
  FQUANTITIES    NUMBER(1) not null,
  FUNITGROUPID   NUMBER(10) not null,
  FMEASUREUNITID NUMBER(10) not null,
  FISCASH        NUMBER(1) not null,
  FISBANK        NUMBER(1) not null,
  FJOURNAL       NUMBER(1) not null,
  FCONTACT       NUMBER(1) not null,
  FISCASHFLOW    NUMBER(1) not null,
  FDETAILID      NUMBER(10) not null,
  FACNT          NUMBER(1) not null,
  FLOAN          NUMBER(1) not null,
  FDPST          NUMBER(1) not null,
  FSTATEDDPST    NUMBER(1) not null,
  FINTEREST      NUMBER(1) not null,
  FISACNT        NUMBER(1) not null,
  FISBUDGET      NUMBER(1) not null,
  FACNTID        NUMBER(10) not null,
  FBRNO          VARCHAR2(10) not null,
  FACCTINT       NUMBER(1) not null,
  FINTRATE       NUMBER(5,3) not null,
  FLASTINTDATE   DATE,
  FACNTTYPE      NUMBER(10) not null,
  FTRADENUM      VARCHAR2(40),
  FCONTROL       NUMBER(10) not null,
  FVIEWMSG       NUMBER(1) not null,
  FMESSAGE       VARCHAR2(100),
  FDELETE        NUMBER(5) not null,
  FISBUSI        NUMBER(10) not null,
  FFULLNAME      VARCHAR2(250),
  FMODIFYTIME    VARCHAR2(36) not null,
  FSYSTEMTYPE    NUMBER(10) not null,
  FCONTROLSYSTEM NUMBER(5) not null,
  UUID           VARCHAR2(36) not null,
  FCFITEMID      NUMBER(10),
  FSUBCFITEMID   NUMBER(10),
  FCORPCODE      VARCHAR2(8)
);
go

