--修改日期：20121207
--修改人：叶爱军
--修改内容：RAT_URATION_APPLY修改INTEREST_RATE的类型NUMBER(6, 4)改为NUMBER(8, 6)
--参数设置：
ALTER TABLE RAT_URATION_APPLY MODIFY INTEREST_RATE NUMBER(8, 6);
COMMIT;

--修改时间2012-11-17
--修改人 李鹏飞
--修改内容  RAT_BKRATION_DIS和RAT_BKRATION_DIS_DETAIL添加字段 
DECLARE
  V_CNT_0 INTEGER;
  V_CNT_1 INTEGER;
  V_CNT_2 INTEGER;
  V_CNT_3 INTEGER;
  V_CNT_4 INTEGER;
  V_CNT_5 INTEGER;
  V_CNT_6 INTEGER;
BEGIN
  --RAT_URATION添加OPEN_MONEY字段 叶爱军
  SELECT COUNT(1) INTO V_CNT_0 FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'RAT_URATION' AND COLUMN_NAME = 'OPEN_MONEY';
  --分配方式 李鹏飞
  SELECT COUNT(1) INTO V_CNT_1 FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'RAT_BKRATION_DIS' AND COLUMN_NAME = 'DISTRIBUTE_WAY';
  --一批单位或网点中是否已经有记录审批通过了 李鹏飞
  SELECT COUNT(1) INTO V_CNT_2 FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'RAT_BKRATION_DIS' AND COLUMN_NAME = 'ISPASSED';
  --保存一批分配的单位或网点编号 李鹏飞
  SELECT COUNT(1) INTO V_CNT_3 FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'RAT_BKRATION_DIS' AND COLUMN_NAME = 'ALL_COMP_CODES';
  --全额共享时，保存本身不占用的金额 李鹏飞
  SELECT COUNT(1) INTO V_CNT_4 FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'RAT_BKRATION_DIS_DETAIL' AND COLUMN_NAME = 'VIRTUAL_URATION';
  --虚拟调剂金额 李鹏飞
  SELECT COUNT(1) INTO V_CNT_5 FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'RAT_BKRATION_DIS_DETAIL' AND COLUMN_NAME = 'VIRTUAL_RELIEF_MONEY';
  --银行授信额度综合品种单项及组合项 张培
  SELECT COUNT(1) INTO V_CNT_6 FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'RAT_COMPOSITIVE_DETAIL';
  
  --RAT_URATION添加OPEN_MONEY字段
  IF V_CNT_0 = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RAT_URATION ADD OPEN_MONEY NUMBER(18, 2)';
  END IF;
  --分配方式
  IF V_CNT_1 = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RAT_BKRATION_DIS ADD DISTRIBUTE_WAY VARCHAR2(10)';
  END IF;
  --一批单位或网点中是否已经有记录审批通过了
  IF V_CNT_2 = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RAT_BKRATION_DIS ADD ISPASSED VARCHAR2(10)';
  END IF;
  --保存一批分配的单位或网点编号
  IF V_CNT_3 = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RAT_BKRATION_DIS ADD ALL_COMP_CODES VARCHAR2(500)';
  END IF;
  --全额共享时，保存本身不占用的金额
  IF V_CNT_4 = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RAT_BKRATION_DIS_DETAIL ADD VIRTUAL_URATION NUMBER(15,2) DEFAULT 0';
  END IF;
  --虚拟调剂金额
  IF V_CNT_5 = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RAT_BKRATION_DIS_DETAIL ADD VIRTUAL_RELIEF_MONEY NUMBER(15,2) DEFAULT 0';
  END IF;
  IF V_CNT_6 = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE RAT_COMPOSITIVE_DETAIL (
						CODE VARCHAR2(20) NOT NULL,
						REF_CODE VARCHAR2(20),
						ITEM_CODE VARCHAR2(500),
						MONEY NUMBER(18,2),
						FLAG CHAR(1),
						REF_TYPE CHAR(1),
						PROCESS_MONEY NUMBER(18,2),
						RELIEF_MONEY NUMBER(18,2),
						BY_RELIEF_MONEY NUMBER(18,2),
						FREEZE_MONEY NUMBER(18,2),
						RAT_CODE VARCHAR2(20),
						COMP_CODE VARCHAR2(20)
					  )';
	EXECUTE IMMEDIATE 'ALTER TABLE RAT_COMPOSITIVE_DETAIL ADD CONSTRAINT COMPOSITIVE_DETAIL_PK PRIMARY KEY (CODE)';
  END IF;
  COMMIT;
END;
/