--修改人：胡双
--修改日期：2012-12-26
--修改内容：修改RETURN_MSG列的长度

ALTER TABLE BIS_ACC_HIS_DTL ALTER COLUMN RETURN_MSG VARCHAR(500);
ALTER TABLE BIS_ACC_HIS_DTL_MERGEN ALTER COLUMN RETURN_MSG VARCHAR(500);
ALTER TABLE BIS_ACC_HIS_DTL_SPLIT ALTER COLUMN RETURN_MSG VARCHAR(500);
ALTER TABLE AB_OPERATION ALTER COLUMN RETURN_MSG VARCHAR(500);
