--修改时间2012-12-21
--修改人 周兵
--修改内容  预警扫描，加主键

ALTER TABLE BT_WARNING_RESULT_DETAIL ADD CONSTRAINT PK_BT_WARNING_RESULT_DETAIL PRIMARY KEY(ID);

ALTER TABLE BT_WARNING_RESULT_BAL ADD CONSTRAINT PK_BT_WARNING_RESULT_BAL PRIMARY KEY(ID);

ALTER TABLE BT_WARNING_RESULT_OVERFLOW ADD CONSTRAINT PK_BT_WARNING_RESULT_OVERFLOW PRIMARY KEY(ID);

ALTER TABLE BT_WARNING_RESULT_BAL_DOWN ADD CONSTRAINT PK_BT_WARNING_RESULT_BAL_DOWN PRIMARY KEY(ID);

ALTER TABLE BT_WARNING_RESULT_DOWN_DETAIL ADD CONSTRAINT PK_BT_WARNING_RESULT_DOWN_DETAIL PRIMARY KEY(ID);

ALTER TABLE BT_WARNING_DETAIL ADD CONSTRAINT PK_BT_WARNING_DETAIL PRIMARY KEY(ID);

ALTER TABLE BT_WARNING_BALANCEDOWN_DTL ADD CONSTRAINT PK_BT_WARNING_BALANCEDOWN_DTL PRIMARY KEY(ID);

commit;