--修改日期：20120918
--修改人：余川锋
--需求编号：XD-JD03-029 系统功能-增加贷款本金
--参数设置：
CREATE OR REPLACE VIEW V_CMS_BILLING AS
SELECT CLB.CLB_ID,
       CLB.CLB_NO,
       CLB.CLB_LOAN_CORP_ID AS BL_CORP_ID,
       BL.CORP_CODE AS BL_CORP_CODE,
       BL.CORP_NAME AS BL_CORP_NAME,
       CLB.CLB_BORROW_CORP_ID AS BB_CORP_ID,
       BB.CORP_CODE AS BB_CORP_CODE,
       BB.CORP_NAME AS BB_CORP_NAME,
       ROUND(CLB.CLB_LOAN_MONEY, 2) AS CLB_LOAN_MONEY,
       ROUND(NVL(SUM(CLA.CLA_MONEY), 0), 2) AS CLA_MONEY,
       ROUND(CLB.CLB_BALANCE, 2) AS CLB_BALANCE,
       ROUND(CLB.CLB_FIXED_RATE, 6) AS CLB_FIXED_RATE,
       ROUND(CLB.CLB_AGREEMENT_RATE, 6) AS CLB_AGREEMENT_RATE,
       CLB.CLB_START_DATE,
       CLB.CLB_END_DATE,
       CLB.CLB_LAST_BILLING_DATE
FROM CMS_LOAN_BILL CLB
LEFT JOIN CMS_LOAN_ABATE CLA ON CLB.CLB_ID = CLA.CLB_ID
INNER JOIN BT_CORP BL ON CLB.CLB_LOAN_CORP_ID = BL.ID
INNER JOIN BT_CORP BB ON CLB.CLB_BORROW_CORP_ID = BB.ID
WHERE CLB.CLB_STATUS=95
GROUP BY CLB.CLB_NO,CLB.CLB_LOAN_CORP_ID,BL.CORP_CODE,
        BL.CORP_NAME,CLB.CLB_BORROW_CORP_ID,BB.CORP_CODE,BB.CORP_NAME,
        CLB.CLB_LOAN_MONEY,CLB.CLB_BALANCE,CLB.CLB_FIXED_RATE,CLB.CLB_LAST_BILLING_DATE,
        CLB.CLB_AGREEMENT_RATE,CLB.CLB_START_DATE,CLB.CLB_END_DATE,CLB.CLB_ID;
CREATE OR REPLACE VIEW V_CMS_ACCOUNTINGFEE AS
SELECT CLB.CLB_ID,
       CLB.CLB_NO,
       CLB.CLB_LOAN_CORP_ID AS BL_CORP_ID,
       BL.CORP_CODE AS BL_CORP_CODE,
       BL.CORP_NAME AS BL_CORP_NAME,
       CLB.CLB_BORROW_CORP_ID AS BB_CORP_ID,
       BB.CORP_CODE AS BB_CORP_CODE,
       BB.CORP_NAME AS BB_CORP_NAME,
       ROUND(CLB.CLB_LOAN_MONEY, 2) AS CLB_LOAN_MONEY,
       ROUND(NVL(SUM(CLA.CLA_MONEY), 0), 2) AS CLA_MONEY,
       ROUND(CB.CLB_BALANCE, 2) AS CLB_BALANCE,
       ROUND(CLB.CLB_FIXED_RATE, 6) AS CLB_FIXED_RATE,
       ROUND(CLB.CLB_AGREEMENT_RATE, 6) AS CLB_AGREEMENT_RATE,
       CLB.CLB_START_DATE,
       CLB.CLB_END_DATE,
       CB.Notice_Num,
       CB.FIX_FEE,
       CB.FIX_FEE_REAL,
       CB.AGREEMENT_FEE,
       CB.AGREEMENT_FEE_REAL,
       CB.BILLING_ID,
       CB.MAKER,
       CB.AUDITOR,
       BU.USER_NAME AS MAKER_NAME,
       BU2.USER_NAME AS AUDITOR_NAME,
       CB.STATUS
FROM CMS_LOAN_BILL CLB
LEFT  JOIN CMS_LOAN_ABATE CLA ON CLB.CLB_ID = CLA.CLB_ID
INNER JOIN BT_CORP BL ON CLB.CLB_LOAN_CORP_ID = BL.ID
INNER JOIN BT_CORP BB ON CLB.CLB_BORROW_CORP_ID = BB.ID
INNER JOIN CMS_BILLING CB ON CLB.CLB_ID = CB.CLB_ID
LEFT  JOIN BT_USER BU ON CB.MAKER=BU.USER_CODE
LEFT  JOIN BT_USER BU2 ON CB.AUDITOR=BU2.USER_CODE
WHERE CLB.CLB_STATUS=95 AND CB.STATUS <> -12
GROUP BY CLB.CLB_ID,
         CLB.CLB_NO,
         CLB.CLB_LOAN_CORP_ID,
         BL.CORP_CODE,
         BL.CORP_NAME,
         CLB.CLB_BORROW_CORP_ID,
         BB.CORP_CODE,
         BB.CORP_NAME,
         CLB.CLB_LOAN_MONEY,
         CB.CLB_BALANCE,
         CLB.CLB_FIXED_RATE,
         CLB.CLB_AGREEMENT_RATE,
         CLB.CLB_START_DATE,
         CLB.CLB_END_DATE,
         CB.Notice_Num,
         CB.FIX_FEE,
         CB.FIX_FEE_REAL,
         CB.AGREEMENT_FEE,
         CB.AGREEMENT_FEE_REAL,
         BU.USER_NAME,
         BU2.USER_NAME,
         CB.MAKER,
         CB.AUDITOR,
         CB.BILLING_ID,
         CB.STATUS;

