CREATE OR REPLACE VIEW V_CMS_LOAN_BOOK AS
SELECT CLB.CLB_ID,
       CLB.CLB_NO,
       CLB.CLB_LOAN_CORP_ID AS BL_CORP_ID,
       BL.CORP_CODE AS BL_CORP_CODE,
       BL.CORP_NAME AS BL_CORP_NAME,
       CLB.CLB_BORROW_CORP_ID AS BB_CORP_ID,
       BB.CORP_CODE AS BB_CORP_CODE,
       BB.CORP_NAME AS BB_CORP_NAME,
       ROUND(CLB.CLB_LOAN_MONEY, 2) AS CLB_LOAN_MONEY,       
       (SELECT NVL(SUM(CLA.CLA_MONEY), 0) FROM CMS_LOAN_ABATE CLA WHERE CLB.CLB_ID = CLA.CLB_ID) AS CLA_MONEY,       
       ROUND(NVL(CLB.CLB_BALANCE, 0), 2) AS CLB_BALANCE,
       ROUND(NVL(CLB.CLB_FIXED_RATE, 0), 6) AS CLB_FIXED_RATE,
       ROUND(NVL(CLB.CLB_AGREEMENT_RATE, 0), 6) AS CLB_AGREEMENT_RATE,          
       (SELECT NVL(SUM(CRL.CRL_MONEY), 0) FROM CMS_REPAY_LOAN CRL WHERE CLB.CLB_ID = CRL.CLB_ID) AS CRL_MONEY,       
       (SELECT NVL(SUM(CBI.FIX_FEE_REAL), 0) FROM CMS_BILLING CBI WHERE CLB.CLB_ID = CBI.CLB_ID) AS FIX_FEE_REAL,
       (SELECT NVL(SUM(CBI.AGREEMENT_FEE_REAL), 0) FROM CMS_BILLING CBI WHERE CLB.CLB_ID = CBI.CLB_ID) AS AGREEMENT_FEE_REAL,       
       (SELECT NVL(SUM(CRL.CRL_FIXED_MONEY), 0) FROM CMS_REPAY_LOAN CRL WHERE CLB.CLB_ID = CRL.CLB_ID) AS CRL_FIXED_MONEY,
       (SELECT NVL(SUM(CRL.CRL_AGREEMENT_MONEY), 0) FROM CMS_REPAY_LOAN CRL WHERE CLB.CLB_ID = CRL.CLB_ID) AS CRL_AGREEMENT_MONEY,              
       (SELECT NVL(SUM(CPR.CPR_FIXED_MONEY), 0) FROM CMS_PAYMENT_RECORDS CPR WHERE CLB.CLB_ID = CPR.CLB_ID) AS CPR_FIXED_MONEY,
       (SELECT NVL(SUM(CPR.CPR_AGREEMENT_MONEY), 0) FROM CMS_PAYMENT_RECORDS CPR WHERE CLB.CLB_ID = CPR.CLB_ID) AS CPR_AGREEMENT_MONEY,       
       CLB.CLB_START_DATE,
       CLB.CLB_END_DATE,
       CLB.CLB_STATUS,
       CLB.USER_ID,
       CLB.APPROVES
  FROM CMS_LOAN_BILL CLB
 INNER JOIN BT_CORP BL ON CLB.CLB_LOAN_CORP_ID = BL.ID
 INNER JOIN BT_CORP BB ON CLB.CLB_BORROW_CORP_ID = BB.ID;