--修改日期：2013.01.09
--修改人：刘之三
--修改内容：自动扫描预警
--修改原因：自动扫描预警
DECLARE
  VN_COUNT     NUMBER;
  VC_STR       VARCHAR2(1000);
BEGIN
  --查看该表中该字段是否存在
  SELECT COUNT(*) 
    INTO VN_COUNT 
    FROM USER_TAB_COLUMNS 
   WHERE TABLE_NAME = 'BT_WARNING_BALANCEDOWN' AND COLUMN_NAME = 'STRATEGY_DETAIL_STR';
  --如果不小于1则说明不存在，则新增此字段
  IF VN_COUNT >= 1 THEN
    VC_STR := ' ALTER TABLE BT_WARNING_BALANCEDOWN MODIFY (STRATEGY_DETAIL_STR VARCHAR2(200))';
    EXECUTE IMMEDIATE VC_STR;
  END IF;
END;
/

DECLARE
  VN_COUNT     NUMBER;
  VC_STR       VARCHAR2(1000);
BEGIN
  --查看该表中该字段是否存在
  SELECT COUNT(*) 
    INTO VN_COUNT 
    FROM USER_TAB_COLUMNS 
   WHERE TABLE_NAME = 'BT_WARNING_BAL' AND COLUMN_NAME = 'STRATEGY_DETAIL_STR';
  --如果不小于1则说明不存在，则新增此字段
  IF VN_COUNT >= 1 THEN
    VC_STR := ' ALTER TABLE BT_WARNING_BAL MODIFY (STRATEGY_DETAIL_STR VARCHAR2(200))';
    EXECUTE IMMEDIATE VC_STR;
  END IF;
END;
/

DECLARE
  VN_COUNT     NUMBER;
  VC_STR       VARCHAR2(1000);
BEGIN
  --查看该表中该字段是否存在
  SELECT COUNT(*) 
    INTO VN_COUNT 
    FROM USER_TAB_COLUMNS 
   WHERE TABLE_NAME = 'BT_WARNING_CASH' AND COLUMN_NAME = 'STRATEGY_DETAIL_STR';
  --如果不小于1则说明不存在，则新增此字段
  IF VN_COUNT >= 1 THEN
    VC_STR := ' ALTER TABLE BT_WARNING_CASH MODIFY (STRATEGY_DETAIL_STR VARCHAR2(200))';
    EXECUTE IMMEDIATE VC_STR;
  END IF;
END;
/

DECLARE
  VN_COUNT     NUMBER;
  VC_STR       VARCHAR2(1000);
BEGIN
  --查看该表中该字段是否存在
  SELECT COUNT(*) 
    INTO VN_COUNT 
    FROM USER_TAB_COLUMNS 
   WHERE TABLE_NAME = 'BT_WARNING_DEZJZC' AND COLUMN_NAME = 'STRATEGY_DETAIL_STR';
  --如果不小于1则说明不存在，则新增此字段
  IF VN_COUNT >= 1 THEN
    VC_STR := ' ALTER TABLE BT_WARNING_DEZJZC MODIFY (STRATEGY_DETAIL_STR VARCHAR2(200))';
    EXECUTE IMMEDIATE VC_STR;
  END IF;
END;
/

DECLARE
  VN_COUNT     NUMBER;
  VC_STR       VARCHAR2(1000);
BEGIN
  --查看该表中该字段是否存在
  SELECT COUNT(*) 
    INTO VN_COUNT 
    FROM USER_TAB_COLUMNS 
   WHERE TABLE_NAME = 'BT_WARNING_DTLRMK' AND COLUMN_NAME = 'STRATEGY_DETAIL_STR';
  --如果不小于1则说明不存在，则新增此字段
  IF VN_COUNT >= 1 THEN
    VC_STR := ' ALTER TABLE BT_WARNING_DTLRMK MODIFY (STRATEGY_DETAIL_STR VARCHAR2(200))';
    EXECUTE IMMEDIATE VC_STR;
  END IF;
END;
/

DECLARE
  VN_COUNT     NUMBER;
  VC_STR       VARCHAR2(1000);
BEGIN
  --查看该表中该字段是否存在
  SELECT COUNT(*) 
    INTO VN_COUNT 
    FROM USER_TAB_COLUMNS 
   WHERE TABLE_NAME = 'BT_WARNING_LARGEPAY' AND COLUMN_NAME = 'STRATEGY_DETAIL_STR';
  --如果不小于1则说明不存在，则新增此字段
  IF VN_COUNT >= 1 THEN
    VC_STR := ' ALTER TABLE BT_WARNING_LARGEPAY MODIFY (STRATEGY_DETAIL_STR VARCHAR2(200))';
    EXECUTE IMMEDIATE VC_STR;
  END IF;
END;
/

DECLARE
  VN_COUNT     NUMBER;
  VC_STR       VARCHAR2(1000);
BEGIN
  --查看该表中该字段是否存在
  SELECT COUNT(*) 
    INTO VN_COUNT 
    FROM USER_TAB_COLUMNS 
   WHERE TABLE_NAME = 'BT_WARNING_OUTPAY' AND COLUMN_NAME = 'STRATEGY_DETAIL_STR';
  --如果不小于1则说明不存在，则新增此字段
  IF VN_COUNT >= 1 THEN
    VC_STR := ' ALTER TABLE BT_WARNING_OUTPAY MODIFY (STRATEGY_DETAIL_STR VARCHAR2(200))';
    EXECUTE IMMEDIATE VC_STR;
  END IF;
END;
/

DECLARE
  VN_COUNT     NUMBER;
  VC_STR       VARCHAR2(1000);
BEGIN
  --查看该表中该字段是否存在
  SELECT COUNT(*) 
    INTO VN_COUNT 
    FROM USER_TAB_COLUMNS 
   WHERE TABLE_NAME = 'BT_WARNING_OVERFLOW' AND COLUMN_NAME = 'STRATEGY_DETAIL_STR';
  --如果不小于1则说明不存在，则新增此字段
  IF VN_COUNT >= 1 THEN
    VC_STR := ' ALTER TABLE BT_WARNING_OVERFLOW MODIFY (STRATEGY_DETAIL_STR VARCHAR2(200))';
    EXECUTE IMMEDIATE VC_STR;
  END IF;
END;
/

DECLARE
  VN_COUNT     NUMBER;
  VC_STR       VARCHAR2(1000);
BEGIN
  --查看该表中该字段是否存在
  SELECT COUNT(*) 
    INTO VN_COUNT 
    FROM USER_TAB_COLUMNS 
   WHERE TABLE_NAME = 'BT_WARNING_PAYEE' AND COLUMN_NAME = 'STRATEGY_DETAIL_STR';
  --如果不小于1则说明不存在，则新增此字段
  IF VN_COUNT >= 1 THEN
    VC_STR := ' ALTER TABLE BT_WARNING_PAYEE MODIFY (STRATEGY_DETAIL_STR VARCHAR2(200))';
    EXECUTE IMMEDIATE VC_STR;
  END IF;
END;
/

DECLARE
  VN_COUNT     NUMBER;
  VC_STR       VARCHAR2(1000);
BEGIN
  --查看该表中该字段是否存在
  SELECT COUNT(*) 
    INTO VN_COUNT 
    FROM USER_TAB_COLUMNS 
   WHERE TABLE_NAME = 'BT_WARNING_SWYZSB' AND COLUMN_NAME = 'STRATEGY_DETAIL_STR';
  --如果不小于1则说明不存在，则新增此字段
  IF VN_COUNT >= 1 THEN
    VC_STR := ' ALTER TABLE BT_WARNING_SWYZSB MODIFY (STRATEGY_DETAIL_STR VARCHAR2(200))';
    EXECUTE IMMEDIATE VC_STR;
  END IF;
END;
/

DECLARE
  VN_COUNT     NUMBER;
  VC_STR       VARCHAR2(1000);
BEGIN
  --查看该表中该字段是否存在
  SELECT COUNT(*) 
    INTO VN_COUNT 
    FROM USER_TAB_COLUMNS 
   WHERE TABLE_NAME = 'BT_WARNING_ZCHLR' AND COLUMN_NAME = 'STRATEGY_DETAIL_STR';
  --如果不小于1则说明不存在，则新增此字段
  IF VN_COUNT >= 1 THEN
    VC_STR := ' ALTER TABLE BT_WARNING_ZCHLR MODIFY (STRATEGY_DETAIL_STR VARCHAR2(200))';
    EXECUTE IMMEDIATE VC_STR;
  END IF;
END;
/