--修改日期：20121102
--修改人：叶爱军
--需求编号：SX-AKS1-002 财务费用-币别
--参数设置：
DECLARE
  V_CNT_0 INTEGER;
BEGIN
  SELECT COUNT(1) INTO V_CNT_0 FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'RAT_URATION' AND COLUMN_NAME = 'CUR_CODE';
  
  --RAT_URATION添加OPEN_MONEY字段
  IF V_CNT_0 = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RAT_URATION ADD CUR_CODE VARCHAR(2)';
  END IF;
  COMMIT;
  
  UPDATE RAT_URATION RU SET RU.CUR_CODE = (SELECT BC.CUR_CODE FROM BT_CURRENCY BC WHERE BC.CUR_NAME = '人民币' AND BC.VALID_SIGN = '1' AND BC.STATUS = '1');
  COMMIT;
END;
/