
--增加借款单位
ALTER TABLE CMS_LOAN_INFO ADD BORROW_CORP_ID VARCHAR(4);
GO
UPDATE CMS_LOAN_INFO SET BORROW_CORP_ID = NET_CODE;
GO

--增加付息方式
ALTER TABLE CMS_PROVIDE_LOAN_INFO ADD PAY_INTEREST VARCHAR(3);
GO
UPDATE CMS_PROVIDE_LOAN_INFO SET PAY_INTEREST = '001';
GO