--修改日期：2013.01.09
--修改人：刘之三
--修改内容：自动扫描预警
--修改原因：自动扫描预警
IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('BT_WARNING_BAL') AND NAME='STRATEGY_DETAIL_STR')  
ALTER TABLE BT_WARNING_BAL ALTER COLUMN STRATEGY_DETAIL_STR VARCHAR(200); 
GO

IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('Bt_Warning_Balancedown') AND NAME='STRATEGY_DETAIL_STR')  
ALTER TABLE Bt_Warning_Balancedown ALTER COLUMN STRATEGY_DETAIL_STR VARCHAR(200); 
GO

IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('BT_WARNING_CASH') AND NAME='STRATEGY_DETAIL_STR')  
ALTER TABLE BT_WARNING_CASH ALTER COLUMN STRATEGY_DETAIL_STR VARCHAR(200); 
GO

IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('BT_WARNING_DEZJZC') AND NAME='STRATEGY_DETAIL_STR')  
ALTER TABLE BT_WARNING_DEZJZC ALTER COLUMN STRATEGY_DETAIL_STR VARCHAR(200); 
GO

IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('BT_WARNING_DTLRMK') AND NAME='STRATEGY_DETAIL_STR')  
ALTER TABLE BT_WARNING_DTLRMK ALTER COLUMN STRATEGY_DETAIL_STR VARCHAR(200); 
GO

IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('BT_WARNING_LARGEPAY') AND NAME='STRATEGY_DETAIL_STR')  
ALTER TABLE BT_WARNING_LARGEPAY ALTER COLUMN STRATEGY_DETAIL_STR VARCHAR(200); 
GO

IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('BT_WARNING_OUTPAY') AND NAME='STRATEGY_DETAIL_STR')  
ALTER TABLE BT_WARNING_OUTPAY ALTER COLUMN STRATEGY_DETAIL_STR VARCHAR(200); 
GO

IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('BT_WARNING_SWYZSB') AND NAME='STRATEGY_DETAIL_STR')  
ALTER TABLE BT_WARNING_SWYZSB ALTER COLUMN STRATEGY_DETAIL_STR VARCHAR(200); 
GO

IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('BT_WARNING_ZCHLR') AND NAME='STRATEGY_DETAIL_STR')  
ALTER TABLE BT_WARNING_ZCHLR ALTER COLUMN STRATEGY_DETAIL_STR VARCHAR(200); 
GO

IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('BT_WARNING_PAYEE') AND NAME='STRATEGY_DETAIL_STR')  
ALTER TABLE BT_WARNING_PAYEE ALTER COLUMN STRATEGY_DETAIL_STR VARCHAR(200); 
GO

IF EXISTS(SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('BT_WARNING_OVERFLOW') AND NAME='STRATEGY_DETAIL_STR')  
ALTER TABLE BT_WARNING_OVERFLOW ALTER COLUMN STRATEGY_DETAIL_STR VARCHAR(200); 
GO