
 --蒲勇军
 --2013-02-26 18:12:24
 --删除多余菜单
 
 DELETE FROM BT_SYS_RES   WHERE  RES_NAME = '预警策略查询' AND SYS_CODE = 'fwg' AND RES_CODE NOT IN (SELECT MAX(RES_CODE) FROM BT_SYS_RES WHERE RES_NAME = '预警策略查询' AND SYS_CODE = 'fwg' )  
 go
 
