--修改日期：20130107
--修改人：祁继鸿
--修改内容：vp7451 增加自开票据 与 付款单相关联的bill_no
--修改内容 AB_EMIT 增加字段 付款单编号BILL_NO
--参数设置：
DECLARE
  ERP_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO ERP_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'AB_EMIT' AND COLUMN_NAME = 'BILL_NO';
  IF ERP_COUNT = 0 THEN
     EXECUTE IMMEDIATE 'ALTER TABLE AB_EMIT ADD BILL_NO VARCHAR2(20)';
  END IF;
END;
/
--修改日期：20130107
--修改人：祁继鸿
--修改内容：vp7451 增加库存票据 与 付款单相关联的bill_no
--修改内容  AB_RECEIVE 增加字段 付款单编号BILL_NO
--参数设置：
DECLARE
  ERP_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO ERP_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'AB_RECEIVE' AND COLUMN_NAME = 'BILL_NO';
  IF ERP_COUNT = 0 THEN
     EXECUTE IMMEDIATE 'ALTER TABLE AB_RECEIVE ADD BILL_NO VARCHAR2(20)';
  END IF;
END;
/

--修改日期：20130108
--修改人：李德成
--修改内容：背书增加后手单位编码
--修改内容  AB_RECEIVE 增加字段 付款单编号NEXT_VENDOR_NUM
--参数设置：
DECLARE
  ERP_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO ERP_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'AB_RECEIVE' AND COLUMN_NAME = 'NEXT_VENDOR_NUM';
  IF ERP_COUNT = 0 THEN
     EXECUTE IMMEDIATE 'ALTER TABLE AB_RECEIVE ADD NEXT_VENDOR_NUM VARCHAR2(31)';
  END IF;
END;
/
