--修改日期：20121009
--修改人：叶爱军
--需求编号：SX-AKS1-001 系统功能-单位银行授信使用统计表
--修改内容：系统菜单 增加 单位银行授信使用统计表
--参数设置：
IF NOT EXISTS (SELECT * FROM BT_SYS_RES WHERE RES_NAME = '单位银行授信使用统计表' AND SYS_CODE = 'rat')
INSERT INTO BT_SYS_RES (RES_CODE, RES_NAME, SYS_CODE, FATHER_CODE, RES_URL, FUNC_FLAG, RES_TYPE, LINK_TARGET, STATUS, RES_ORDER, RMK, REVERSE1, REVERSE2, REVERSE3, REVERSE4, REVERSE5, REVERSE6, REVERSE7, REVERSE8, REVERSE9, REVERSE10, RES_LEVEL, RES_ROLE)
SELECT (SELECT MAX(T1.RES_CODE) + 1 FROM BT_SYS_RES T1), '单位银行授信使用统计表', 'rat', RES_CODE, '/rat/ratTotalAction.do?method=doCorpQuery', '0', '0', '0', '0', (SELECT MAX(T2.RES_ORDER)+1 FROM BT_SYS_RES T2 WHERE T2.FATHER_CODE = T3.RES_CODE AND T2.SYS_CODE = 'rat'), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, '' FROM BT_SYS_RES T3 WHERE T3.RES_NAME = '银行授信额度' AND T3.SYS_CODE = 'rat';
GO


--修改日期：20121009
--修改人：叶爱军
--需求编号：SX-AKS1-001 系统功能-银行授信使用统计表
--修改内容：系统菜单 增加 银行授信使用统计表
--参数设置：
IF NOT EXISTS (SELECT * FROM BT_SYS_RES WHERE RES_NAME = '银行授信使用统计表' AND SYS_CODE = 'rat')
INSERT INTO BT_SYS_RES (RES_CODE, RES_NAME, SYS_CODE, FATHER_CODE, RES_URL, FUNC_FLAG, RES_TYPE, LINK_TARGET, STATUS, RES_ORDER, RMK, REVERSE1, REVERSE2, REVERSE3, REVERSE4, REVERSE5, REVERSE6, REVERSE7, REVERSE8, REVERSE9, REVERSE10, RES_LEVEL, RES_ROLE)
SELECT (SELECT MAX(T1.RES_CODE) + 1 FROM BT_SYS_RES T1), '银行授信使用统计表', 'rat', RES_CODE, '/rat/ratTotalAction.do?method=doBankQuery', '0', '0', '0', '0', (SELECT MAX(T2.RES_ORDER)+1 FROM BT_SYS_RES T2 WHERE T2.FATHER_CODE = T3.RES_CODE AND T2.SYS_CODE = 'rat'), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, '' FROM BT_SYS_RES T3 WHERE T3.RES_NAME = '银行授信额度' AND T3.SYS_CODE = 'rat';
GO

--修改日期：20121031
--修改人：叶爱军
--需求编号：SX-AKS1-002
--修改内容：币别汇率
IF EXISTS (SELECT * FROM sysobjects WHERE  name = 'V_FC_EXCRATE_ADJUST')  
DROP VIEW V_FC_EXCRATE_ADJUST  
GO 
CREATE VIEW V_FC_EXCRATE_ADJUST AS
SELECT BC.CUR_CODE,
       BC.CUR_NAME,
       (CASE WHEN FEA.NEW_EXCHANGE_RATE IS NULL THEN BC.CUR_EXRATE ELSE FEA.NEW_EXCHANGE_RATE END) AS NEW_EXCHANGE_RATE,
       (CASE WHEN FEA.ADJUST_TIME IS NULL THEN '1900-01-01' ELSE CONVERT(CHAR(20), FEA.ADJUST_TIME, 120) END) AS ADJUST_TIME
  FROM BT_CURRENCY BC
  LEFT JOIN FC_EXCRATE_ADJUST FEA ON BC.CUR_CODE = FEA.CUR_CODE AND FEA.STATUS = '95';
GO

--修改日期：20121031
--修改人：叶爱军
--需求编号：SX-AKS1-002
--修改内容：根据币别、时间获取汇率

IF EXISTS(SELECT 1  FROM SYSOBJECTS WHERE XTYPE = 'FN' AND NAME='FUN_GETRATE')
DROP FUNCTION FUN_GETRATE
GO
CREATE FUNCTION FUN_GETRATE(@V_CUR_CODE VARCHAR, @V_ADJUST_TIME VARCHAR)
  RETURNS NUMERIC AS
BEGIN
  DECLARE @V_EXCHANGE_RATE NUMERIC(12, 8)
  SELECT TOP 1 @V_EXCHANGE_RATE = VFEA.NEW_EXCHANGE_RATE FROM V_FC_EXCRATE_ADJUST VFEA WHERE VFEA.CUR_CODE = '02' AND VFEA.ADJUST_TIME <= '2012-10-29' ORDER BY VFEA.ADJUST_TIME DESC
  RETURN @V_EXCHANGE_RATE
END
GO


--修改日期：20121102
--修改人：叶爱军
--需求编号：SX-AKS1-002 财务费用-币别
--参数设置：
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'CUR_CODE' AND LTRIM(B.NAME) = 'RAT_URATION')
	ALTER TABLE RAT_URATION ADD CUR_CODE VARCHAR(2)
GO

--修改日期：20121207
--修改人：叶爱军
--修改内容：RAT_URATION_APPLY修改INTEREST_RATE的类型NUMERIC(6, 4)改为NUMERIC(8, 6)
--参数设置：
ALTER TABLE RAT_URATION_APPLY ALTER COLUMN INTEREST_RATE NUMERIC(10,6);
GO


--修改时间：20121207
--修改人：叶爱军
--描述：RAT_URATION添加OPEN_MONEY字段
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'OPEN_MONEY' AND LTRIM(B.NAME) = 'RAT_URATION')
	ALTER TABLE RAT_URATION ADD OPEN_MONEY NUMERIC(18, 2)
GO


--日期：2012-10-19 
--修改人：张培
--修改内容：创建表
--授信额度 >> 银行授信额度综合品种单项及组合项
IF EXISTS (SELECT 1 FROM SYSOBJECTS WHERE ID = OBJECT_ID('RAT_COMPOSITIVE_DETAIL') AND TYPE = 'U')
   DROP TABLE RAT_COMPOSITIVE_DETAIL
GO
CREATE TABLE RAT_COMPOSITIVE_DETAIL(
    CODE        	VARCHAR(20) NOT NULL,
    REF_CODE    	VARCHAR(20),
    ITEM_CODE   	VARCHAR(500),
    MONEY       	NUMERIC(18,2),
    FLAG        	CHAR(1),
    REF_TYPE    	CHAR(1),
    PROCESS_MONEY 	NUMERIC(18,2),
    RELIEF_MONEY 	NUMERIC(18,2),
    BY_RELIEF_MONEY NUMERIC(18,2),
    FREEZE_MONEY 	NUMERIC(18,2),
    RAT_CODE 		VARCHAR(20),
    COMP_CODE 		VARCHAR(20)
)
GO

ALTER TABLE RAT_COMPOSITIVE_DETAIL
  ADD CONSTRAINT COMPOSITIVE_DETAIL_PK PRIMARY KEY (CODE);
GO

--修改时间2012-11-17
--修改人 李鹏飞
--修改内容  RAT_BKRATION_DIS和RAT_BKRATION_DIS_DETAIL添加字段 
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'DISTRIBUTE_WAY' AND LTRIM(B.NAME) = 'RAT_BKRATION_DIS')
	--分配方式
	ALTER TABLE RAT_BKRATION_DIS ADD DISTRIBUTE_WAY VARCHAR(10)
GO

IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'ISPASSED' AND LTRIM(B.NAME) = 'RAT_BKRATION_DIS')
	--一批单位或网点中是否已经有记录审批通过了
	ALTER TABLE RAT_BKRATION_DIS ADD ISPASSED VARCHAR(10)
GO

IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'ALL_COMP_CODES' AND LTRIM(B.NAME) = 'RAT_BKRATION_DIS')
	--保存一批分配的单位或网点编号 
	ALTER TABLE RAT_BKRATION_DIS ADD ALL_COMP_CODES VARCHAR(500);
GO

IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'VIRTUAL_URATION' AND LTRIM(B.NAME) = 'RAT_BKRATION_DIS_DETAIL')
	--全额共享时，保存本身不占用的金额
	ALTER TABLE RAT_BKRATION_DIS_DETAIL ADD VIRTUAL_URATION NUMERIC(15,2) DEFAULT 0;
GO

IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'VIRTUAL_RELIEF_MONEY' AND LTRIM(B.NAME) = 'RAT_BKRATION_DIS_DETAIL')
	--虚拟调剂金额
	ALTER TABLE RAT_BKRATION_DIS_DETAIL ADD VIRTUAL_RELIEF_MONEY NUMERIC(15,2) DEFAULT 0;
GO

IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'GUARANTEEUNIT' AND LTRIM(B.NAME) = 'RAT_BKRATION')
	--担保单位
	ALTER TABLE RAT_BKRATION ADD GUARANTEEUNIT VARCHAR(100);
GO

IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'GUARANTEECONTRACT' AND LTRIM(B.NAME) = 'RAT_BKRATION')
	--担保合同
	ALTER TABLE RAT_BKRATION ADD GUARANTEECONTRACT VARCHAR(50);
GO

IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'ATTACHFILEPATH' AND LTRIM(B.NAME) = 'RAT_BKRATION')
	--附件路径
	ALTER TABLE RAT_BKRATION ADD ATTACHFILEPATH VARCHAR(255);
GO



--修改日期：2012.11.30
--修改人：祁继鸿
--修改内容：user00035243
--修改原因：对银行授信待审批列表，在当前位置地址多了“审批”二字需要去掉
UPDATE BT_APPROVE_BUSINESS SET BUSINESS_NAME='银行额度申请占用' WHERE BUSINESS_NAME='银行额度申请占用审批';
UPDATE BT_APPROVE_BUSINESS SET BUSINESS_NAME='银行额度录入' WHERE BUSINESS_NAME='银行额度录入审批';
UPDATE BT_APPROVE_BUSINESS SET BUSINESS_NAME='银行额度分配' WHERE BUSINESS_NAME='银行额度分配审批';
UPDATE BT_APPROVE_BUSINESS SET BUSINESS_NAME='银行额度调剂' WHERE BUSINESS_NAME='银行额度调剂审批';
UPDATE BT_APPROVE_BUSINESS SET BUSINESS_NAME='内部额度录入' WHERE BUSINESS_NAME='内部额度录入审批';
UPDATE BT_APPROVE_BUSINESS SET BUSINESS_NAME='内部额度申请占用' WHERE BUSINESS_NAME='内部额度申请占用审批';
UPDATE BT_APPROVE_BUSINESS SET BUSINESS_NAME='内部额度追加' WHERE BUSINESS_NAME='内部额度追加审批';
UPDATE RAT_URATION SET CUR_CODE = (SELECT BC.CUR_CODE FROM BT_CURRENCY BC WHERE BC.CUR_NAME = '人民币' AND BC.VALID_SIGN = '1' AND BC.STATUS = '1')
GO

--修改日期：20121217
--修改人：李鹏飞
--修改内容：RAT_BKRATION_DIS_DETAIL添加RELIEF_AND_URATION_MONEY
--添加原因：总额共享分配时审批通过之后把非调剂与占用金额保存到RELIEF_AND_URATION_MONEY
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'RELIEF_AND_URATION_MONEY' AND LTRIM(B.NAME) = 'RAT_BKRATION_DIS_DETAIL')
	ALTER TABLE RAT_BKRATION_DIS_DETAIL ADD RELIEF_AND_URATION_MONEY NUMERIC(15,2) DEFAULT 0;
GO



--修改日期：20121221
--修改人：李鹏飞
--修改内容：RAT_BKRATION_DETAIL添加TOTAL_MONEY_ADD_MONEY
--添加原因：总额共享单位的银行追加与集团追加金额
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'TOTAL_MONEY_ADD_MONEY' AND LTRIM(B.NAME) = 'RAT_BKRATION_DETAIL')
	ALTER TABLE RAT_BKRATION_DETAIL ADD TOTAL_MONEY_ADD_MONEY NUMERIC(15,2) DEFAULT 0;
GO


--修改时间2012-11-18
--修改人 黄盈
--修改内容  rat_bkration添加字段
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'GUARANTEEUNIT' AND LTRIM(B.NAME) = 'RAT_BKRATION')
	--担保单位
	ALTER TABLE RAT_BKRATION ADD GUARANTEEUNIT VARCHAR(100);
GO

IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'GUARANTEECONTRACT' AND LTRIM(B.NAME) = 'RAT_BKRATION')
	--担保合同
	ALTER TABLE RAT_BKRATION ADD GUARANTEECONTRACT VARCHAR(50);
GO

IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'ATTACHFILEPATH' AND LTRIM(B.NAME) = 'RAT_BKRATION')
	--附件路径
	ALTER TABLE RAT_BKRATION ADD ATTACHFILEPATH VARCHAR(255);
GO



--修改日期：20121221
--修改人：李鹏飞
--修改内容：RAT_BKRATION_DETAIL和RAT_BKRATION_DIS_DETAIL表添加字段
--添加原因：敞口额度

IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'TOTAL_MONEY_ADD_OPEN_MONEY' AND LTRIM(B.NAME) = 'RAT_BKRATION_DETAIL')
--总额共享分配单位的敞口额度追加金额
	ALTER TABLE RAT_BKRATION_DETAIL ADD TOTAL_MONEY_ADD_OPEN_MONEY NUMERIC(18,2) DEFAULT 0;
GO

IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'VIRUTAL_RELIEF_OPEN_MONEY' AND LTRIM(B.NAME) = 'RAT_BKRATION_DIS_DETAIL')
--总额共享分配单位的敞口额度调剂金额
	ALTER TABLE RAT_BKRATION_DIS_DETAIL ADD VIRUTAL_RELIEF_OPEN_MONEY NUMERIC(18,2) DEFAULT 0;
GO

IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'VIRUTAL_OPEN_URATION' AND LTRIM(B.NAME) = 'RAT_BKRATION_DIS_DETAIL')
--总额共享分配单位的敞口额度审批中占用金额
	ALTER TABLE RAT_BKRATION_DIS_DETAIL ADD VIRUTAL_OPEN_URATION NUMERIC(18,2) DEFAULT 0;
GO

IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'URATION_OPEN_MONEY' AND LTRIM(B.NAME) = 'RAT_BKRATION_DIS_DETAIL')
--总额共享分配单位的敞口额度审批通过占用金额
	ALTER TABLE RAT_BKRATION_DIS_DETAIL ADD URATION_OPEN_MONEY NUMERIC(18,2) DEFAULT 0;
GO


--追加的敞口额度
update RAT_BKRATION_DETAIL set TOTAL_MONEY_ADD_OPEN_MONEY=0 where TOTAL_MONEY_ADD_OPEN_MONEY is null;
--追加的授信额度
update RAT_BKRATION_DETAIL set TOTAL_MONEY_ADD_MONEY=0 where TOTAL_MONEY_ADD_MONEY is null;
--虚拟的敞口调剂额度
update RAT_BKRATION_DIS_DETAIL set VIRUTAL_RELIEF_OPEN_MONEY=0 where VIRUTAL_RELIEF_OPEN_MONEY is null;
--虚拟的敞口占用额度
update RAT_BKRATION_DIS_DETAIL set VIRUTAL_OPEN_URATION=0 where VIRUTAL_OPEN_URATION is null;
--正式的敞口占用额度
update RAT_BKRATION_DIS_DETAIL set URATION_OPEN_MONEY=0 where URATION_OPEN_MONEY is null;
--正式的授信占用额度
update RAT_BKRATION_DIS_DETAIL set RELIEF_AND_URATION_MONEY=0 where  RELIEF_AND_URATION_MONEY is null;
--虚拟的占用授信额度
update RAT_BKRATION_DIS_DETAIL set VIRTUAL_URATION=0 where  VIRTUAL_URATION is null;
--虚拟的调剂授信额度
update RAT_BKRATION_DIS_DETAIL set VIRTUAL_RELIEF_MONEY=0 where  VIRTUAL_RELIEF_MONEY is null;

--修改人：李鹏飞
--修改时间：2012-12-15
--描述：修改原来历史数据的distribute_way字段的值为3
UPDATE RAT_BKRATION_DIS SET DISTRIBUTE_WAY = '3' WHERE DISTRIBUTE_WAY IS NULL;
GO

--修改日期：20121031
--修改人：叶爱军
--需求编号：SX-AKS1-002
--修改内容：币别汇率
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE  name = 'V_FC_EXCRATE_ADJUST ')  
DROP VIEW V_FC_EXCRATE_ADJUST  
GO 
CREATE VIEW V_FC_EXCRATE_ADJUST AS
SELECT BC.CUR_CODE,
       BC.CUR_NAME,
       (CASE WHEN FEA.NEW_EXCHANGE_RATE IS NULL THEN BC.CUR_EXRATE ELSE FEA.NEW_EXCHANGE_RATE END) AS NEW_EXCHANGE_RATE,
       (CASE WHEN FEA.ADJUST_TIME IS NULL THEN '1900-01-01' ELSE CONVERT(CHAR(20), FEA.ADJUST_TIME, 120) END) AS ADJUST_TIME
  FROM BT_CURRENCY BC
  LEFT JOIN FC_EXCRATE_ADJUST FEA ON BC.CUR_CODE = FEA.CUR_CODE AND FEA.STATUS = '95';
GO

--修改日期：20130109
--修改人：张培
--Bug编号：user00035383
--修改内容：添加综合品种选择单项及组合项编码字段
--授信占用
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'COMP_ITEM_CODE' AND LTRIM(B.NAME) = 'RAT_URATION')
	ALTER TABLE RAT_URATION ADD COMP_ITEM_CODE VARCHAR(500)
GO
--承兑自开  
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'COMP_ITEM_CODE' AND LTRIM(B.NAME) = 'AB_EMIT')
	ALTER TABLE AB_EMIT ADD COMP_ITEM_CODE VARCHAR(500)
GO
--信用证  
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'COMP_ITEM_CODE' AND LTRIM(B.NAME) = 'LC_ENROL')
	ALTER TABLE LC_ENROL ADD COMP_ITEM_CODE VARCHAR(500)
GO
--信贷借款
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'COMP_ITEM_CODE' AND LTRIM(B.NAME) = 'CMS_PROVIDE_LOAN_INFO')
	ALTER TABLE CMS_PROVIDE_LOAN_INFO ADD COMP_ITEM_CODE VARCHAR(500)
GO
--授信申请
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'COMP_ITEM_CODE' AND LTRIM(B.NAME) = 'RAT_URATION_APPLY')
	ALTER TABLE RAT_URATION_APPLY ADD COMP_ITEM_CODE VARCHAR(500)
GO

ALTER TABLE RAT_BKRATION_DETAIL ALTER COLUMN INTERESTRATE NUMERIC(15,6);
GO

--修改日期：20121031
--修改人：叶爱军
--需求编号：SX-AKS1-002
--修改内容：综合单项的共享额度
IF EXISTS(SELECT 1  FROM SYSOBJECTS WHERE XTYPE = 'FN' AND NAME='FUN_GET_PROCESS_MONEY_SIN')
DROP FUNCTION FUN_GET_PROCESS_MONEY_SIN
GO
CREATE FUNCTION FUN_GET_PROCESS_MONEY_SIN(@V_RATION_CODE VARCHAR, @V_ITEM_CODE VARCHAR, @V_COMPCODE VARCHAR)
  RETURNS NUMERIC AS
BEGIN
  DECLARE @V_PROCESS_MONEY NUMERIC(15, 2)
  SELECT @V_PROCESS_MONEY = ISNULL(SUM(T.V_PROCESS_MONEY), 0)
  FROM (SELECT (CASE WHEN LEN(RC.ITEM_CODE) = 9 THEN RC.MONEY ELSE 0 END) AS V_PROCESS_MONEY
  FROM RAT_COMPOSITIVE_DETAIL RC JOIN RAT_URATION RU ON RC.RAT_CODE = RU.RATION_CODE AND RC.REF_CODE = RU.BILLNO
  AND PATINDEX(RU.COMP_ITEM_CODE, RC.ITEM_CODE) >= 1 WHERE RC.REF_TYPE = '6' AND RC.RAT_CODE = @V_RATION_CODE AND RU.RATION_CODE = @V_RATION_CODE
  AND PATINDEX(RC.ITEM_CODE, @V_ITEM_CODE) >= 1 AND RU.STATUS IN ('1', '2')
  AND RC.COMP_CODE IN (SELECT RBD.COMPCODE FROM RAT_BKRATION_DIS RBD WHERE RBD.RAT_CODE = @V_RATION_CODE AND RBD.DISTRIBUTE_WAY = '2') GROUP BY RC.ITEM_CODE, RC.REF_CODE, RC.MONEY) T
  RETURN @V_PROCESS_MONEY
END
GO

--修改日期：20121031
--修改人：叶爱军
--需求编号：SX-AKS1-002
--修改内容：综合组合项的共享额度
IF EXISTS(SELECT 1  FROM SYSOBJECTS WHERE XTYPE = 'FN' AND NAME='FUN_GET_PROCESS_MONEY_COM')
DROP FUNCTION FUN_GET_PROCESS_MONEY_COM
GO
CREATE FUNCTION FUN_GET_PROCESS_MONEY_COM(@V_RATION_CODE VARCHAR, @V_ITEM_CODE VARCHAR, @V_COMPCODE VARCHAR)
  RETURNS NUMERIC AS
BEGIN
  DECLARE @V_PROCESS_MONEY NUMERIC(15, 2)
  SELECT @V_PROCESS_MONEY = ISNULL(SUM(T.V_PROCESS_MONEY), 0)
  FROM (SELECT DISTINCT RC.REF_CODE, RC.MONEY AS V_PROCESS_MONEY
  FROM RAT_COMPOSITIVE_DETAIL RC JOIN RAT_URATION RU ON RC.RAT_CODE = RU.RATION_CODE AND RC.REF_CODE = RU.BILLNO
  AND PATINDEX(RU.COMP_ITEM_CODE, RC.ITEM_CODE) >= 1 WHERE RC.REF_TYPE = '6' AND RC.RAT_CODE = @V_RATION_CODE AND RU.RATION_CODE = @V_RATION_CODE
  AND PATINDEX(RC.ITEM_CODE, @V_ITEM_CODE) >= 1 AND RU.STATUS IN ('1', '2')
  AND RC.COMP_CODE IN (SELECT RBD.COMPCODE FROM RAT_BKRATION_DIS RBD WHERE RBD.RAT_CODE = @V_RATION_CODE AND RBD.DISTRIBUTE_WAY = '2') GROUP BY RC.ITEM_CODE, RC.REF_CODE, RC.MONEY) T
  RETURN @V_PROCESS_MONEY
END
GO