--修改日期：20121009
--修改人：叶爱军
--需求编号：SX-AKS1-002 系统功能-单位银行授信使用统计表
--修改内容：系统菜单 增加 单位银行授信使用统计表
--参数设置：
DECLARE
  VN_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO VN_COUNT FROM BT_SYS_RES WHERE RES_NAME = '单位银行授信使用统计表' AND SYS_CODE = 'rat';
  IF VN_COUNT < 1 THEN
  	INSERT INTO BT_SYS_RES (RES_CODE, RES_NAME, SYS_CODE, FATHER_CODE, RES_URL, FUNC_FLAG, RES_TYPE, LINK_TARGET, STATUS, RES_ORDER, RMK, REVERSE1, REVERSE2, REVERSE3, REVERSE4, REVERSE5, REVERSE6, REVERSE7, REVERSE8, REVERSE9, REVERSE10, RES_LEVEL, RES_ROLE)
	SELECT (SELECT MAX(T1.RES_CODE) + 1 FROM BT_SYS_RES T1), '单位银行授信使用统计表', 'rat', RES_CODE, '/rat/ratTotalAction.do?method=doCorpQuery', '0', '0', '0', '0', (SELECT MAX(T2.RES_ORDER)+1 FROM BT_SYS_RES T2 WHERE T2.FATHER_CODE = T3.RES_CODE AND T2.SYS_CODE = 'rat'), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, '' FROM BT_SYS_RES T3 WHERE T3.RES_NAME = '银行授信额度' AND T3.SYS_CODE = 'rat';
	COMMIT;
 END IF;
END;
/

ALTER SYSTEM SET OPEN_CURSORS = 3000 SCOPE = BOTH;
/

--修改日期：20121009
--修改人：叶爱军
--需求编号：SX-AKS1-003 系统功能-银行授信使用统计表
--修改内容：系统菜单 增加 银行授信使用统计表
--参数设置：
DECLARE
  VN_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO VN_COUNT FROM BT_SYS_RES WHERE RES_NAME = '银行授信使用统计表' AND SYS_CODE = 'rat';
  IF VN_COUNT < 1 THEN
  	INSERT INTO BT_SYS_RES (RES_CODE, RES_NAME, SYS_CODE, FATHER_CODE, RES_URL, FUNC_FLAG, RES_TYPE, LINK_TARGET, STATUS, RES_ORDER, RMK, REVERSE1, REVERSE2, REVERSE3, REVERSE4, REVERSE5, REVERSE6, REVERSE7, REVERSE8, REVERSE9, REVERSE10, RES_LEVEL, RES_ROLE)
	SELECT (SELECT MAX(T1.RES_CODE) + 1 FROM BT_SYS_RES T1), '银行授信使用统计表', 'rat', RES_CODE, '/rat/ratTotalAction.do?method=doBankQuery', '0', '0', '0', '0', (SELECT MAX(T2.RES_ORDER)+1 FROM BT_SYS_RES T2 WHERE T2.FATHER_CODE = T3.RES_CODE AND T2.SYS_CODE = 'rat'), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, '' FROM BT_SYS_RES T3 WHERE T3.RES_NAME = '银行授信额度' AND T3.SYS_CODE = 'rat';
	COMMIT;
 END IF;
END;
/

--修改日期：20121031
--修改人：叶爱军
--需求编号：SX-AKS1-002
--修改内容：币别汇率
CREATE OR REPLACE VIEW V_FC_EXCRATE_ADJUST AS
SELECT BC.CUR_CODE,
       BC.CUR_NAME,
       (CASE WHEN FEA.NEW_EXCHANGE_RATE IS NULL THEN BC.CUR_EXRATE ELSE FEA.NEW_EXCHANGE_RATE END) AS NEW_EXCHANGE_RATE,
       (CASE WHEN FEA.ADJUST_TIME IS NULL THEN '1900-01-01' ELSE TO_CHAR(FEA.ADJUST_TIME, 'YYYY-MM-DD') END) AS ADJUST_TIME
  FROM BT_CURRENCY BC
  LEFT JOIN FC_EXCRATE_ADJUST FEA ON BC.CUR_CODE = FEA.CUR_CODE AND FEA.STATUS = '95';

--修改日期：20121031
--修改人：叶爱军
--需求编号：SX-AKS1-002
--修改内容：根据币别、时间获取汇率
CREATE OR REPLACE FUNCTION FUN_GETRATE(V_CUR_CODE IN VARCHAR2, V_ADJUST_TIME IN VARCHAR2)
  RETURN NUMBER IS
  V_EXCHANGE_RATE NUMBER(12, 8);
BEGIN
  SELECT NEW_EXCHANGE_RATE INTO V_EXCHANGE_RATE FROM (SELECT VFEA.NEW_EXCHANGE_RATE FROM V_FC_EXCRATE_ADJUST VFEA WHERE VFEA.CUR_CODE = V_CUR_CODE AND VFEA.ADJUST_TIME <= V_ADJUST_TIME ORDER BY VFEA.ADJUST_TIME DESC) WHERE ROWNUM = 1;
  RETURN V_EXCHANGE_RATE;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RETURN 1;
END;
/

--修改日期：20121207
--修改人：叶爱军
--修改内容：RAT_URATION_APPLY修改INTEREST_RATE的类型NUMBER(6, 4)改为NUMBER(10, 7) 
--参数设置：
ALTER TABLE RAT_URATION_APPLY MODIFY INTEREST_RATE NUMBER(10,6);
COMMIT;
/

--修改时间2012-11-17
--修改人 李鹏飞
--修改内容  RAT_BKRATION_DIS和RAT_BKRATION_DIS_DETAIL添加字段
DECLARE
  V_CNT_0 INTEGER;
  V_CNT_1 INTEGER;
  V_CNT_2 INTEGER;
  V_CNT_3 INTEGER;
  V_CNT_4 INTEGER;
  V_CNT_5 INTEGER;
  V_CNT_6 INTEGER;
  V_CNT_7 INTEGER;
  V_CNT_8 INTEGER;
  V_CNT_9 INTEGER;
BEGIN
  --RAT_URATION添加OPEN_MONEY字段 叶爱军
  SELECT COUNT(1) INTO V_CNT_0 FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'RAT_URATION' AND COLUMN_NAME = 'OPEN_MONEY';
  --分配方式 李鹏飞
  SELECT COUNT(1) INTO V_CNT_1 FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'RAT_BKRATION_DIS' AND COLUMN_NAME = 'DISTRIBUTE_WAY';
  --一批单位或网点中是否已经有记录审批通过了 李鹏飞
  SELECT COUNT(1) INTO V_CNT_2 FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'RAT_BKRATION_DIS' AND COLUMN_NAME = 'ISPASSED';
  --保存一批分配的单位或网点编号 李鹏飞
  SELECT COUNT(1) INTO V_CNT_3 FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'RAT_BKRATION_DIS' AND COLUMN_NAME = 'ALL_COMP_CODES';
  --全额共享时，保存本身不占用的金额 李鹏飞
  SELECT COUNT(1) INTO V_CNT_4 FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'RAT_BKRATION_DIS_DETAIL' AND COLUMN_NAME = 'VIRTUAL_URATION';
  --虚拟调剂金额 李鹏飞
  SELECT COUNT(1) INTO V_CNT_5 FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'RAT_BKRATION_DIS_DETAIL' AND COLUMN_NAME = 'VIRTUAL_RELIEF_MONEY';
  --银行授信额度综合品种单项及组合项 张培
  SELECT COUNT(1) INTO V_CNT_6 FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'RAT_COMPOSITIVE_DETAIL';
  --表RAT_BKRATION 新增字段 担保单位 HUANGY
  SELECT COUNT(1) INTO V_CNT_7 FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'RAT_BKRATION' AND COLUMN_NAME = 'GUARANTEEUNIT';
  --表RAT_BKRATION 新增字段 担保合同 HUANGY
  SELECT COUNT(1) INTO V_CNT_8 FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'RAT_BKRATION' AND COLUMN_NAME = 'GUARANTEECONTRACT';
  --表RAT_BKRATION 新增字段 附件路径 HUANGY
  SELECT COUNT(1) INTO V_CNT_9 FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'RAT_BKRATION' AND COLUMN_NAME = 'ATTACHFILEPATH';

  --RAT_URATION添加OPEN_MONEY字段
  IF V_CNT_0 = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RAT_URATION ADD OPEN_MONEY NUMBER(18, 2) DEFAULT 0';
  END IF;
  --分配方式
  IF V_CNT_1 = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RAT_BKRATION_DIS ADD DISTRIBUTE_WAY VARCHAR2(10)';
  END IF;
  --一批单位或网点中是否已经有记录审批通过了
  IF V_CNT_2 = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RAT_BKRATION_DIS ADD ISPASSED VARCHAR2(10)';
  END IF;
  --保存一批分配的单位或网点编号
  IF V_CNT_3 = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RAT_BKRATION_DIS ADD ALL_COMP_CODES VARCHAR2(500)';
  END IF;
  --全额共享时，保存本身不占用的金额
  IF V_CNT_4 = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RAT_BKRATION_DIS_DETAIL ADD VIRTUAL_URATION NUMBER(15,2) DEFAULT 0';
  END IF;
  --虚拟调剂金额
  IF V_CNT_5 = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RAT_BKRATION_DIS_DETAIL ADD VIRTUAL_RELIEF_MONEY NUMBER(15,2) DEFAULT 0';
  END IF;
  IF V_CNT_6 = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE RAT_COMPOSITIVE_DETAIL (
						CODE VARCHAR2(20) NOT NULL,
						REF_CODE VARCHAR2(20),
						ITEM_CODE VARCHAR2(500),
						MONEY NUMBER(18,2),
						FLAG CHAR(1),
						REF_TYPE CHAR(1),
						PROCESS_MONEY NUMBER(18,2),
						RELIEF_MONEY NUMBER(18,2),
						BY_RELIEF_MONEY NUMBER(18,2),
						FREEZE_MONEY NUMBER(18,2),
						RAT_CODE VARCHAR2(20),
						COMP_CODE VARCHAR2(20)
					  )';
	EXECUTE IMMEDIATE 'ALTER TABLE RAT_COMPOSITIVE_DETAIL ADD CONSTRAINT COMPOSITIVE_DETAIL_PK PRIMARY KEY (CODE)';
  END IF;
  --担保单位
  IF V_CNT_7 = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RAT_BKRATION ADD GUARANTEEUNIT VARCHAR2(100)';
  END IF;
  --担保合同
  IF V_CNT_8 = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RAT_BKRATION ADD GUARANTEECONTRACT VARCHAR2(50)';
  END IF;
  --附件路径
  IF V_CNT_9 = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RAT_BKRATION ADD ATTACHFILEPATH VARCHAR2(255)';
  END IF;
  COMMIT;
END;
/

--修改日期：20121102
--修改人：叶爱军
--需求编号：SX-AKS1-002 财务费用-币别
--参数设置：
DECLARE
  V_CNT_0 INTEGER;
BEGIN
  SELECT COUNT(1) INTO V_CNT_0 FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'RAT_URATION' AND COLUMN_NAME = 'CUR_CODE';

  --RAT_URATION添加OPEN_MONEY字段
  IF V_CNT_0 = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RAT_URATION ADD CUR_CODE VARCHAR(2)';
  END IF;
  COMMIT;
END;
/


--修改日期：2012.11.30
--修改人：祁继鸿
--修改内容：user00035243
--修改原因：对银行授信待审批列表，在当前位置地址多了“审批”二字需要去掉
UPDATE BT_APPROVE_BUSINESS SET BUSINESS_NAME='银行额度申请占用' WHERE BUSINESS_NAME='银行额度申请占用审批';
UPDATE BT_APPROVE_BUSINESS SET BUSINESS_NAME='银行额度录入' WHERE BUSINESS_NAME='银行额度录入审批';
UPDATE BT_APPROVE_BUSINESS SET BUSINESS_NAME='银行额度分配' WHERE BUSINESS_NAME='银行额度分配审批';
UPDATE BT_APPROVE_BUSINESS SET BUSINESS_NAME='银行额度调剂' WHERE BUSINESS_NAME='银行额度调剂审批';
UPDATE BT_APPROVE_BUSINESS SET BUSINESS_NAME='内部额度录入' WHERE BUSINESS_NAME='内部额度录入审批';
UPDATE BT_APPROVE_BUSINESS SET BUSINESS_NAME='内部额度申请占用' WHERE BUSINESS_NAME='内部额度申请占用审批';
UPDATE BT_APPROVE_BUSINESS SET BUSINESS_NAME='内部额度追加' WHERE BUSINESS_NAME='内部额度追加审批';
UPDATE RAT_URATION RU SET RU.CUR_CODE = (SELECT BC.CUR_CODE FROM BT_CURRENCY BC WHERE BC.CUR_NAME = '人民币' AND BC.VALID_SIGN = '1' AND BC.STATUS = '1');
COMMIT;
/


--修改日期：20121217
--修改人：李鹏飞
--修改内容：RAT_BKRATION_DIS_DETAIL添加RELIEF_AND_URATION_MONEY
--添加原因：总额共享分配时审批通过之后把非调剂与占用金额保存到RELIEF_AND_URATION_MONEY
DECLARE
  V_CNT_0 INTEGER;
BEGIN
  SELECT COUNT(1) INTO V_CNT_0 FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'RAT_BKRATION_DIS_DETAIL' AND COLUMN_NAME = 'RELIEF_AND_URATION_MONEY';
    IF V_CNT_0 = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RAT_BKRATION_DIS_DETAIL ADD RELIEF_AND_URATION_MONEY NUMBER(15,2) DEFAULT 0';
   END IF;
   commit;
END;
/


--修改日期：20121221
--修改人：李鹏飞
--修改内容：RAT_BKRATION_DETAIL添加TOTAL_MONEY_ADD_MONEY
--添加原因：总额共享单位的银行追加与集团追加金额
DECLARE
  V_CNT_0 INTEGER;
BEGIN
  SELECT COUNT(1) INTO V_CNT_0 FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'RAT_BKRATION_DETAIL' AND COLUMN_NAME = 'TOTAL_MONEY_ADD_MONEY';
    IF V_CNT_0 = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RAT_BKRATION_DETAIL ADD TOTAL_MONEY_ADD_MONEY NUMBER(15,2) DEFAULT 0';
   END IF;
   commit;
END;
/



--修改时间2012-11-18
--修改人 黄盈
--修改内容  rat_bkration添加字段
DECLARE
  V_CNT_7 INTEGER;
  V_CNT_8 INTEGER;
  V_CNT_9 INTEGER;
BEGIN

  --表RAT_BKRATION 新增字段 担保单位 HUANGY
  SELECT COUNT(1) INTO V_CNT_7 FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'RAT_BKRATION' AND COLUMN_NAME = 'GUARANTEEUNIT';
  --表RAT_BKRATION 新增字段 担保合同 HUANGY
  SELECT COUNT(1) INTO V_CNT_8 FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'RAT_BKRATION' AND COLUMN_NAME = 'GUARANTEECONTRACT';
  --表RAT_BKRATION 新增字段 附件路径 HUANGY
  SELECT COUNT(1) INTO V_CNT_9 FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'RAT_BKRATION' AND COLUMN_NAME = 'ATTACHFILEPATH';

  --担保单位
  IF V_CNT_7 = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RAT_BKRATION ADD GUARANTEEUNIT VARCHAR2(100)';
  END IF;
  --担保合同
  IF V_CNT_8 = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RAT_BKRATION ADD GUARANTEECONTRACT VARCHAR2(50)';
  END IF;
  --附件路径
  IF V_CNT_9 = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RAT_BKRATION ADD ATTACHFILEPATH VARCHAR2(255)';
  END IF;
  COMMIT;
END;
/



--修改日期：20121221
--修改人：李鹏飞
--修改内容：RAT_BKRATION_DETAIL和RAT_BKRATION_DIS_DETAIL表添加字段
--添加原因：敞口额度
DECLARE
  V_CNT_0 INTEGER;
  V_CNT_1 INTEGER;
  V_CNT_2 INTEGER;
  V_CNT_3 INTEGER;
BEGIN

--总额共享分配单位的敞口额度追加金额
  SELECT COUNT(1) INTO V_CNT_0 FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'RAT_BKRATION_DETAIL' AND COLUMN_NAME = 'TOTAL_MONEY_ADD_OPEN_MONEY';
--总额共享分配单位的敞口额度调剂金额
  SELECT COUNT(1) INTO V_CNT_1 FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'RAT_BKRATION_DIS_DETAIL' AND COLUMN_NAME = 'VIRUTAL_RELIEF_OPEN_MONEY';
--总额共享分配单位的敞口额度审批中占用金额
  SELECT COUNT(1) INTO V_CNT_2 FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'RAT_BKRATION_DIS_DETAIL' AND COLUMN_NAME = 'VIRUTAL_OPEN_URATION';
--总额共享分配单位的敞口额度审批通过占用金额
  SELECT COUNT(1) INTO V_CNT_3 FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'RAT_BKRATION_DIS_DETAIL' AND COLUMN_NAME = 'URATION_OPEN_MONEY';


  IF V_CNT_0 = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RAT_BKRATION_DETAIL ADD TOTAL_MONEY_ADD_OPEN_MONEY NUMBER(18, 2) DEFAULT 0';
  END IF;

  IF V_CNT_1 = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RAT_BKRATION_DIS_DETAIL ADD VIRUTAL_RELIEF_OPEN_MONEY NUMBER(18, 2) DEFAULT 0';
  END IF;

  IF V_CNT_2 = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RAT_BKRATION_DIS_DETAIL ADD VIRUTAL_OPEN_URATION NUMBER(18, 2) DEFAULT 0';
  END IF;

  IF V_CNT_3 = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RAT_BKRATION_DIS_DETAIL ADD URATION_OPEN_MONEY NUMBER(18, 2) DEFAULT 0';
  END IF;
  COMMIT;
END;
/

--追加的敞口额度
update RAT_BKRATION_DETAIL set TOTAL_MONEY_ADD_OPEN_MONEY=0 where TOTAL_MONEY_ADD_OPEN_MONEY is null;
--追加的授信额度
update RAT_BKRATION_DETAIL set TOTAL_MONEY_ADD_MONEY=0 where TOTAL_MONEY_ADD_MONEY is null;
--虚拟的敞口调剂额度
update RAT_BKRATION_DIS_DETAIL set VIRUTAL_RELIEF_OPEN_MONEY=0 where VIRUTAL_RELIEF_OPEN_MONEY is null;
--虚拟的敞口占用额度
update RAT_BKRATION_DIS_DETAIL set VIRUTAL_OPEN_URATION=0 where VIRUTAL_OPEN_URATION is null;
--正式的敞口占用额度
update RAT_BKRATION_DIS_DETAIL set URATION_OPEN_MONEY=0 where URATION_OPEN_MONEY is null;
--正式的授信占用额度
update RAT_BKRATION_DIS_DETAIL set RELIEF_AND_URATION_MONEY=0 where  RELIEF_AND_URATION_MONEY is null;
--虚拟的占用授信额度
update RAT_BKRATION_DIS_DETAIL set VIRTUAL_URATION=0 where  VIRTUAL_URATION is null;
--虚拟的调剂授信额度
update RAT_BKRATION_DIS_DETAIL set VIRTUAL_RELIEF_MONEY=0 where  VIRTUAL_RELIEF_MONEY is null;


--修改人：李鹏飞
--修改时间：2012-12-15
--描述：修改原来历史数据的distribute_way字段的值为3
UPDATE RAT_BKRATION_DIS SET DISTRIBUTE_WAY = '3' WHERE DISTRIBUTE_WAY IS NULL;
COMMIT;
/

--修改日期：20121031
--修改人：叶爱军
--需求编号：SX-AKS1-002
--修改内容：币别汇率
CREATE OR REPLACE VIEW V_FC_EXCRATE_ADJUST AS
SELECT BC.CUR_CODE,
       BC.CUR_NAME,
       (CASE WHEN FEA.NEW_EXCHANGE_RATE IS NULL THEN BC.CUR_EXRATE ELSE FEA.NEW_EXCHANGE_RATE END) AS NEW_EXCHANGE_RATE,
       (CASE WHEN FEA.ADJUST_TIME IS NULL THEN '1900-01-01' ELSE TO_CHAR(FEA.ADJUST_TIME, 'YYYY-MM-DD') END) AS ADJUST_TIME
  FROM BT_CURRENCY BC
  LEFT JOIN FC_EXCRATE_ADJUST FEA ON BC.CUR_CODE = FEA.CUR_CODE AND FEA.STATUS = '95';
/

--修改日期：20130109
--修改人：张培
--Bug编号：user00035383
--修改内容：添加占用综合品种选择单项及组合项编码字段
DECLARE
  V_CNT_0 INTEGER;
  V_CNT_1 INTEGER;
  V_CNT_2 INTEGER;
  V_CNT_3 INTEGER;
  V_CNT_4 INTEGER;
BEGIN
--授信占用
  SELECT COUNT(1) INTO V_CNT_0 FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'RAT_URATION' AND COLUMN_NAME = 'COMP_ITEM_CODE';
--承兑自开  
  SELECT COUNT(1) INTO V_CNT_1 FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'AB_EMIT' AND COLUMN_NAME = 'COMP_ITEM_CODE';
--信用证  
  SELECT COUNT(1) INTO V_CNT_2 FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'LC_ENROL' AND COLUMN_NAME = 'COMP_ITEM_CODE';
--信贷借款
  SELECT COUNT(1) INTO V_CNT_3 FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'CMS_PROVIDE_LOAN_INFO' AND COLUMN_NAME = 'COMP_ITEM_CODE';
--授信申请
  SELECT COUNT(1) INTO V_CNT_4 FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'RAT_URATION_APPLY' AND COLUMN_NAME = 'COMP_ITEM_CODE';
  
  IF V_CNT_0 = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RAT_URATION ADD COMP_ITEM_CODE VARCHAR2(500)';
  END IF;
  IF V_CNT_1 = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE AB_EMIT ADD COMP_ITEM_CODE VARCHAR2(500)';
  END IF;
  IF V_CNT_2 = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE LC_ENROL ADD COMP_ITEM_CODE VARCHAR2(500)';
  END IF;
  IF V_CNT_3 = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CMS_PROVIDE_LOAN_INFO ADD COMP_ITEM_CODE VARCHAR2(500)';
  END IF;
  IF V_CNT_4 = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RAT_URATION_APPLY ADD COMP_ITEM_CODE VARCHAR2(500)';
  END IF;
  COMMIT;
END;
/

ALTER TABLE RAT_BKRATION_DETAIL MODIFY INTERESTRATE NUMBER(15, 6);
COMMIT;
/

--修改日期：20130121
--修改人：叶爱军
--需求编号：SX-AKS1-002
--修改内容：综合单项的共享额度
CREATE OR REPLACE FUNCTION FUN_GET_PROCESS_MONEY_SIN(V_RATION_CODE IN VARCHAR2, V_ITEM_CODE IN VARCHAR2)
  RETURN NUMBER IS
  V_PROCESS_MONEY NUMBER(15, 2);
BEGIN
  SELECT NVL(SUM(T.V_PROCESS_MONEY), 0) INTO V_PROCESS_MONEY
    FROM (SELECT (CASE WHEN LENGTH(RC.ITEM_CODE) = 9 THEN RC.MONEY ELSE 0 END) AS V_PROCESS_MONEY
    FROM RAT_COMPOSITIVE_DETAIL RC JOIN RAT_URATION RU ON RC.RAT_CODE = RU.RATION_CODE AND RC.REF_CODE = RU.BILLNO
    AND INSTR(RU.COMP_ITEM_CODE, RC.ITEM_CODE, 1, 1) >= 1 WHERE RC.REF_TYPE = '6' AND RC.RAT_CODE = V_RATION_CODE
    AND RU.RATION_CODE = V_RATION_CODE AND INSTR(V_ITEM_CODE, RC.ITEM_CODE, 1, 1) >= 1 AND RU.STATUS IN ('1', '2')
    AND RC.COMP_CODE IN (SELECT RBD.COMPCODE FROM RAT_BKRATION_DIS RBD WHERE RBD.RAT_CODE = V_RATION_CODE AND RBD.DISTRIBUTE_WAY = '2') GROUP BY RC.ITEM_CODE, RC.REF_CODE, RC.MONEY) T;
  RETURN V_PROCESS_MONEY;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RETURN 0;
END;
/

--修改日期：20130121
--修改人：叶爱军
--需求编号：SX-AKS1-002
--修改内容：综合组合项的共享额度
CREATE OR REPLACE FUNCTION FUN_GET_PROCESS_MONEY_COM(V_RATION_CODE IN VARCHAR2, V_ITEM_CODE IN VARCHAR2)
  RETURN NUMBER IS
  V_PROCESS_MONEY NUMBER(15, 2);
BEGIN
  SELECT NVL(SUM(T.V_PROCESS_MONEY), 0) INTO V_PROCESS_MONEY
    FROM (SELECT DISTINCT RC.REF_CODE, RC.MONEY AS V_PROCESS_MONEY
    FROM RAT_COMPOSITIVE_DETAIL RC JOIN RAT_URATION RU ON RC.RAT_CODE = RU.RATION_CODE AND RC.REF_CODE = RU.BILLNO
    AND INSTR(RU.COMP_ITEM_CODE, RC.ITEM_CODE, 1, 1) >= 1 WHERE RC.REF_TYPE = '6' AND RC.RAT_CODE = V_RATION_CODE
    AND RU.RATION_CODE = V_RATION_CODE AND INSTR(V_ITEM_CODE, RC.ITEM_CODE, 1, 1) >= 1 AND RU.STATUS IN ('1', '2')
    AND RC.COMP_CODE IN (SELECT RBD.COMPCODE FROM RAT_BKRATION_DIS RBD WHERE RBD.RAT_CODE = V_RATION_CODE AND RBD.DISTRIBUTE_WAY = '2') GROUP BY RC.ITEM_CODE, RC.REF_CODE, RC.MONEY) T;
  RETURN V_PROCESS_MONEY;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RETURN 0;
END;
/