--修改日期：2012-08-03
--修改人：  费滔
--修改内容: 将BIS_BIF_RULE的自增长取消，种子表TB_GENERATOR中BIS_BIF_RULE_ID对应的value与数据表BIS_BIF_RULE)对应
--修改原因: BIS_BIF_RULE设置成自增长时，不能从种子表获取值作为主键插入
delete from TB_GENERATOR where gen_name='BIS_BIF_RULE_ID'
go
insert into TB_GENERATOR(GEN_NAME,GEN_VALUE) select 'BIS_BIF_RULE_ID',(select MAX(ID)+1 from BIS_BIF_RULE)
go
CREATE TABLE dbo.Tmp_BIS_BIF_RULE
	(
	ID int NOT NULL,
	BIF_CODE char(4) NOT NULL,
	BIF_NAME varchar(30) NOT NULL,
	PAYER_NAME int NULL,
	PAYER_ACC int NULL,
	PAYER_BANK int NULL,
	PAYEE_NAME int NULL,
	PAYEE_ACC int NULL,
	PAYEE_BANK int NULL,
	PURPOSE int NULL,
	ADD_WORD int NULL
	)
GO
IF EXISTS(SELECT * FROM dbo.BIS_BIF_RULE)
	 EXEC('INSERT INTO dbo.Tmp_BIS_BIF_RULE (ID, BIF_CODE, BIF_NAME, PAYER_NAME, PAYER_ACC, PAYER_BANK, PAYEE_NAME, PAYEE_ACC, PAYEE_BANK, PURPOSE, ADD_WORD)
		SELECT ID, BIF_CODE, BIF_NAME, PAYER_NAME, PAYER_ACC, PAYER_BANK, PAYEE_NAME, PAYEE_ACC, PAYEE_BANK, PURPOSE, ADD_WORD FROM dbo.BIS_BIF_RULE WITH (HOLDLOCK TABLOCKX)')
GO
DROP TABLE dbo.BIS_BIF_RULE
GO
EXECUTE sp_rename N'dbo.Tmp_BIS_BIF_RULE', N'BIS_BIF_RULE', 'OBJECT' 
GO
ALTER TABLE dbo.BIS_BIF_RULE ADD CONSTRAINT
	PK_BIS_BIF_RULE PRIMARY KEY CLUSTERED (ID) 
GO
ALTER TABLE dbo.BIS_BIF_RULE ADD CONSTRAINT
	UQ_BIS_BIF_RULE UNIQUE NONCLUSTERED (BIF_CODE) 
GO