--修改日期：20120918
--修改人：叶爱军
--需求编号：XD-JD03-027 系统功能-增加借款单位
--参数设置：
ALTER TABLE CMS_LOAN_INFO ADD BORROW_CORP_ID VARCHAR2(4);
UPDATE CMS_LOAN_INFO SET BORROW_CORP_ID = NET_CODE;
COMMIT;

--修改日期：20120918
--修改人：叶爱军
--需求编号：XD-JD03-027 系统功能-增加付息方式
--参数设置：
ALTER TABLE CMS_PROVIDE_LOAN_INFO ADD PAY_INTEREST VARCHAR2(3);
UPDATE CMS_PROVIDE_LOAN_INFO SET PAY_INTEREST = '001';
COMMIT;