--修改日期：20121031
--修改人：叶爱军
--需求编号：SX-AKS1-002
--修改内容：币别汇率
CREATE OR REPLACE VIEW V_FC_EXCRATE_ADJUST AS
SELECT BC.CUR_CODE,
       BC.CUR_NAME,
       (CASE WHEN FEA.NEW_EXCHANGE_RATE IS NULL THEN BC.CUR_EXRATE ELSE FEA.NEW_EXCHANGE_RATE END) AS NEW_EXCHANGE_RATE,
       (CASE WHEN FEA.ADJUST_TIME IS NULL THEN '1900-01-01' ELSE TO_CHAR(FEA.ADJUST_TIME, 'YYYY-MM-DD') END) AS ADJUST_TIME
  FROM BT_CURRENCY BC
  LEFT JOIN FC_EXCRATE_ADJUST FEA ON BC.CUR_CODE = FEA.CUR_CODE AND FEA.STATUS = '95';
/

--修改日期：20130109
--修改人：张培
--Bug编号：user00035383
--修改内容：添加占用综合品种选择单项及组合项编码字段
DECLARE
  V_CNT_0 INTEGER;
  V_CNT_1 INTEGER;
  V_CNT_2 INTEGER;
  V_CNT_3 INTEGER;
  V_CNT_4 INTEGER;
BEGIN
--授信占用
  SELECT COUNT(1) INTO V_CNT_0 FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'RAT_URATION' AND COLUMN_NAME = 'COMP_ITEM_CODE';
--承兑自开  
  SELECT COUNT(1) INTO V_CNT_1 FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'AB_EMIT' AND COLUMN_NAME = 'COMP_ITEM_CODE';
--信用证  
  SELECT COUNT(1) INTO V_CNT_2 FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'LC_ENROL' AND COLUMN_NAME = 'COMP_ITEM_CODE';
--信贷借款
  SELECT COUNT(1) INTO V_CNT_3 FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'CMS_PROVIDE_LOAN_INFO' AND COLUMN_NAME = 'COMP_ITEM_CODE';
--授信申请
  SELECT COUNT(1) INTO V_CNT_4 FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'RAT_URATION_APPLY' AND COLUMN_NAME = 'COMP_ITEM_CODE';
  
  IF V_CNT_0 = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RAT_URATION ADD COMP_ITEM_CODE VARCHAR2(500)';
  END IF;
  IF V_CNT_1 = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE AB_EMIT ADD COMP_ITEM_CODE VARCHAR2(500)';
  END IF;
  IF V_CNT_2 = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE LC_ENROL ADD COMP_ITEM_CODE VARCHAR2(500)';
  END IF;
  IF V_CNT_3 = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE CMS_PROVIDE_LOAN_INFO ADD COMP_ITEM_CODE VARCHAR2(500)';
  END IF;
  IF V_CNT_4 = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RAT_URATION_APPLY ADD COMP_ITEM_CODE VARCHAR2(500)';
  END IF;
  COMMIT;
END;
/

ALTER TABLE RAT_BKRATION_DETAIL MODIFY INTERESTRATE NUMBER(15, 6);
COMMIT;
/

--修改日期：20130121
--修改人：叶爱军
--需求编号：SX-AKS1-002
--修改内容：综合单项的共享额度
CREATE OR REPLACE FUNCTION FUN_GET_PROCESS_MONEY_SIN(V_RATION_CODE IN VARCHAR2, V_ITEM_CODE IN VARCHAR2)
  RETURN NUMBER IS
  V_PROCESS_MONEY NUMBER(15, 2);
BEGIN
  SELECT NVL(SUM(T.V_PROCESS_MONEY), 0) INTO V_PROCESS_MONEY
    FROM (SELECT (CASE WHEN LENGTH(RC.ITEM_CODE) = 9 THEN RC.MONEY ELSE 0 END) AS V_PROCESS_MONEY
    FROM RAT_COMPOSITIVE_DETAIL RC JOIN RAT_URATION RU ON RC.RAT_CODE = RU.RATION_CODE AND RC.REF_CODE = RU.BILLNO
    AND INSTR(RU.COMP_ITEM_CODE, RC.ITEM_CODE, 1, 1) >= 1 WHERE RC.REF_TYPE = '6' AND RC.RAT_CODE = V_RATION_CODE
    AND RU.RATION_CODE = V_RATION_CODE AND INSTR(V_ITEM_CODE, RC.ITEM_CODE, 1, 1) >= 1 AND RU.STATUS IN ('1', '2')
    AND RC.COMP_CODE IN (SELECT RBD.COMPCODE FROM RAT_BKRATION_DIS RBD WHERE RBD.RAT_CODE = V_RATION_CODE AND RBD.DISTRIBUTE_WAY = '2') GROUP BY RC.ITEM_CODE, RC.REF_CODE, RC.MONEY) T;
  RETURN V_PROCESS_MONEY;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RETURN 0;
END;
/

--修改日期：20130121
--修改人：叶爱军
--需求编号：SX-AKS1-002
--修改内容：综合组合项的共享额度
CREATE OR REPLACE FUNCTION FUN_GET_PROCESS_MONEY_COM(V_RATION_CODE IN VARCHAR2, V_ITEM_CODE IN VARCHAR2)
  RETURN NUMBER IS
  V_PROCESS_MONEY NUMBER(15, 2);
BEGIN
  SELECT NVL(SUM(T.V_PROCESS_MONEY), 0) INTO V_PROCESS_MONEY
    FROM (SELECT DISTINCT RC.REF_CODE, RC.MONEY AS V_PROCESS_MONEY
    FROM RAT_COMPOSITIVE_DETAIL RC JOIN RAT_URATION RU ON RC.RAT_CODE = RU.RATION_CODE AND RC.REF_CODE = RU.BILLNO
    AND INSTR(RU.COMP_ITEM_CODE, RC.ITEM_CODE, 1, 1) >= 1 WHERE RC.REF_TYPE = '6' AND RC.RAT_CODE = V_RATION_CODE
    AND RU.RATION_CODE = V_RATION_CODE AND INSTR(V_ITEM_CODE, RC.ITEM_CODE, 1, 1) >= 1 AND RU.STATUS IN ('1', '2')
    AND RC.COMP_CODE IN (SELECT RBD.COMPCODE FROM RAT_BKRATION_DIS RBD WHERE RBD.RAT_CODE = V_RATION_CODE AND RBD.DISTRIBUTE_WAY = '2') GROUP BY RC.ITEM_CODE, RC.REF_CODE, RC.MONEY) T;
  RETURN V_PROCESS_MONEY;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RETURN 0;
END;
/