--修改时间2012-12-25
--修改人 曾炼平
--修改内容 增加 保证金比率字段

DECLARE
  VN_COUNT     NUMBER;
  VC_STR       VARCHAR2(1000);
BEGIN
  SELECT COUNT(*) 
    INTO VN_COUNT
    FROM USER_TAB_COLUMNS 
   WHERE TABLE_NAME = 'LC_ENROL' AND COLUMN_NAME = 'DEPOSIT_RATIO';
  IF VN_COUNT < 1 THEN
    VC_STR := 'ALTER TABLE LC_ENROL ADD (DEPOSIT_RATIO number(10,2))';
    EXECUTE IMMEDIATE VC_STR;
  END IF;
END;
/
