--修改日期：2012.12.4
--修改人：李程
--修改内容：修改用途表视图，以前的视图在某些数据库上会出现数据重复。
--修改原因：VP单：[VP7222]广州建筑-信贷管理用途维护问题。


CREATE OR REPLACE VIEW V_BT_PURPOSE AS
(
  SELECT A.CORP_ID, A.PURPOSE, A.PURPOSE_CODE, B.NIS_ID, C.CMS_PL_ID, D.LC_ID
  FROM (
        SELECT CORP_ID, PURPOSE, PURPOSE_CODE FROM NIS_PURPOSE
        UNION
        SELECT CORP_ID, PURPOSE, PURPOSE_CODE FROM CMS_PL_PURPOSE
        UNION
        SELECT CORP_ID, PURPOSE, PURPOSE_CODE FROM LC_PURPOSE) A
  LEFT JOIN (SELECT ID NIS_ID, PURPOSE_CODE FROM NIS_PURPOSE) B ON A.PURPOSE_CODE = B.PURPOSE_CODE
  LEFT JOIN (SELECT ID CMS_PL_ID, PURPOSE_CODE FROM CMS_PL_PURPOSE) C ON A.PURPOSE_CODE = C.PURPOSE_CODE
  LEFT JOIN (SELECT ID LC_ID, PURPOSE_CODE FROM LC_PURPOSE) D ON A.PURPOSE_CODE = D.PURPOSE_CODE
);
