--修改日期：2012.12.15
--修改人：刘之三
--修改内容：自动扫描预警
--修改原因：自动扫描预警


--净流入透支
IF NOT EXISTS(SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('BT_WARNING_OVERFLOW') AND NAME='STRATEGY_DETAIL_STR')  
ALTER TABLE BT_WARNING_OVERFLOW ADD STRATEGY_DETAIL_STR VARCHAR(40); 
GO

IF NOT EXISTS(SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('BT_WARNING_OVERFLOW') AND NAME='BUSINESS_DATE')  
ALTER TABLE BT_WARNING_OVERFLOW ADD BUSINESS_DATE DATETIME; 
GO

IF NOT EXISTS(SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('BT_WARNING_OVERFLOW') AND NAME='WARNING_REASON')  
ALTER TABLE BT_WARNING_OVERFLOW ADD WARNING_REASON VARCHAR(400); 
GO

IF NOT EXISTS(SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('BT_WARNING_OVERFLOW') AND NAME='BANK_ACC')  
ALTER TABLE BT_WARNING_OVERFLOW ADD BANK_ACC VARCHAR(50); 
GO

IF NOT EXISTS(SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('BT_WARNING_OVERFLOW') AND NAME='STRAGE_DETAIL_ID')  
ALTER TABLE BT_WARNING_OVERFLOW ADD STRAGE_DETAIL_ID numeric(10); 
GO

IF NOT EXISTS(SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('BT_WARNING_OVERFLOW') AND NAME='SCAN_DATE_START')  
ALTER TABLE BT_WARNING_OVERFLOW ADD SCAN_DATE_START DATETIME; 
GO

IF NOT EXISTS(SELECT * FROM SYSCOLUMNS WHERE ID=OBJECT_ID('BT_WARNING_OVERFLOW') AND NAME='BANK_TYPE')  
ALTER TABLE BT_WARNING_OVERFLOW ADD BANK_TYPE VARCHAR(10); 
GO