


--修改人:蒲勇军
--修改时间:2012-09-19
--离线账户授权表
create table BT_UNDERLINE_ACC_GRANT
(
  GRANT_ID               NUMBER(10) PRIMARY KEY,
  USER_CODE              VARCHAR2(8) not null,
  bank_acc               VARCHAR2(50) not null,
  GRANT_DTL              CHAR(1),
  GRANT_BAL              CHAR(1),
  GRANT_EXG              CHAR(1),
  GRANT_USER             CHAR(8),
  STATUS                 CHAR(1)
);

COMMENT ON COLUMN BT_UNDERLINE_ACC_GRANT.GRANT_ID IS 'ID';
COMMENT ON COLUMN BT_UNDERLINE_ACC_GRANT.USER_CODE IS '用户';
COMMENT ON COLUMN BT_UNDERLINE_ACC_GRANT.bank_acc IS '帐号';
COMMENT ON COLUMN BT_UNDERLINE_ACC_GRANT.GRANT_DTL IS '查询明细';
COMMENT ON COLUMN BT_UNDERLINE_ACC_GRANT.GRANT_BAL IS '查询历史余额';
COMMENT ON COLUMN BT_UNDERLINE_ACC_GRANT.GRANT_EXG IS '交易';
COMMENT ON COLUMN BT_UNDERLINE_ACC_GRANT.GRANT_USER IS '授权人';
COMMENT ON COLUMN BT_UNDERLINE_ACC_GRANT.STATUS IS '状态 1有效';


