--修改人:陈春燕
--修改时间:2012-11-2
--修改内容:ZY-CD-01_ORCL.sql 更改ab_operation，测试缺此字段
IF NOT EXISTS(SELECT * 
FROM SYSCOLUMNS 
WHERE ID=OBJECT_ID('AB_OPERATION') AND NAME='RATMODEL')  
ALTER TABLE AB_OPERATION ADD RATMODEL VARCHAR(10)
GO
