CREATE VIEW V_CMS_BILLING AS
SELECT CLB.CLB_ID,
       CLB.CLB_NO,
       CLB.CLB_LOAN_CORP_ID AS BL_CORP_ID,
       BL.CORP_CODE AS BL_CORP_CODE,
       BL.CORP_NAME AS BL_CORP_NAME,
       CLB.CLB_BORROW_CORP_ID AS BB_CORP_ID,
       BB.CORP_CODE AS BB_CORP_CODE,
       BB.CORP_NAME AS BB_CORP_NAME,
       CONVERT(MONEY,ROUND(CLB.CLB_LOAN_MONEY, 2), 120) AS CLB_LOAN_MONEY,
       CONVERT(MONEY,ROUND(SUM(CLA.CLA_MONEY), 2), 120) AS CLA_MONEY,
       CONVERT(MONEY,ROUND(CB.CLB_BALANCE, 2), 120) AS CLB_BALANCE,
       CONVERT(MONEY,ROUND(CLB.CLB_FIXED_RATE, 6), 120) AS CLB_FIXED_RATE,
       CONVERT(MONEY,ROUND(CLB.CLB_AGREEMENT_RATE, 6), 120) AS CLB_AGREEMENT_RATE,
       CLB.CLB_START_DATE,
       CLB.CLB_END_DATE,
       CLB.CLB_LAST_BILLING_DATE
       --–ﬁ∏ƒ»À£∫¡ı”¬
       /*(select datediff(dd,CLB_END_DATE,CLB_START_DATE) from CMS_LOAN_BILL where CLB_NO=CLB.CLB_NO) AS COMP_RATE_DAYS ,
         CONVERT(MONEY,ROUND(CLB.CLB_FIXED_RATE/360, 6), 120) AS DAY_RATE,
         CONVERT(MONEY,ROUND(CLB.CLB_AGREEMENT_RATE/360, 6), 120) AS DAY_RATE_OF_AGREEMENT,
         (CONVERT(MONEY,ROUND(CB.CLB_BALANCE, 2), 120))*(select datediff(dd,CLB_END_DATE,CLB_START_DATE) from CMS_LOAN_BILL where CLB_NO=CLB.CLB_NO) AS JI_SHU,
         CONVERT(MONEY,ROUND(CLB.CLB_FIXED_RATE/360, 6), 120)*(CONVERT(MONEY,ROUND(CB.CLB_BALANCE, 2), 120))*(select datediff(dd,CLB_END_DATE,CLB_START_DATE) from CMS_LOAN_BILL where CLB_NO=CLB.CLB_NO) AS RATE_S,
         CONVERT(MONEY,ROUND(CLB.CLB_AGREEMENT_RATE/360, 6), 120)*(CONVERT(MONEY,ROUND(CB.CLB_BALANCE, 2), 120))*(select datediff(dd,CLB_END_DATE,CLB_START_DATE) from CMS_LOAN_BILL where CLB_NO=CLB.CLB_NO),2) AS RATE_SI
       */
FROM CMS_LOAN_BILL CLB
LEFT JOIN CMS_LOAN_ABATE CLA ON CLB.CLB_ID = CLA.CLB_ID
INNER JOIN BT_CORP BL ON CLB.CLB_LOAN_CORP_ID = BL.ID
INNER JOIN BT_CORP BB ON CLB.CLB_BORROW_CORP_ID = BB.ID
WHERE CLB.CLB_STATUS=95
GROUP BY CLB.CLB_NO,CLB.CLB_LOAN_CORP_ID,BL.CORP_CODE,
        BL.CORP_NAME,CLB.CLB_BORROW_CORP_ID,BB.CORP_CODE,BB.CORP_NAME,
        CLB.CLB_LOAN_MONEY,CLB.CLB_BALANCE,CLB.CLB_FIXED_RATE,CLB.CLB_LAST_BILLING_DATE,
        CLB.CLB_AGREEMENT_RATE,CLB.CLB_START_DATE,CLB.CLB_END_DATE,CLB.CLB_ID
GO
