--修改人:陈春燕
--修改时间:2012-12-25
--修改内容: AB_EMIT 新增数据来源（ORIGIN）和同步时间(SYNCHRONIZATION_TIME)；添加AB_EMIT_TEMP表。存储删除的自开票据;
-------- add column ORIGIN
DECLARE
  VN_COUNT     NUMBER;
  VC_STR        VARCHAR2(1000);
BEGIN 
  SELECT COUNT(*) 
    INTO VN_COUNT
    FROM USER_TAB_COLUMNS 
   WHERE TABLE_NAME = 'AB_EMIT' AND COLUMN_NAME = 'ORIGIN';
  IF VN_COUNT < 1 THEN
    VC_STR := ' ALTER TABLE AB_EMIT ADD ORIGIN VARCHAR2(20)';
    EXECUTE IMMEDIATE VC_STR;
  END IF;
END;
/
-------- add column 
DECLARE
  VN_COUNT     NUMBER;
  VC_STR        VARCHAR2(1000);
BEGIN
  SELECT COUNT(*) 
    INTO VN_COUNT
    FROM USER_TAB_COLUMNS 
   WHERE TABLE_NAME = 'AB_EMIT' AND COLUMN_NAME = 'SYNCHRONIZATION_TIME';
  IF VN_COUNT < 1 THEN
    VC_STR := ' ALTER TABLE AB_EMIT ADD SYNCHRONIZATION_TIME date';
    EXECUTE IMMEDIATE VC_STR;
  END IF;
END;
/
------------add AB_EMIT_TEMP table
DECLARE
  VC_STR           VARCHAR2(2000);
  VN_COUNT         NUMBER;
BEGIN 
  SELECT COUNT(*)
    INTO VN_COUNT
    FROM USER_TABLES
   WHERE TABLE_NAME = 'AB_EMIT_TEMP';
  IF VN_COUNT < 1 THEN
    VC_STR := 'CREATE TABLE AB_EMIT_TEMP 
     (ID NUMBER(28,0) NOT NULL ENABLE, 
  ACCBOOK_ID CHAR(1) NOT NULL ENABLE, 
  SUBJECT CHAR(3) NOT NULL ENABLE, 
  CODE VARCHAR2(20), 
  PACT_NO VARCHAR2(50), 
  CORP_ID NUMBER NOT NULL ENABLE, 
  CORP_NAME VARCHAR2(200) NOT NULL ENABLE, 
  DEPT_CODE CHAR(4), 
  RATION_TYPE CHAR(1), 
  RATION_CODE VARCHAR2(20), 
  RECEIVER VARCHAR2(200) NOT NULL ENABLE, 
  BILL_TYPE VARCHAR2(20) NOT NULL ENABLE, 
  MONEY NUMBER(18,2) NOT NULL ENABLE, 
  APPLY_DATE DATE, 
  ISSUE_DATE DATE NOT NULL ENABLE, 
  MATURITY_DATE DATE NOT NULL ENABLE, 
  PAYER VARCHAR2(200) NOT NULL ENABLE, 
  ACCEPTOR VARCHAR2(200) NOT NULL ENABLE, 
  RESUME VARCHAR2(200), 
  POUNDAGE NUMBER(18,2), 
  BAIL NUMBER(18,2), 
  CAUTIONER VARCHAR2(200), 
  GAGE VARCHAR2(200), 
  GAGE_VALUE NUMBER(18,2), 
  STATE NUMBER NOT NULL ENABLE, 
  IS_HELP NUMBER NOT NULL ENABLE, 
  OPERATOR_CODE VARCHAR2(8) NOT NULL ENABLE, 
  ENTER_DATE DATE NOT NULL ENABLE, 
  IS_APPEND NUMBER NOT NULL ENABLE, 
  USE_TYPE NUMBER NOT NULL ENABLE, 
  FIVE_RANK NUMBER NOT NULL ENABLE, 
  ITEM_CODE VARCHAR2(20), 
  DISCOUNT_DATE DATE, 
  DISCOUNT_DAYS NUMBER(*,0), 
  DISCOUNT_INTEREST_RATE NUMBER, 
  DISCOUNT_INTEREST NUMBER, 
  RECEIVER_BANK VARCHAR2(100), 
  RECEIVER_BANK_ACC VARCHAR2(30), 
  REMARK VARCHAR2(1000), 
  IS_SELF_BILLING CHAR(1) DEFAULT 1, 
  DATA_SOURCE CHAR(3), 
  UPDATE_DATE DATE, 
  BAIL_MATURITY_DATE DATE, 
  BAIL_INTEREST_RATE NUMBER(6,2), 
  BAIL_PROPORTION NUMBER(5,4), 
  OPEN_FLAG CHAR(1), 
  BANK_ACC VARCHAR2(30), 
  BANK_NAME VARCHAR2(140), 
	BANK_CODE CHAR(4), 
	MORPLE_CODE VARCHAR2(50), 
	GUA_TYPE VARCHAR2(2), 
	VENDOR_NUM VARCHAR2(31), 
	SERVICE_CHARGE NUMBER(18,2), 
	PRACTICE_TYPE VARCHAR2(30), 
	PAYMENT_CORP VARCHAR2(200), 
	REMIT NUMBER(18,2), 
	REPAYMENT NUMBER(18,2), 
	INCREASE_PROFIT NUMBER(18,2),
  ORIGIN VARCHAR2(20),
  SYNCHRONIZATION_TIME DATE,  
  CONSTRAINT PK_AB_EMIT_TEMP PRIMARY KEY (ID)
  )';
    EXECUTE IMMEDIATE VC_STR;
  END IF;
END;
/
------ modify lc_enrol
 ALTER TABLE lc_enrol  rename column reserve3 to origin;
 ALTER TABLE lc_enrol  MODIFY origin VARCHAR2(20);
 ALTER TABLE lc_enrol  rename column reserve2 to SYNCHRONIZATION_TIME;
 ALTER TABLE lc_enrol  MODIFY SYNCHRONIZATION_TIME DATE;

 

 



