--修改人：胡双
--修改日期：2012-12-25
--修改内容：VP7396，添加业务类型：承兑汇票

DECLARE
  @VN_COUNT INT;
BEGIN
  SELECT @VN_COUNT=COUNT(*)  FROM ERP_VOUCHER_TYPE WHERE ID = 4;
  IF (@VN_COUNT < 1)
  BEGIN
    INSERT INTO ERP_VOUCHER_TYPE
      (ID, VOUCHER_TYPE_CODE, VOUCHER_TYPE_NAME)
    VALUES
      (4, '04', '承兑汇票');
  END;
END;