--修改人:陈春燕
--修改时间:2012-12-25
--修改内容: AB_EMIT_TEMP。存储删除的自开票据
-----
IF NOT EXISTS(SELECT * 
FROM SYSCOLUMNS 
WHERE ID=OBJECT_ID('AB_EMIT') AND NAME='ORIGIN')  
ALTER TABLE AB_EMIT ADD ORIGIN VARCHAR(20)
GO


IF NOT EXISTS(SELECT * 
FROM SYSCOLUMNS 
WHERE ID=OBJECT_ID('AB_EMIT') AND NAME='SYNCHRONIZATION_TIME')  
ALTER TABLE AB_EMIT ADD SYNCHRONIZATION_TIME datetime
GO

 
IF NOT EXISTS (SELECT 1
                 FROM  SYSOBJECTS
                WHERE  ID = OBJECT_ID('AB_EMIT_TEMP')
                  AND   TYPE = 'U')
CREATE TABLE AB_EMIT_TEMP 
     (ID NUMERIC(28,0) NOT NULL, 
  ACCBOOK_ID CHAR(1) NOT NULL, 
  SUBJECT CHAR(3) NOT NULL, 
  CODE VARCHAR(20), 
  PACT_NO VARCHAR(50), 
  CORP_ID NUMERIC NOT NULL, 
  CORP_NAME VARCHAR(200) NOT NULL, 
  DEPT_CODE CHAR(4), 
  RATION_TYPE CHAR(1), 
  RATION_CODE VARCHAR(20), 
  RECEIVER VARCHAR(200) NOT NULL, 
  BILL_TYPE VARCHAR(20) NOT NULL, 
  MONEY NUMERIC(18,2) NOT NULL, 
  APPLY_DATE datetime, 
  ISSUE_DATE datetime NOT NULL, 
  MATURITY_DATE datetime NOT NULL, 
  PAYER VARCHAR(200) NOT NULL, 
  ACCEPTOR VARCHAR(200) NOT NULL, 
  RESUME VARCHAR(200), 
  POUNDAGE NUMERIC(18,2), 
  BAIL NUMERIC(18,2), 
  CAUTIONER VARCHAR(200), 
  GAGE VARCHAR(200), 
  GAGE_VALUE NUMERIC(18,2), 
  STATE NUMERIC NOT NULL, 
  IS_HELP NUMERIC NOT NULL, 
  OPERATOR_CODE VARCHAR(8) NOT NULL, 
  ENTER_DATE datetime NOT NULL, 
  IS_APPEND NUMERIC NOT NULL, 
  USE_TYPE NUMERIC NOT NULL, 
  FIVE_RANK NUMERIC NOT NULL, 
  ITEM_CODE VARCHAR(20), 
  DISCOUNT_DATE datetime, 
  DISCOUNT_DAYS NUMERIC(28,0), 
  DISCOUNT_INTEREST_RATE NUMERIC, 
  DISCOUNT_INTEREST NUMERIC, 
  RECEIVER_BANK VARCHAR(100), 
  RECEIVER_BANK_ACC VARCHAR(30), 
  REMARK VARCHAR(1000), 
  IS_SELF_BILLING CHAR(1) DEFAULT 1, 
  DATA_SOURCE CHAR(3), 
  UPDATE_DATE datetime, 
  BAIL_MATURITY_DATE datetime, 
  BAIL_INTEREST_RATE NUMERIC(6,2), 
  BAIL_PROPORTION NUMERIC(5,4), 
  OPEN_FLAG CHAR(1), 
  BANK_ACC VARCHAR(30), 
  BANK_NAME VARCHAR(140), 
  BANK_CODE CHAR(4), 
  MORPLE_CODE VARCHAR(50), 
  GUA_TYPE VARCHAR(2), 
  VENDOR_NUM VARCHAR(31), 
  SERVICE_CHARGE NUMERIC(18,2), 
  PRACTICE_TYPE VARCHAR(30), 
  PAYMENT_CORP VARCHAR(200), 
  REMIT NUMERIC(18,2), 
  REPAYMENT NUMERIC(18,2), 
  INCREASE_PROFIT NUMERIC(18,2),
  ORIGIN VARCHAR(20),
  SYNCHRONIZATION_TIME datetime ,
  CONSTRAINT PK_AB_EMIT_TEMP PRIMARY KEY (ID)
  )
 go

------ modify lc_enrol
EXEC sp_rename 'lc_enrol.[reserve3]','origin','COLUMN' 
go
 
ALTER TABLE LC_ENROL ALTER COLUMN origin VARCHAR(20)
GO

EXEC sp_rename 'lc_enrol.reserve2','SYNCHRONIZATION_TIME','COLUMN' 
go

ALTER TABLE LC_ENROL ALTER COLUMN SYNCHRONIZATION_TIME DATETIME
go
 

 



