--修改人:陈春燕
--修改时间:2012-12-24
--修改内容: 添加AB_RECEIVE_TEMP表。存储删除的库存票据
 
IF NOT EXISTS (SELECT 1
                 FROM  SYSOBJECTS
                WHERE  ID = OBJECT_ID('AB_RECEIVE_TEMP')
                  AND   TYPE = 'U')
CREATE TABLE AB_RECEIVE_TEMP 
  (ID NUMERIC(28,0) NOT NULL, 
  ACCBOOK_ID CHAR(1) NOT NULL , 
  SUBJECT CHAR(3) NOT NULL , 
  CORP_ID NUMBER NOT NULL , 
  CORP_NAME VARCHAR(200) NOT NULL , 
  DEPT_CODE CHAR(4), 
  CODE VARCHAR(20) NOT NULL ENABLE, 
  CORP_CODE VARCHAR(15), 
  BILL_TYPE VARCHAR(20) NOT NULL , 
  IS_BONDED NUMERIC NOT NULL , 
  MONEY NUMBER(18,2) NOT NULL , 
  ISSUE_DATE datetime NOT NULL , 
  MATURITY_DATE datetime NOT NULL , 
  PAYER VARCHAR(200) NOT NULL , 
  ACCEPTOR VARCHAR(200) NOT NULL , 
  RESUME VARCHAR(200), 
  SIGN_BANK VARCHAR(20), 
  PRE_HAND VARCHAR(200), 
  NEXT_HAND VARCHAR(200), 
  STATE NUMERIC NOT NULL , 
  IS_TRUE NUMERIC NOT NULL , 
  IS_HELP NUMERIC NOT NULL , 
  OPERATOR_CODE VARCHAR(8), 
  ENTER_DATE datetime NOT NULL , 
  TALLY_FLAG NUMERIC DEFAULT 0 NOT NULL , 
  PAYEE_CORP_NAME VARCHAR(80), 
  PAYEE_BANK_ACC VARCHAR(30), 
  PAYEE_BANK_NAME VARCHAR(140), 
  IS_PAY NUMERIC, 
  PAYER_ACC VARCHAR(100), 
  RECEIPT_DATE datetime, 
  DISCOUNT_TO_NET CHAR(1), 
  DISCOUNT_TO_MIDDLENET CHAR(1) DEFAULT 0, 
  IS_LOCK CHAR(1), 
  MORPLE_CODE VARCHAR(50), 
  VENDOR_NUM VARCHAR(31), 
  CONSTRAINT PK_AB_RECEIVE_TEMP PRIMARY KEY (ID)
   )
 go
----creat index on AB_RECEIVE_TEMP
 CREATE INDEX IDX_AB_RECEIVE_TEMP_01 ON AB_RECEIVE_TEMP (ACCBOOK_ID, CORP_ID, SUBJECT, STATE)  
 CREATE INDEX IDX_AB_RECEIVE_TEMP_02 ON AB_RECEIVE_TEMP (CORP_ID, TALLY_FLAG, STATE)
  go

 

 



