--修改日期：20130107
--修改人：祁继鸿
--修改内容：vp7451 增加ERP转移过来的历史金额
--修改内容：ERP_HIS_MONEY 增加字段 ERP历史金额
--参数设置：
DECLARE
  ERP_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO ERP_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'NIS_BILLHEAD' AND COLUMN_NAME = 'ERP_HIS_MONEY';
  IF ERP_COUNT = 0 THEN
     EXECUTE IMMEDIATE 'ALTER TABLE NIS_BILLHEAD ADD ERP_HIS_MONEY NUMBER(15,2)';
  END IF;
END;
/
--修改付款账号字段可以为空
DECLARE
  ERP_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO ERP_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'NIS_BILLHEAD' AND COLUMN_NAME='PAYER_ACC' AND NULLABLE='N';
  IF ERP_COUNT = 0 THEN
     EXECUTE IMMEDIATE 'ALTER TABLE nis_billhead modify payer_acc NULL;';
  END IF;
END;
/
--修改付款单操作员字段可以为空
DECLARE
  ERP_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO ERP_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'NIS_BILLHEAD' AND COLUMN_NAME='OP' AND NULLABLE='N';
  IF ERP_COUNT = 0 THEN
     EXECUTE IMMEDIATE 'ALTER TABLE nis_billhead modify op NULL;';
  END IF;
END;
/

--修改日期：20130107
--修改人：祁继鸿
--修改内容：vp7451 增加自开票据 与 付款单相关联的bill_no
--修改内容 AB_EMIT 增加字段 付款单编号BILL_NO
--参数设置：
DECLARE
  ERP_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO ERP_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'AB_EMIT' AND COLUMN_NAME = 'BILL_NO';
  IF ERP_COUNT = 0 THEN
     EXECUTE IMMEDIATE 'ALTER TABLE AB_EMIT ADD BILL_NO VARCHAR2(20)';
  END IF;
END;
/
--修改日期：20130107
--修改人：祁继鸿
--修改内容：vp7451 增加库存票据 与 付款单相关联的bill_no
--修改内容  AB_RECEIVE 增加字段 付款单编号BILL_NO
--参数设置：
DECLARE
  ERP_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO ERP_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'AB_RECEIVE' AND COLUMN_NAME = 'BILL_NO';
  IF ERP_COUNT = 0 THEN
     EXECUTE IMMEDIATE 'ALTER TABLE AB_RECEIVE ADD BILL_NO VARCHAR2(20)';
  END IF;
END;
/

--修改字段长度
alter table nis_billhead modify billnumber varchar2(500);

