--修改日期：20130108
--修改人：李德成
--修改内容：背书增加后手单位编码
--修改内容  AB_RECEIVE 增加字段 付款单编号NEXT_VENDOR_NUM
--参数设置：
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'NEXT_VENDOR_NUM' AND LTRIM(B.NAME) = 'AB_RECEIVE')
  ALTER TABLE AB_RECEIVE ADD NEXT_VENDOR_NUM varchar(31);
GO

--修改日期：20130108
--修改人：李德成
--修改内容：传输方式：SAP/OMS/NC
--修改内容  ERP_PAY_INFO 增加字段 TRANS_TYPE
--参数设置：
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'TRANS_TYPE' AND LTRIM(B.NAME) = 'ERP_PAY_INFO')
  ALTER TABLE ERP_PAY_INFO ADD TRANS_TYPE varchar(10);
GO

--修改日期：20130108
--修改人：李德成
--修改内容：传输状态：0成功，1失败
--修改内容  ERP_PAY_INFO 增加字段 TRANS_STATUS
--参数设置：
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'TRANS_STATUS' AND LTRIM(B.NAME) = 'ERP_PAY_INFO')
  ALTER TABLE ERP_PAY_INFO ADD TRANS_STATUS CHAR(1);
GO
--修改日期：20130108
--修改人：李德成
--修改内容：erp凭证号
--修改内容  ERP_PAY_INFO 增加字段 ERP_VOUCHER_NO
--参数设置：
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'ERP_VOUCHER_NO' AND LTRIM(B.NAME) = 'ERP_PAY_INFO')
  ALTER TABLE ERP_PAY_INFO ADD ERP_VOUCHER_NO varchar(60);
GO
--修改日期：20130108
--修改人：李德成
--修改内容：传输次数
--修改内容  ERP_PAY_INFO 增加字段 SEND_FREQUENCY 
--参数设置：
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'SEND_FREQUENCY' AND LTRIM(B.NAME) = 'ERP_PAY_INFO')
  alter table ERP_PAY_INFO add SEND_FREQUENCY int default 0;
GO
--修改日期：20130108
--修改人：李德成
--修改内容：返回信息
--修改内容  ERP_PAY_INFO 增加字段 TRANS_MSG
--参数设置：
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'TRANS_MSG' AND LTRIM(B.NAME) = 'ERP_PAY_INFO')
  ALTER TABLE ERP_PAY_INFO ADD TRANS_MSG varchar(500);
GO
--修改日期：20130108
--修改人：李德成
--修改内容：收款行联行号
--修改内容  ERP_PAY_INFO 增加字段 PAYEE_BANK_CODE
--参数设置：
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'PAYEE_BANK_CODE' AND LTRIM(B.NAME) = 'ERP_PAY_INFO')
  alter table ERP_PAY_INFO add PAYEE_BANK_CODE varchar(20);
GO
--修改日期：20130108
--修改人：李德成
--修改内容：付款方式
--修改内容  ERP_PAY_INFO 增加字段 PAYTYPE
--参数设置：
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'PAYTYPE' AND LTRIM(B.NAME) = 'ERP_PAY_INFO')
  alter table ERP_PAY_INFO add PAYTYPE varchar(10);
GO
--修改日期：20130108
--修改人：李德成
--修改内容：业务类型
--修改内容  ERP_PAY_INFO 增加字段 BUSINESSTYPE
--参数设置：
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'BUSINESSTYPE' AND LTRIM(B.NAME) = 'ERP_PAY_INFO')
  alter table ERP_PAY_INFO add BUSINESSTYPE varchar(50);
GO
--修改日期：20130108
--修改人：李德成
--修改内容：背书增加后手单位编码
--修改内容  ERP_PAY_INFO 增加字段TEMPORARYMONEY
--参数设置：暂支款
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'TEMPORARYMONEY' AND LTRIM(B.NAME) = 'ERP_PAY_INFO')
  alter table ERP_PAY_INFO add TEMPORARYMONEY numeric(15,2);
GO
--修改日期：20130108
--修改人：李德成
--修改内容：记账所属成本中心代码
--修改内容  ERP_PAY_INFO 增加字段REC_COST_CENTER_CODE
--参数设置：
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'REC_COST_CENTER_CODE' AND LTRIM(B.NAME) = 'ERP_PAY_INFO')
  alter table ERP_PAY_INFO add REC_COST_CENTER_CODE varchar(20);
GO
--修改日期：20130108
--修改人：李德成
--修改内容：记账所属成本中心名称
--修改内容  ERP_PAY_INFO 增加字段REC_COST_CENTER_NAME
--参数设置：
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'REC_COST_CENTER_NAME' AND LTRIM(B.NAME) = 'ERP_PAY_INFO')
  alter table ERP_PAY_INFO add REC_COST_CENTER_NAME varchar(80);
GO
--修改日期：20130108
--修改人：李德成
--修改内容：供应商编号
--修改内容  ERP_PAY_INFO 增加字段EXTERNAL_CODE
--参数设置：
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'EXTERNAL_CODE' AND LTRIM(B.NAME) = 'ERP_PAY_INFO')
  alter table ERP_PAY_INFO add EXTERNAL_CODE varchar(20);
GO

--修改日期：20130108
--修改人：李德成
--修改内容：传输状态：0成功，1失败
--修改内容  FC_ACCBOOK_BLNED 增加字段TRANS_STATUS
--参数设置：
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'TRANS_STATUS' AND LTRIM(B.NAME) = 'FC_ACCBOOK_BLNED')
  ALTER TABLE FC_ACCBOOK_BLNED ADD TRANS_STATUS CHAR(1);
GO
--修改日期：20130108
--修改人：李德成
--修改内容：erp凭证号
--修改内容  FC_ACCBOOK_BLNED 增加字段ERP_VOUCHER_NO
--参数设置：
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'ERP_VOUCHER_NO' AND LTRIM(B.NAME) = 'FC_ACCBOOK_BLNED')
  alter table FC_ACCBOOK_BLNED add ERP_VOUCHER_NO varchar(30);
GO
--修改日期：20130108
--修改人：李德成
--修改内容：传输次数
--修改内容  FC_ACCBOOK_BLNED 增加字段SEND_FREQUENCY
--参数设置：
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'SEND_FREQUENCY' AND LTRIM(B.NAME) = 'FC_ACCBOOK_BLNED')
  alter table FC_ACCBOOK_BLNED add SEND_FREQUENCY int default 0;
GO
--修改日期：20130108
--修改人：李德成
--修改内容：返回信息
--修改内容  FC_ACCBOOK_BLNED 增加字段TRANS_MSG
--参数设置：
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'TRANS_MSG' AND LTRIM(B.NAME) = 'FC_ACCBOOK_BLNED')
  ALTER TABLE FC_ACCBOOK_BLNED ADD TRANS_MSG varchar(500);
GO

--修改日期：20130108
--修改人：李德成
--修改内容：erp凭证号
--修改内容  BT_NET_CHALK 增加字段ERP_VOUCHER_NO
--参数设置：
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'ERP_VOUCHER_NO' AND LTRIM(B.NAME) = 'BT_NET_CHALK')
  alter table BT_NET_CHALK add ERP_VOUCHER_NO varchar(30);
GO
--修改日期：20130108
--修改人：李德成
--修改内容：传输次数
--修改内容  BT_NET_CHALK 增加字段SEND_FREQUENCY
--参数设置：
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'SEND_FREQUENCY' AND LTRIM(B.NAME) = 'BT_NET_CHALK')
  alter table BT_NET_CHALK add SEND_FREQUENCY int default 0;
GO
--修改日期：20130108
--修改人：李德成
--修改内容：返回信息
--修改内容  BT_NET_CHALK 增加字段TRANS_MSG
--参数设置：
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'TRANS_MSG' AND LTRIM(B.NAME) = 'BT_NET_CHALK')
  ALTER TABLE BT_NET_CHALK ADD TRANS_MSG varchar(500);
GO


--修改日期：20130108
--修改人：吴生火
--修改内容：传输状态：0成功，1失败
--修改内容  FC_ACCBOOK 增加字段TRANS_STATUS
--参数设置：
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'TRANS_STATUS' AND LTRIM(B.NAME) = 'FC_ACCBOOK')
  ALTER TABLE FC_ACCBOOK ADD TRANS_STATUS CHAR(1);
GO
--修改日期：20130108
--修改人：吴生火
--修改内容：erp凭证号
--修改内容  FC_ACCBOOK 增加字段ERP_VOUCHER_NO
--参数设置：
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'ERP_VOUCHER_NO' AND LTRIM(B.NAME) = 'FC_ACCBOOK')
  alter table FC_ACCBOOK add ERP_VOUCHER_NO VARCHAR2(30);
GO
--修改日期：20130108
--修改人：吴生火
--修改内容：传输次数
--修改内容  FC_ACCBOOK 增加字段SEND_FREQUENCY
--参数设置：
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'SEND_FREQUENCY' AND LTRIM(B.NAME) = 'FC_ACCBOOK')
  alter table FC_ACCBOOK add SEND_FREQUENCY number default 0;
GO
--修改日期：20130108
--修改人：吴生火
--修改内容：返回信息
--修改内容  FC_ACCBOOK 增加字段TRANS_MSG
--参数设置：
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'TRANS_MSG' AND LTRIM(B.NAME) = 'FC_ACCBOOK')
  ALTER TABLE FC_ACCBOOK ADD TRANS_MSG VARCHAR2(500);
GO