--修改人:陈春燕
--修改时间:2012-12-24
--修改内容: 添加AB_RECEIVE_TEMP表。存储删除的库存票据
 
DECLARE
  VC_STR           VARCHAR2(2000);
  VN_COUNT         NUMBER;
BEGIN 
  SELECT COUNT(*)
    INTO VN_COUNT
    FROM USER_TABLES
   WHERE TABLE_NAME = 'AB_RECEIVE_TEMP';
  IF VN_COUNT < 1 THEN
    VC_STR := 'CREATE TABLE AB_RECEIVE_TEMP 
  (ID NUMBER(28,0) NOT NULL ENABLE, 
  ACCBOOK_ID CHAR(1) NOT NULL ENABLE, 
  SUBJECT CHAR(3) NOT NULL ENABLE, 
  CORP_ID NUMBER NOT NULL ENABLE, 
  CORP_NAME VARCHAR2(200) NOT NULL ENABLE, 
  DEPT_CODE CHAR(4), 
  CODE VARCHAR2(20) NOT NULL ENABLE, 
  CORP_CODE VARCHAR2(15), 
  BILL_TYPE VARCHAR2(20) NOT NULL ENABLE, 
  IS_BONDED NUMBER NOT NULL ENABLE, 
  MONEY NUMBER(18,2) NOT NULL ENABLE, 
  ISSUE_DATE DATE NOT NULL ENABLE, 
  MATURITY_DATE DATE NOT NULL ENABLE, 
  PAYER VARCHAR2(200) NOT NULL ENABLE, 
  ACCEPTOR VARCHAR2(200) NOT NULL ENABLE, 
  RESUME VARCHAR2(200), 
  SIGN_BANK VARCHAR2(20), 
  PRE_HAND VARCHAR2(200), 
  NEXT_HAND VARCHAR2(200), 
  STATE NUMBER NOT NULL ENABLE, 
  IS_TRUE NUMBER NOT NULL ENABLE, 
  IS_HELP NUMBER NOT NULL ENABLE, 
  OPERATOR_CODE VARCHAR2(8), 
  ENTER_DATE DATE NOT NULL ENABLE, 
  TALLY_FLAG NUMBER DEFAULT 0 NOT NULL ENABLE, 
  PAYEE_CORP_NAME VARCHAR2(80), 
  PAYEE_BANK_ACC VARCHAR2(30), 
  PAYEE_BANK_NAME VARCHAR2(140), 
  IS_PAY NUMBER, 
  PAYER_ACC VARCHAR2(100), 
  RECEIPT_DATE DATE, 
  DISCOUNT_TO_NET CHAR(1), 
  DISCOUNT_TO_MIDDLENET CHAR(1) DEFAULT 0, 
  IS_LOCK CHAR(1), 
  MORPLE_CODE VARCHAR2(50), 
  VENDOR_NUM VARCHAR2(31), 
  CONSTRAINT PK_AB_RECEIVE_TEMP PRIMARY KEY (ID)
   )';
    EXECUTE IMMEDIATE VC_STR;
  END IF;
END;
/

----creat index on AB_RECEIVE_TEMP
CREATE INDEX IDX_AB_RECEIVE_TEMP_01 ON AB_RECEIVE_TEMP (ACCBOOK_ID, CORP_ID, SUBJECT, STATE);
CREATE INDEX IDX_AB_RECEIVE_TEMP_02 ON AB_RECEIVE_TEMP (CORP_ID, TALLY_FLAG, STATE);



 

 



