
--修改日期：20130108
--修改人：吴生火
--修改内容：传输状态：0成功，1失败
--修改内容  FC_ACCBOOK 增加字段TRANS_STATUS
--参数设置：
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'TRANS_STATUS' AND LTRIM(B.NAME) = 'FC_ACCBOOK')
  ALTER TABLE FC_ACCBOOK ADD TRANS_STATUS CHAR(1);
GO
--修改日期：20130108
--修改人：吴生火
--修改内容：erp凭证号
--修改内容  FC_ACCBOOK 增加字段ERP_VOUCHER_NO
--参数设置：
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'ERP_VOUCHER_NO' AND LTRIM(B.NAME) = 'FC_ACCBOOK')
  alter table FC_ACCBOOK add ERP_VOUCHER_NO VARCHAR2(30);
GO
--修改日期：20130108
--修改人：吴生火
--修改内容：传输次数
--修改内容  FC_ACCBOOK 增加字段SEND_FREQUENCY
--参数设置：
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'SEND_FREQUENCY' AND LTRIM(B.NAME) = 'FC_ACCBOOK')
  alter table FC_ACCBOOK add SEND_FREQUENCY number default 0;
GO
--修改日期：20130108
--修改人：吴生火
--修改内容：返回信息
--修改内容  FC_ACCBOOK 增加字段TRANS_MSG
--参数设置：
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'TRANS_MSG' AND LTRIM(B.NAME) = 'FC_ACCBOOK')
  ALTER TABLE FC_ACCBOOK ADD TRANS_MSG VARCHAR2(500);
GO