
--修改日期：20130108
--修改人：李德成
--修改内容：背书增加后手单位编码
--修改内容  AB_RECEIVE 增加字段 付款单编号NEXT_VENDOR_NUM
--参数设置：
DECLARE
  ERP_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO ERP_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'AB_RECEIVE' AND COLUMN_NAME = 'NEXT_VENDOR_NUM';
  IF ERP_COUNT = 0 THEN
     EXECUTE IMMEDIATE 'ALTER TABLE AB_RECEIVE ADD NEXT_VENDOR_NUM VARCHAR2(31)';
  END IF;
END;
/

--修改字段长度
alter table nis_billhead modify billnumber varchar2(500);

--修改日期：20130108
--修改人：李德成
--修改内容：传输方式：SAP/OMS/NC
--修改内容  ERP_PAY_INFO 增加字段 TRANS_TYPE
--参数设置：
DECLARE
  ERP_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO ERP_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'ERP_PAY_INFO' AND COLUMN_NAME = 'TRANS_TYPE';
  IF ERP_COUNT = 0 THEN
     EXECUTE IMMEDIATE 'ALTER TABLE ERP_PAY_INFO ADD TRANS_TYPE VARCHAR2(10)';
  END IF;
END;
/

--修改日期：20130108
--修改人：李德成
--修改内容：传输状态：0成功，1失败
--修改内容  ERP_PAY_INFO 增加字段 TRANS_STATUS
--参数设置：
DECLARE
  ERP_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO ERP_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'ERP_PAY_INFO' AND COLUMN_NAME = 'TRANS_STATUS';
  IF ERP_COUNT = 0 THEN
     EXECUTE IMMEDIATE 'ALTER TABLE ERP_PAY_INFO ADD TRANS_STATUS CHAR(1)';
  END IF;
END;
/
--修改日期：20130108
--修改人：李德成
--修改内容：erp凭证号
--修改内容  ERP_PAY_INFO 增加字段 ERP_VOUCHER_NO
--参数设置：
DECLARE
  ERP_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO ERP_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'ERP_PAY_INFO' AND COLUMN_NAME = 'ERP_VOUCHER_NO';
  IF ERP_COUNT = 0 THEN
     EXECUTE IMMEDIATE 'ALTER TABLE ERP_PAY_INFO ADD ERP_VOUCHER_NO VARCHAR2(60)';
  END IF;
END;
/
--修改日期：20130108
--修改人：李德成
--修改内容：传输次数
--修改内容  ERP_PAY_INFO 增加字段 SEND_FREQUENCY 
--参数设置：
DECLARE
  ERP_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO ERP_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'ERP_PAY_INFO' AND COLUMN_NAME = 'SEND_FREQUENCY';
  IF ERP_COUNT = 0 THEN
     EXECUTE IMMEDIATE 'alter table ERP_PAY_INFO add SEND_FREQUENCY number default 0';
  END IF;
END;
/
--修改日期：20130108
--修改人：李德成
--修改内容：返回信息
--修改内容  ERP_PAY_INFO 增加字段 TRANS_MSG
--参数设置：
DECLARE
  ERP_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO ERP_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'ERP_PAY_INFO' AND COLUMN_NAME = 'TRANS_MSG';
  IF ERP_COUNT = 0 THEN
     EXECUTE IMMEDIATE 'ALTER TABLE ERP_PAY_INFO ADD TRANS_MSG VARCHAR2(500)';
  END IF;
END;
/
--修改日期：20130108
--修改人：李德成
--修改内容：收款行联行号
--修改内容  ERP_PAY_INFO 增加字段 PAYEE_BANK_CODE
--参数设置：
DECLARE
  ERP_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO ERP_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'ERP_PAY_INFO' AND COLUMN_NAME = 'PAYEE_BANK_CODE';
  IF ERP_COUNT = 0 THEN
     EXECUTE IMMEDIATE 'alter table ERP_PAY_INFO add PAYEE_BANK_CODE VARCHAR2(20)';
  END IF;
END;
/
--修改日期：20130108
--修改人：李德成
--修改内容：付款方式
--修改内容  ERP_PAY_INFO 增加字段 PAYTYPE
--参数设置：
DECLARE
  ERP_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO ERP_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'ERP_PAY_INFO' AND COLUMN_NAME = 'PAYTYPE';
  IF ERP_COUNT = 0 THEN
     EXECUTE IMMEDIATE 'alter table ERP_PAY_INFO add PAYTYPE VARCHAR2(10)';
  END IF;
END;
/
--修改日期：20130108
--修改人：李德成
--修改内容：业务类型
--修改内容  ERP_PAY_INFO 增加字段 BUSINESSTYPE
--参数设置：
DECLARE
  ERP_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO ERP_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'ERP_PAY_INFO' AND COLUMN_NAME = 'BUSINESSTYPE';
  IF ERP_COUNT = 0 THEN
     EXECUTE IMMEDIATE 'alter table ERP_PAY_INFO add BUSINESSTYPE VARCHAR2(50)';
  END IF;
END;
/
--修改日期：20130108
--修改人：李德成
--修改内容：背书增加后手单位编码
--修改内容  ERP_PAY_INFO 增加字段TEMPORARYMONEY
--参数设置：暂支款
DECLARE
  ERP_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO ERP_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'ERP_PAY_INFO' AND COLUMN_NAME = 'TEMPORARYMONEY';
  IF ERP_COUNT = 0 THEN
     EXECUTE IMMEDIATE 'alter table ERP_PAY_INFO add TEMPORARYMONEY NUMBER(15,2)';
  END IF;
END;
/

--修改日期：20130108
--修改人：李德成
--修改内容：记账所属成本中心代码
--修改内容  ERP_PAY_INFO 增加字段REC_COST_CENTER_CODE
--参数设置：
DECLARE
  ERP_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO ERP_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'ERP_PAY_INFO' AND COLUMN_NAME = 'REC_COST_CENTER_CODE';
  IF ERP_COUNT = 0 THEN
     EXECUTE IMMEDIATE 'alter table ERP_PAY_INFO add REC_COST_CENTER_CODE VARCHAR2(20)';
  END IF;
END;
/

--修改日期：20130108
--修改人：李德成
--修改内容：记账所属成本中心名称
--修改内容  ERP_PAY_INFO 增加字段REC_COST_CENTER_NAME
--参数设置：
DECLARE
  ERP_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO ERP_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'ERP_PAY_INFO' AND COLUMN_NAME = 'REC_COST_CENTER_NAME';
  IF ERP_COUNT = 0 THEN
     EXECUTE IMMEDIATE 'alter table ERP_PAY_INFO add REC_COST_CENTER_NAME VARCHAR2(80)';
  END IF;
END;
/

--修改日期：20130108
--修改人：李德成
--修改内容：供应商编号
--修改内容  ERP_PAY_INFO 增加字段EXTERNAL_CODE
--参数设置：
DECLARE
  ERP_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO ERP_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'ERP_PAY_INFO' AND COLUMN_NAME = 'EXTERNAL_CODE';
  IF ERP_COUNT = 0 THEN
     EXECUTE IMMEDIATE 'alter table ERP_PAY_INFO add EXTERNAL_CODE VARCHAR2(20)';
  END IF;
END;
/

--修改日期：20130108
--修改人：李德成
--修改内容：传输状态：0成功，1失败
--修改内容  FC_ACCBOOK_BLNED 增加字段TRANS_STATUS
--参数设置：
DECLARE
  ERP_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO ERP_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'FC_ACCBOOK_BLNED' AND COLUMN_NAME = 'TRANS_STATUS';
  IF ERP_COUNT = 0 THEN
     EXECUTE IMMEDIATE 'ALTER TABLE FC_ACCBOOK_BLNED ADD TRANS_STATUS CHAR(1)';
  END IF;
END;
/

--修改日期：20130108
--修改人：李德成
--修改内容：erp凭证号
--修改内容  FC_ACCBOOK_BLNED 增加字段ERP_VOUCHER_NO
--参数设置：
DECLARE
  ERP_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO ERP_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'FC_ACCBOOK_BLNED' AND COLUMN_NAME = 'ERP_VOUCHER_NO';
  IF ERP_COUNT = 0 THEN
     EXECUTE IMMEDIATE 'alter table FC_ACCBOOK_BLNED add ERP_VOUCHER_NO VARCHAR2(30)';
  END IF;
END;
/

--修改日期：20130108
--修改人：李德成
--修改内容：传输次数
--修改内容  FC_ACCBOOK_BLNED 增加字段SEND_FREQUENCY
--参数设置：
DECLARE
  ERP_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO ERP_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'FC_ACCBOOK_BLNED' AND COLUMN_NAME = 'SEND_FREQUENCY';
  IF ERP_COUNT = 0 THEN
     EXECUTE IMMEDIATE 'alter table FC_ACCBOOK_BLNED add SEND_FREQUENCY number default 0';
  END IF;
END;
/

--修改日期：20130108
--修改人：李德成
--修改内容：返回信息
--修改内容  FC_ACCBOOK_BLNED 增加字段TRANS_MSG
--参数设置：
DECLARE
  ERP_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO ERP_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'FC_ACCBOOK_BLNED' AND COLUMN_NAME = 'TRANS_MSG';
  IF ERP_COUNT = 0 THEN
     EXECUTE IMMEDIATE 'ALTER TABLE FC_ACCBOOK_BLNED ADD TRANS_MSG VARCHAR2(500)';
  END IF;
END;
/


--修改日期：20130108
--修改人：李德成
--修改内容：erp凭证号
--修改内容  BT_NET_CHALK 增加字段ERP_VOUCHER_NO
--参数设置：
DECLARE
  ERP_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO ERP_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'BT_NET_CHALK' AND COLUMN_NAME = 'ERP_VOUCHER_NO';
  IF ERP_COUNT = 0 THEN
     EXECUTE IMMEDIATE 'alter table BT_NET_CHALK add ERP_VOUCHER_NO VARCHAR2(30)';
  END IF;
END;
/

--修改日期：20130108
--修改人：李德成
--修改内容：传输次数
--修改内容  BT_NET_CHALK 增加字段SEND_FREQUENCY
--参数设置：
DECLARE
  ERP_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO ERP_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'BT_NET_CHALK' AND COLUMN_NAME = 'SEND_FREQUENCY';
  IF ERP_COUNT = 0 THEN
     EXECUTE IMMEDIATE 'alter table BT_NET_CHALK add SEND_FREQUENCY number default 0';
  END IF;
END;
/

--修改日期：20130108
--修改人：李德成
--修改内容：返回信息
--修改内容  BT_NET_CHALK 增加字段TRANS_MSG
--参数设置：
DECLARE
  ERP_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO ERP_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'BT_NET_CHALK' AND COLUMN_NAME = 'TRANS_MSG';
  IF ERP_COUNT = 0 THEN
     EXECUTE IMMEDIATE 'ALTER TABLE BT_NET_CHALK ADD TRANS_MSG VARCHAR2(500)';
  END IF;
END;
/


--修改日期：20130108
--修改人：吴生火
--修改内容：传输状态：0成功，1失败
--修改内容  FC_ACCBOOK 增加字段TRANS_STATUS
--参数设置：
DECLARE
  ERP_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO ERP_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'FC_ACCBOOK' AND COLUMN_NAME = 'TRANS_STATUS';
  IF ERP_COUNT = 0 THEN
     EXECUTE IMMEDIATE 'ALTER TABLE FC_ACCBOOK ADD TRANS_STATUS CHAR(1)';
  END IF;
END;
/

--修改日期：20130108
--修改人：吴生火
--修改内容：erp凭证号
--修改内容  FC_ACCBOOK 增加字段ERP_VOUCHER_NO
--参数设置：
DECLARE
  ERP_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO ERP_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'FC_ACCBOOK' AND COLUMN_NAME = 'ERP_VOUCHER_NO';
  IF ERP_COUNT = 0 THEN
     EXECUTE IMMEDIATE 'alter table FC_ACCBOOK add ERP_VOUCHER_NO VARCHAR2(30)';
  END IF;
END;
/

--修改日期：20130108
--修改人：吴生火
--修改内容：传输次数
--修改内容  FC_ACCBOOK 增加字段SEND_FREQUENCY
--参数设置：
DECLARE
  ERP_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO ERP_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'FC_ACCBOOK' AND COLUMN_NAME = 'SEND_FREQUENCY';
  IF ERP_COUNT = 0 THEN
     EXECUTE IMMEDIATE 'alter table FC_ACCBOOK add SEND_FREQUENCY number default 0';
  END IF;
END;
/

--修改日期：20130108
--修改人：吴生火
--修改内容：返回信息
--修改内容  FC_ACCBOOK 增加字段TRANS_MSG
--参数设置：
DECLARE
  ERP_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO ERP_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'FC_ACCBOOK' AND COLUMN_NAME = 'TRANS_MSG';
  IF ERP_COUNT = 0 THEN
     EXECUTE IMMEDIATE 'ALTER TABLE FC_ACCBOOK ADD TRANS_MSG VARCHAR2(500)';
  END IF;
END;
/

