
--修改日期：20130108
--修改人：吴生火
--修改内容：传输状态：0成功，1失败
--修改内容  FC_ACCBOOK 增加字段TRANS_STATUS
--参数设置：
DECLARE
  ERP_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO ERP_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'FC_ACCBOOK' AND COLUMN_NAME = 'TRANS_STATUS';
  IF ERP_COUNT = 0 THEN
     EXECUTE IMMEDIATE 'ALTER TABLE FC_ACCBOOK ADD TRANS_STATUS CHAR(1)';
  END IF;
END;
/

--修改日期：20130108
--修改人：吴生火
--修改内容：erp凭证号
--修改内容  FC_ACCBOOK 增加字段ERP_VOUCHER_NO
--参数设置：
DECLARE
  ERP_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO ERP_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'FC_ACCBOOK' AND COLUMN_NAME = 'ERP_VOUCHER_NO';
  IF ERP_COUNT = 0 THEN
     EXECUTE IMMEDIATE 'alter table FC_ACCBOOK add ERP_VOUCHER_NO VARCHAR2(30)';
  END IF;
END;
/

--修改日期：20130108
--修改人：吴生火
--修改内容：传输次数
--修改内容  FC_ACCBOOK 增加字段SEND_FREQUENCY
--参数设置：
DECLARE
  ERP_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO ERP_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'FC_ACCBOOK' AND COLUMN_NAME = 'SEND_FREQUENCY';
  IF ERP_COUNT = 0 THEN
     EXECUTE IMMEDIATE 'alter table FC_ACCBOOK add SEND_FREQUENCY number default 0';
  END IF;
END;
/

--修改日期：20130108
--修改人：吴生火
--修改内容：返回信息
--修改内容  FC_ACCBOOK 增加字段TRANS_MSG
--参数设置：
DECLARE
  ERP_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO ERP_COUNT FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'FC_ACCBOOK' AND COLUMN_NAME = 'TRANS_MSG';
  IF ERP_COUNT = 0 THEN
     EXECUTE IMMEDIATE 'ALTER TABLE FC_ACCBOOK ADD TRANS_MSG VARCHAR2(500)';
  END IF;
END;
/
