--修改日期 20130130
--修改人 田进
--修改内容 增加银行接口设置表
CREATE TABLE ERP_INTER_CONFIG
(
     INTER_CODE VARCHAR(1) PRIMARY KEY,--收付标志（0：收； 1：付；2：凭证）
     OFFLINE_SIGN VARCHAR(1),--离线标志（0：否：1是）
     ONLINE_SIGN VARCHAR(1),--在线标志（0：否：1是）
     AUTOSEND_SIGN VARCHAR(1),--自动发送标志（0：否：1是）
     SPLIT_SIGN VARCHAR(1),--拆分标志（0：否：1是）
     MERGER_SIGN VARCHAR(1),--合并标志（0：否：1是）
     BUDGETMATCH_SIGN VARCHAR(1),--预算匹配标志（0：否：1是）
     MAKEUP_SIGN VARCHAR(1),--补录标志（0：否：1是）
     NET_SIGN VARCHAR(1),--生成网点凭证（0：否：1是）
     CORP_SIGN VARCHAR(1),--生成单位凭证（0：否：1是）
     COMPARE_SIGN VARCHAR(1),--勾兑付款指令(0：否：1是)
     DATA_SOURCE VARCHAR(20) --发送的数据来源（bytter:B,erp:E,other:O）
)
GO
--张少举 
--新增
--付款模版匹配


IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'TEMPLATE_ID_1' AND LTRIM(B.NAME) = 'NIS_BILLHEAD')
	alter table NIS_BILLHEAD add TEMPLATE_ID_1 NUMERIC(10)
GO
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'TEMPLATE_ID_2' AND LTRIM(B.NAME) = 'NIS_BILLHEAD')
	alter table NIS_BILLHEAD add TEMPLATE_ID_2 NUMERIC(10)
GO
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'COST_CENTER_CODE' AND LTRIM(B.NAME) = 'NIS_BILLHEAD')
	alter table NIS_BILLHEAD add COST_CENTER_CODE VARCHAR(10)
GO