CREATE OR REPLACE VIEW V_CMS_LOAN_BILL AS
SELECT CLI.CORP_ID,
       BC.CORP_CODE,
       BC.CORP_NAME,
       CLI.STATUS AS LOAN_STATE,
       CLI.LOAN_GENRE,
       TO_CHAR(CLI.LOAN_DATE, 'YYYY-MM-DD') AS LOAN_DATE,
       SUM(NVL(CLI.LOAN_MONEY, 0)) AS CONTRACT_SUM,
       SUM(CASE WHEN TO_CHAR(LSOI.LOAN_SEND_OUT_DATE, 'YYYY') = TO_CHAR(SYSDATE, 'YYYY') THEN LSOI.LOAN_SEND_OUT_MONEY ELSE 0 END) AS LOAN_SUM,
       SUM(NVL(LSOI.LOAN_SEND_OUT_MONEY, 0)) AS LOAN_SUM_ALL,       
       SUM(CASE WHEN TO_CHAR(CLR.REPAY_DATE, 'YYYY') = TO_CHAR(SYSDATE, 'YYYY') AND CLR.STATUS >= 95 THEN CLR.REPAY_MONEY ELSE 0 END) AS REPAY_SUM,
       SUM(CASE WHEN CLR.STATUS >= 95 THEN CLR.REPAY_MONEY ELSE 0 END) AS REPAY_SUM_ALL,
       SUM(NVL(LSOI.LOAN_SEND_OUT_MONEY, 0)) AS LOAN_MONEY,
       (SUM(NVL(CLI.LOAN_MONEY, 0)) - SUM((CASE WHEN CLR.STATUS >= 95 THEN CLR.REPAY_MONEY ELSE 0 END))) AS LOAN_MONEY_LAST
FROM CMS_LOAN_INFO CLI
LEFT JOIN LOAN_SEND_OUT_INFO LSOI ON CLI.BILL_CODE = LSOI.FATHER_CODE
LEFT JOIN CMS_CONTRACT CCT ON LSOI.BILL_CODE = CCT.LI_CODE
LEFT JOIN CMS_LOAN_REPAY CLR ON CLR.LI_CODE = LSOI.BILL_CODE
LEFT JOIN BT_CORP BC ON CLI.CORP_ID = BC.ID
WHERE CLI.STATUS >= 95
GROUP BY CLI.CORP_ID, BC.CORP_CODE, BC.CORP_NAME, CLI.LOAN_DATE, CLI.STATUS, CLI.LOAN_GENRE;