--修改日期：20120918
--修改人：叶爱军
--需求编号：XD-JD03-027 系统功能-贷款台账
--修改内容：系统菜单 增加 贷款台账
--参数设置：
INSERT INTO BT_SYS_RES (RES_CODE, RES_NAME, SYS_CODE, FATHER_CODE, RES_URL, FUNC_FLAG, RES_TYPE, LINK_TARGET, STATUS, RES_ORDER, RMK, REVERSE1, REVERSE2, REVERSE3, REVERSE4, REVERSE5, REVERSE6, REVERSE7, REVERSE8, REVERSE9, REVERSE10, RES_LEVEL, RES_ROLE)
SELECT (SELECT MAX(T1.RES_CODE) + 1 FROM BT_SYS_RES T1), '贷款台账', 'cms', RES_CODE, '/cms/cmsLoanBill.do?method=toList', '0', '0', '0', '0', (SELECT MAX(T2.RES_ORDER)+1 FROM BT_SYS_RES T2 WHERE T2.FATHER_CODE = T3.RES_CODE AND T2.SYS_CODE = 'cms'), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, '' FROM BT_SYS_RES T3 WHERE T3.RES_NAME = '贷款管理' AND T3.SYS_CODE = 'cms';
COMMIT;

--修改日期：20120918
--修改人：余川锋
--需求编号：XD-JD03-029 
--修改内容：系统菜单 增加资金占用费
insert into bt_sys_res (RES_CODE, RES_NAME, SYS_CODE, FATHER_CODE, RES_URL, FUNC_FLAG, RES_TYPE, LINK_TARGET, STATUS, RES_ORDER, RMK, REVERSE1, REVERSE2, REVERSE3, REVERSE4, REVERSE5, REVERSE6, REVERSE7, REVERSE8, REVERSE9, REVERSE10, RES_LEVEL, RES_ROLE)
values ((select max(res_code) + 1 from bt_sys_res), '资金占用费', 'cms', (select res_code from bt_sys_res  where res_name='贷款管理' and SYS_CODE='cms'), '', '0', '1', '0', '0', (select max(t.res_order)+1 from bt_sys_res t  where t.father_code=(select res_code from bt_sys_res  where res_name='贷款管理')), '资金占用费', '', '', '', '', '', null, null, null, null, null, 2, '');

insert into bt_sys_res (RES_CODE, RES_NAME, SYS_CODE, FATHER_CODE, RES_URL, FUNC_FLAG, RES_TYPE, LINK_TARGET, STATUS, RES_ORDER, RMK, REVERSE1, REVERSE2, REVERSE3, REVERSE4, REVERSE5, REVERSE6, REVERSE7, REVERSE8, REVERSE9, REVERSE10, RES_LEVEL, RES_ROLE)
values ((select max(res_code) + 1 from bt_sys_res), '计费', 'cms', (select res_code from bt_sys_res  where res_name='资金占用费' and SYS_CODE='cms' and res_level=2), '/cms/billing.do?method=toList', '0', '1', '0', '0', 1, '证劵资金账号维护', '', '', '', '', '', null, null, null, null, null, 3, '');

insert into bt_sys_res (RES_CODE, RES_NAME, SYS_CODE, FATHER_CODE, RES_URL, FUNC_FLAG, RES_TYPE, LINK_TARGET, STATUS, RES_ORDER, RMK, REVERSE1, REVERSE2, REVERSE3, REVERSE4, REVERSE5, REVERSE6, REVERSE7, REVERSE8, REVERSE9, REVERSE10, RES_LEVEL, RES_ROLE)
values ((select max(res_code) + 1 from bt_sys_res), '核算占用费', 'cms', (select res_code from bt_sys_res  where res_name='资金占用费' and SYS_CODE='cms' and res_level=2), '/cms/accountingFee.do?method=toList', '0', '1', '0', '0', 1, '证劵资金账号维护', '', '', '', '', '', null, null, null, null, null, 3, '');


--修改日期：20120928
--修改人：叶爱军 
--需求编号：XD-JD03-030 系统功能-缴费记录
--修改内容：系统菜单 增加 缴费记录
--参数设置：
INSERT INTO BT_SYS_RES (RES_CODE, RES_NAME, SYS_CODE, FATHER_CODE, RES_URL, FUNC_FLAG, RES_TYPE, LINK_TARGET, STATUS, RES_ORDER, RMK, REVERSE1, REVERSE2, REVERSE3, REVERSE4, REVERSE5, REVERSE6, REVERSE7, REVERSE8, REVERSE9, REVERSE10, RES_LEVEL, RES_ROLE)
SELECT (SELECT MAX(T1.RES_CODE) + 1 FROM BT_SYS_RES T1), '缴费记录', 'cms', RES_CODE, '/cms/cmsPaymentRecord.do?method=toList', '0', '0', '0', '0', (SELECT MAX(T2.RES_ORDER)+1 FROM BT_SYS_RES T2 WHERE T2.FATHER_CODE = T3.RES_CODE AND T2.SYS_CODE = 'cms'), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, '' FROM BT_SYS_RES T3 WHERE T3.RES_NAME = '资金占用费' AND T3.SYS_CODE = 'cms';
COMMIT;

--修改日期：20120920
--修改人：高枫
--修改内容：XD-JD03-028 系统功能-贷款减免
--修改内容：系统菜单 增加 贷款减免
--参数设置：
INSERT INTO BT_SYS_RES (RES_CODE, RES_NAME, SYS_CODE, FATHER_CODE, RES_URL, FUNC_FLAG, RES_TYPE, LINK_TARGET, STATUS, RES_ORDER, RMK, REVERSE1, REVERSE2, REVERSE3, REVERSE4, REVERSE5, REVERSE6, REVERSE7, REVERSE8, REVERSE9, REVERSE10, RES_LEVEL, RES_ROLE)
SELECT (SELECT MAX(T1.RES_CODE) + 1 FROM BT_SYS_RES T1), '贷款减免', 'cms', RES_CODE, '/cms/cmsLoanAnnul.do?method=initQuery', '0', '1', '0', '0', (SELECT MAX(T2.RES_ORDER)+1 FROM BT_SYS_RES T2 WHERE T2.FATHER_CODE = T3.RES_CODE AND T2.SYS_CODE = 'cms'), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, '' FROM BT_SYS_RES T3 WHERE T3.RES_NAME = '贷款管理' AND T3.SYS_CODE = 'cms';
COMMIT;

--修改日期：20120920
--修改人：高枫 
--修改内容：XD-JD03-027 系统功能-贷款还款
--修改内容：系统菜单 增加 贷款台账还款
--参数设置：
INSERT INTO BT_SYS_RES (RES_CODE, RES_NAME, SYS_CODE, FATHER_CODE, RES_URL, FUNC_FLAG, RES_TYPE, LINK_TARGET, STATUS, RES_ORDER, RMK, REVERSE1, REVERSE2, REVERSE3, REVERSE4, REVERSE5, REVERSE6, REVERSE7, REVERSE8, REVERSE9, REVERSE10, RES_LEVEL, RES_ROLE)
SELECT (SELECT MAX(T1.RES_CODE) + 1 FROM BT_SYS_RES T1), '贷款还款台账', 'cms', RES_CODE, '/cms/cmsLoanRepay.do?method=initQuery', '0', '1', '0', '0', (SELECT MAX(T2.RES_ORDER)+1 FROM BT_SYS_RES T2 WHERE T2.FATHER_CODE = T3.RES_CODE AND T2.SYS_CODE = 'cms'), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, '' FROM BT_SYS_RES T3 WHERE T3.RES_NAME = '贷款管理' AND T3.SYS_CODE = 'cms';
COMMIT;

--修改日期：20120921
--修改人：叶爱军
--修改内容：XD-JD03-027 系统功能-贷款台账
--修改内容：担保方式 1,增加 组合担保，其它;2,修改TYPE_NAME;
--参数设置：
UPDATE CMS_PROVIDE_LOAN_TYPE SET TYPE_NAME = '信用/免担保贷款' WHERE TYPE_CODE = '01' AND OPERATION_TYPE = 'A';
UPDATE CMS_PROVIDE_LOAN_TYPE SET TYPE_NAME = '保证贷款' WHERE TYPE_CODE = '02' AND OPERATION_TYPE = 'A';
UPDATE CMS_PROVIDE_LOAN_TYPE SET TYPE_NAME = '抵押贷款' WHERE TYPE_CODE = '03' AND OPERATION_TYPE = 'A';
UPDATE CMS_PROVIDE_LOAN_TYPE SET TYPE_NAME = '质押贷款' WHERE TYPE_CODE = '04' AND OPERATION_TYPE = 'A';
INSERT INTO CMS_PROVIDE_LOAN_TYPE (TYPE_CODE, TYPE_NAME, OPERATION_TYPE) VALUES ('05', '组合担保', 'A');
INSERT INTO CMS_PROVIDE_LOAN_TYPE (TYPE_CODE, TYPE_NAME, OPERATION_TYPE) VALUES ('06', '其他', 'A');
COMMIT;

CREATE TABLE CMS_LOAN_ABATE  (
   CLA_ID               VARCHAR2(32)                    NOT NULL,
   CLB_ID               VARCHAR2(32),
   NEXTCHECKER          VARCHAR2(200),
   APPROVES             VARCHAR2(200),
   CORP_ID              VARCHAR2(32),
   USER_ID              VARCHAR2(32),
   CLA_NO               VARCHAR2(14),
   CLA_CREATE_TIME      DATE,
   CLA_DATE             DATE,
   CLA_MONEY            NUMBER(15,2),
   CLA_STATUS           NUMBER(10),
   CLA_FIXED_MONEY      NUMBER(15,2),
   CLA_AGREEMENT_MONEY  NUMBER(15,2),
   CLA_MEMO             VARCHAR2(1000),
   CLA_DESC             VARCHAR2(2000),
   CONSTRAINT PK_CMS_LOAN_ABATE PRIMARY KEY (CLA_ID)
);

CREATE TABLE CMS_LOAN_BILL  (
   CLB_ID               VARCHAR2(32)                    NOT NULL,
   NEXTCHECKER          VARCHAR2(200),
   APPROVES             VARCHAR2(200),
   CORP_ID              VARCHAR2(32),
   USER_ID              VARCHAR2(32),
   CLB_NO               VARCHAR2(14),
   CLB_CREATE_TIME      DATE,
   CLB_LOAN_CORP_ID     VARCHAR2(4),
   CLB_BORROW_CORP_ID   VARCHAR2(4),
   CLB_LOAN_MONEY       NUMBER(15,2),
   CLB_BALANCE          NUMBER(15,2),
   CLB_START_DATE       DATE,
   CLB_END_DATE         DATE,
   CLB_FIXED_RATE       NUMBER(9,6),
   CLB_AGREEMENT_RATE   NUMBER(9,6),
   CLB_ITEM_CODE        VARCHAR2(20),
   CLB_REPAY_TYPE       VARCHAR2(2),
   CLB_CONTRACT_TERM    NUMBER,
   CLB_LOAN_TYPE        VARCHAR2(2),
   CLB_CURRENCY         VARCHAR2(2),
   CLB_LOAN_TERM        NUMBER,
   CLB_STATUS           NUMBER(10),
   CLB_GUARANTEE        NUMBER(15,2),
   CLB_GUA_MEMO         VARCHAR2(2000),
   CLB_LOAN_MEMO        VARCHAR2(2000),
   CLB_MEMO             VARCHAR2(1000),
   CLB_FILE             VARCHAR2(1000),
   CLB_LAST_BILLING_DATE DATE,
   CONSTRAINT PK_CMS_LOAN_BILL PRIMARY KEY (CLB_ID)
);

CREATE TABLE CMS_PAYMENT_RECORDS  (
   CPR_ID               VARCHAR2(32)                    NOT NULL,
   CLB_ID               VARCHAR2(32),
   CORP_ID              VARCHAR2(32),
   USER_ID              VARCHAR2(32),
   NEXTCHECKER          VARCHAR2(200),
   APPROVES             VARCHAR2(200),
   CPR_NO               VARCHAR2(14),
   CPR_MONEY            NUMBER(15,2),
   CPR_FIXED_MONEY      NUMBER(15,2),
   CPR_AGREEMENT_MONEY  NUMBER(15,2),
   CPR_CREATE_TIME      DATE,
   CPR_PAYMENT_DATE     DATE,
   CPR_STATUS           NUMBER(10),
   CPR_DESC             VARCHAR2(2000),
   CONSTRAINT PK_CMS_PAYMENT_RECORDS PRIMARY KEY (CPR_ID)
);

CREATE TABLE CMS_REPAY_LOAN  (
   CRL_ID               VARCHAR2(32)                    NOT NULL,
   CLB_ID               VARCHAR2(32),
   NEXTCHECKER          VARCHAR2(200),
   APPROVES             VARCHAR2(200),
   CORP_ID              VARCHAR2(32),
   USER_ID              VARCHAR2(32),
   CRL_NO               VARCHAR2(14),
   CRL_CREATE_TIME      DATE,
   CRL_DATE             DATE,
   CRL_MONEY            NUMBER(15,2),
   CRL_STATUS           NUMBER(10),
   CRL_FIXED_MONEY      NUMBER(15,6),
   CRL_AGREEMENT_MONEY  NUMBER(15,6),
   CRL_MEMO             VARCHAR2(1000),
   CRL_DESC             VARCHAR2(2000),
   CONSTRAINT PK_CMS_REPAY_LOAN PRIMARY KEY (CRL_ID)
);

ALTER TABLE CMS_LOAN_ABATE
   ADD CONSTRAINT FK_CMS_LOAN_REL_BILL__CMS_LOAN FOREIGN KEY (CLB_ID)
      REFERENCES CMS_LOAN_BILL (CLB_ID);

ALTER TABLE CMS_PAYMENT_RECORDS
   ADD CONSTRAINT FK_CMS_PAYM_REL_PAYME_CMS_LOAN FOREIGN KEY (CLB_ID)
      REFERENCES CMS_LOAN_BILL (CLB_ID);

ALTER TABLE CMS_REPAY_LOAN
   ADD CONSTRAINT FK_CMS_REPA_RAL_BILL__CMS_LOAN FOREIGN KEY (CLB_ID)
      REFERENCES CMS_LOAN_BILL (CLB_ID);

ALTER TABLE CMS_REPAY_LOAN ADD BILL_BLANCE  NUMBER(15,2) default(0);
--增加贷款减免余额控制
ALTER TABLE CMS_LOAN_ABATE ADD BILL_BLANCE  NUMBER(15,2) default(0);

--增加固定占用费率与协定占用费率
ALTER TABLE CMS_LOAN_INFO ADD CLB_AGREEMENT_RATE NUMBER(15, 6);
--增加固定占用费率与协定占用费率
ALTER TABLE LOAN_SEND_OUT_INFO ADD CLB_AGREEMENT_RATE NUMBER(15, 6);

/*==============================================================*/
/* Table: CMS_BILLING                                           */
/*==============================================================*/
create table CMS_BILLING
(
  BILLING_ID         VARCHAR2(32) not null,
  FIX_FEE            NUMBER(15,2),
  AGREEMENT_FEE      NUMBER(15,2),
  FIXED_RATE         NUMBER(9,6),
  AGREEMENT_RATE     NUMBER(9,6),
  FEE_DATE           DATE,
  STATUS             NUMBER(10),
  CLB_ID             VARCHAR2(32),
  CLB_BALANCE        NUMBER(15,2),
  FEE_START_DATE     DATE,
  FEE_END_DATE       DATE,
  NOTICE_NUM         NVARCHAR2(32),
  FIX_FEE_REAL       NUMBER(15,2),
  AGREEMENT_FEE_REAL NUMBER(15,2),
  MAKER              VARCHAR2(8),
  AUDITOR            VARCHAR2(8),
  constraint CMS_BILLING_PK primary key (BILLING_ID)
);
comment on column CMS_BILLING.CLB_ID
  is '贷款台账ID';
comment on column CMS_BILLING.CLB_BALANCE
  is '当前余额';
comment on column CMS_BILLING.FEE_START_DATE
  is '计费开始时间';
comment on column CMS_BILLING.FEE_END_DATE
  is '计费结束时间';
comment on column CMS_BILLING.NOTICE_NUM
  is '通知单号';
comment on column CMS_BILLING.FIX_FEE_REAL
  is '修改后的固定占用费';
comment on column CMS_BILLING.AGREEMENT_FEE_REAL
  is '修改后的协定占用费';
comment on column CMS_BILLING.MAKER
  is '制单人';
comment on column CMS_BILLING.AUDITOR
  is '审核人';

UPDATE CMS_LOAN_INFO SET CLB_AGREEMENT_RATE = 0;
UPDATE LOAN_SEND_OUT_INFO SET CLB_AGREEMENT_RATE = 0;
COMMIT;
 
--修改日期：20121017
--修改人：叶爱军
--修改内容：CMS_LOAN_BILL 增加字段 应付固定费用 应付协定费用 已付固定费用 已付协定费用 减免固定费用 减免协定费用 待付固定费用 待付协定费用
--参数设置： 
ALTER TABLE CMS_LOAN_BILL ADD CLB_BIIL_FIX NUMBER(15,2) default(0);
ALTER TABLE CMS_LOAN_BILL ADD CLB_BILL_AGREEMENT NUMBER(15,2) default(0);
ALTER TABLE CMS_LOAN_BILL ADD CLB_PAY_FIX NUMBER(15,2) default(0);
ALTER TABLE CMS_LOAN_BILL ADD CLB_PAY_AGREEMENT NUMBER(15,2) default(0);
ALTER TABLE CMS_LOAN_BILL ADD CLB_ABATE_FIX NUMBER(15,2) default(0);
ALTER TABLE CMS_LOAN_BILL ADD CLB_ABATE_AGREEMENT NUMBER(15,2) default(0);
ALTER TABLE CMS_LOAN_BILL ADD CLB_UNPAY_FIX NUMBER(15,2) default(0);
ALTER TABLE CMS_LOAN_BILL ADD CLB_UNPAY_AGREEMENT NUMBER(15,2) default(0);

UPDATE CMS_LOAN_BILL SET CLB_BIIL_FIX = 0 WHERE CLB_BIIL_FIX IS NULL;
UPDATE CMS_LOAN_BILL SET CLB_BILL_AGREEMENT = 0 WHERE CLB_BILL_AGREEMENT IS NULL;
UPDATE CMS_LOAN_BILL SET CLB_PAY_FIX = 0 WHERE CLB_PAY_FIX IS NULL;
UPDATE CMS_LOAN_BILL SET CLB_PAY_AGREEMENT = 0 WHERE CLB_PAY_AGREEMENT IS NULL;
UPDATE CMS_LOAN_BILL SET CLB_ABATE_FIX = 0 WHERE CLB_ABATE_FIX IS NULL;
UPDATE CMS_LOAN_BILL SET CLB_ABATE_AGREEMENT = 0 WHERE CLB_ABATE_AGREEMENT IS NULL;
UPDATE CMS_LOAN_BILL SET CLB_UNPAY_FIX = 0 WHERE CLB_UNPAY_FIX IS NULL;
UPDATE CMS_LOAN_BILL SET CLB_UNPAY_AGREEMENT = 0 WHERE CLB_UNPAY_AGREEMENT IS NULL;
COMMIT;

--修改日期：20121018
--修改人：叶爱军
--修改内容：CMS_PAYMENT_RECORDS 增加字段 CPR_IS_AUTOMATIC
--参数设置： 
ALTER TABLE CMS_PAYMENT_RECORDS ADD CPR_IS_AUTOMATIC NUMBER(1);

UPDATE CMS_PAYMENT_RECORDS SET CPR_IS_AUTOMATIC = 0 WHERE CPR_IS_AUTOMATIC IS NULL;
COMMIT;

CREATE OR REPLACE VIEW V_CMS_LOAN_BOOK AS
SELECT CLB.CLB_ID,
       CLB.CLB_NO,
       CLB.CLB_LOAN_CORP_ID AS BL_CORP_ID,
       BL.CORP_CODE AS BL_CORP_CODE,
       BL.CORP_NAME AS BL_CORP_NAME,
       CLB.CLB_BORROW_CORP_ID AS BB_CORP_ID,
       BB.CORP_CODE AS BB_CORP_CODE,
       BB.CORP_NAME AS BB_CORP_NAME,
       ROUND(CLB.CLB_LOAN_MONEY, 2) AS CLB_LOAN_MONEY,       
       (SELECT NVL(SUM(CLA.CLA_MONEY), 0) FROM CMS_LOAN_ABATE CLA WHERE CLB.CLB_ID = CLA.CLB_ID) AS CLA_MONEY,       
       ROUND(NVL(CLB.CLB_BALANCE, 0), 2) AS CLB_BALANCE,
       ROUND(NVL(CLB.CLB_FIXED_RATE, 0), 6) AS CLB_FIXED_RATE,
       ROUND(NVL(CLB.CLB_AGREEMENT_RATE, 0), 6) AS CLB_AGREEMENT_RATE,          
       (SELECT NVL(SUM(CRL.CRL_MONEY), 0) FROM CMS_REPAY_LOAN CRL WHERE CLB.CLB_ID = CRL.CLB_ID) AS CRL_MONEY,       
       (SELECT NVL(SUM(CBI.FIX_FEE_REAL), 0) FROM CMS_BILLING CBI WHERE CLB.CLB_ID = CBI.CLB_ID) AS FIX_FEE_REAL,
       (SELECT NVL(SUM(CBI.AGREEMENT_FEE_REAL), 0) FROM CMS_BILLING CBI WHERE CLB.CLB_ID = CBI.CLB_ID) AS AGREEMENT_FEE_REAL,       
       (SELECT NVL(SUM(CRL.CRL_FIXED_MONEY), 0) FROM CMS_REPAY_LOAN CRL WHERE CLB.CLB_ID = CRL.CLB_ID) AS CRL_FIXED_MONEY,
       (SELECT NVL(SUM(CRL.CRL_AGREEMENT_MONEY), 0) FROM CMS_REPAY_LOAN CRL WHERE CLB.CLB_ID = CRL.CLB_ID) AS CRL_AGREEMENT_MONEY,              
       (SELECT NVL(SUM(CPR.CPR_FIXED_MONEY), 0) FROM CMS_PAYMENT_RECORDS CPR WHERE CLB.CLB_ID = CPR.CLB_ID) AS CPR_FIXED_MONEY,
       (SELECT NVL(SUM(CPR.CPR_AGREEMENT_MONEY), 0) FROM CMS_PAYMENT_RECORDS CPR WHERE CLB.CLB_ID = CPR.CLB_ID) AS CPR_AGREEMENT_MONEY,       
       CLB.CLB_START_DATE,
       CLB.CLB_END_DATE,
       CLB.CLB_STATUS
  FROM CMS_LOAN_BILL CLB
 INNER JOIN BT_CORP BL ON CLB.CLB_LOAN_CORP_ID = BL.ID
 INNER JOIN BT_CORP BB ON CLB.CLB_BORROW_CORP_ID = BB.ID;
 
/*==============================================================*/
/* Table: V_CMS_ACCOUNTINGFEE                                   */
/*==============================================================*/
CREATE OR REPLACE VIEW V_CMS_BILLING AS
SELECT CLB.CLB_ID,
       CLB.CLB_NO,
       CLB.CLB_LOAN_CORP_ID AS BL_CORP_ID,
       BL.CORP_CODE AS BL_CORP_CODE,
       BL.CORP_NAME AS BL_CORP_NAME,
       CLB.CLB_BORROW_CORP_ID AS BB_CORP_ID,
       BB.CORP_CODE AS BB_CORP_CODE,
       BB.CORP_NAME AS BB_CORP_NAME,
       ROUND(CLB.CLB_LOAN_MONEY, 2) AS CLB_LOAN_MONEY,
       ROUND(NVL(SUM(CLA.CLA_MONEY), 0), 2) AS CLA_MONEY,
       ROUND(CLB.CLB_BALANCE, 2) AS CLB_BALANCE,
       ROUND(CLB.CLB_FIXED_RATE, 6) AS CLB_FIXED_RATE,
       ROUND(CLB.CLB_AGREEMENT_RATE, 6) AS CLB_AGREEMENT_RATE,
       CLB.CLB_START_DATE,
       CLB.CLB_END_DATE,
       CLB.CLB_LAST_BILLING_DATE
FROM CMS_LOAN_BILL CLB
LEFT JOIN CMS_LOAN_ABATE CLA ON CLB.CLB_ID = CLA.CLB_ID
INNER JOIN BT_CORP BL ON CLB.CLB_LOAN_CORP_ID = BL.ID
INNER JOIN BT_CORP BB ON CLB.CLB_BORROW_CORP_ID = BB.ID
WHERE CLB.CLB_STATUS=95
GROUP BY CLB.CLB_NO,CLB.CLB_LOAN_CORP_ID,BL.CORP_CODE,
        BL.CORP_NAME,CLB.CLB_BORROW_CORP_ID,BB.CORP_CODE,BB.CORP_NAME,
        CLB.CLB_LOAN_MONEY,CLB.CLB_BALANCE,CLB.CLB_FIXED_RATE,CLB.CLB_LAST_BILLING_DATE,
        CLB.CLB_AGREEMENT_RATE,CLB.CLB_START_DATE,CLB.CLB_END_DATE,CLB.CLB_ID;
CREATE OR REPLACE VIEW V_CMS_ACCOUNTINGFEE AS
SELECT CLB.CLB_ID,
       CLB.CLB_NO,
       CLB.CLB_LOAN_CORP_ID AS BL_CORP_ID,
       BL.CORP_CODE AS BL_CORP_CODE,
       BL.CORP_NAME AS BL_CORP_NAME,
       CLB.CLB_BORROW_CORP_ID AS BB_CORP_ID,
       BB.CORP_CODE AS BB_CORP_CODE,
       BB.CORP_NAME AS BB_CORP_NAME,
       ROUND(CLB.CLB_LOAN_MONEY, 2) AS CLB_LOAN_MONEY,
       ROUND(NVL(SUM(CLA.CLA_MONEY), 0), 2) AS CLA_MONEY,
       ROUND(CB.CLB_BALANCE, 2) AS CLB_BALANCE,
       ROUND(CLB.CLB_FIXED_RATE, 6) AS CLB_FIXED_RATE,
       ROUND(CLB.CLB_AGREEMENT_RATE, 6) AS CLB_AGREEMENT_RATE,
       CLB.CLB_START_DATE,
       CLB.CLB_END_DATE,
       CB.Notice_Num,
       CB.FIX_FEE,
       CB.FIX_FEE_REAL,
       CB.AGREEMENT_FEE,
       CB.AGREEMENT_FEE_REAL,
       CB.BILLING_ID,
       CB.MAKER,
       CB.AUDITOR,
       BU.USER_NAME AS MAKER_NAME,
       BU2.USER_NAME AS AUDITOR_NAME,
       CB.STATUS
FROM CMS_LOAN_BILL CLB
LEFT  JOIN CMS_LOAN_ABATE CLA ON CLB.CLB_ID = CLA.CLB_ID
INNER JOIN BT_CORP BL ON CLB.CLB_LOAN_CORP_ID = BL.ID
INNER JOIN BT_CORP BB ON CLB.CLB_BORROW_CORP_ID = BB.ID
INNER JOIN CMS_BILLING CB ON CLB.CLB_ID = CB.CLB_ID
LEFT  JOIN BT_USER BU ON CB.MAKER=BU.USER_CODE
LEFT  JOIN BT_USER BU2 ON CB.AUDITOR=BU2.USER_CODE
WHERE CLB.CLB_STATUS=95 AND CB.STATUS <> -12
GROUP BY CLB.CLB_ID,
         CLB.CLB_NO,
         CLB.CLB_LOAN_CORP_ID,
         BL.CORP_CODE,
         BL.CORP_NAME,
         CLB.CLB_BORROW_CORP_ID,
         BB.CORP_CODE,
         BB.CORP_NAME,
         CLB.CLB_LOAN_MONEY,
         CB.CLB_BALANCE,
         CLB.CLB_FIXED_RATE,
         CLB.CLB_AGREEMENT_RATE,
         CLB.CLB_START_DATE,
         CLB.CLB_END_DATE,
         CB.Notice_Num,
         CB.FIX_FEE,
         CB.FIX_FEE_REAL,
         CB.AGREEMENT_FEE,
         CB.AGREEMENT_FEE_REAL,
         BU.USER_NAME,
         BU2.USER_NAME,
         CB.MAKER,
         CB.AUDITOR,
         CB.BILLING_ID,
         CB.STATUS;
CREATE OR REPLACE VIEW V_CMS_ABATE_VIEW AS
SELECT CLA.CLA_ID,  --减免单号
       CLB.CLB_NO, --贷款单号
       CLB.CLB_ID, --台账id
       CLB.CLB_LOAN_CORP_ID AS BL_CORP_ID,
       BL.CORP_NAME AS BL_CORP_NAME,
       CLB.CLB_BORROW_CORP_ID AS BB_CORP_ID,
       BB.CORP_NAME AS BB_CORP_NAME,
       ROUND(NVL(CLA.CLA_MONEY,0), 2) AS CLA_MONEY, --本金
       ROUND(NVL(CLA.CLA_FIXED_MONEY, 0), 2)AS CLA_FIXED_MONEY, --固定占用费
       ROUND(NVL(CLA.CLA_AGREEMENT_MONEY,0), 2) AS CLA_AGREEMENT_MONEY,  -- 协定占用费
       ROUND(NVL(CLB.CLB_LOAN_MONEY,0), 2) AS CLB_LOAN_MONEY,  --贷款本金
       ROUND(NVL(CLB.CLB_BALANCE,0), 2) AS CLB_BALANCE,   --当前余额
       ROUND(NVL(CLA.CLA_MONEY,0)*10000+NVL(CLA.CLA_FIXED_MONEY, 0)+NVL(CLA.CLA_AGREEMENT_MONEY,0), 2) ABATEMONEY,
       CLA.CLA_DATE,
       CLA.CLA_DESC,
       CLA.CLA_STATUS,
       CLA.CLA_NO,
       CLA.USER_ID,
       CLA.NEXTCHECKER
  FROM CMS_LOAN_ABATE CLA
 INNER JOIN CMS_LOAN_BILL CLB ON CLB.CLB_ID = CLA.CLB_ID
 INNER JOIN BT_CORP BL ON CLB.CLB_LOAN_CORP_ID = BL.ID
 INNER JOIN BT_CORP BB ON CLB.CLB_BORROW_CORP_ID = BB.ID
 GROUP BY CLA.CLA_ID,
          CLB.CLB_NO,
          CLB.CLB_ID,
          CLB.CLB_LOAN_CORP_ID,
          BL.CORP_NAME,
          CLB.CLB_BORROW_CORP_ID,
          BB.CORP_NAME,
          CLA.CLA_MONEY,
          CLA.CLA_FIXED_MONEY,
          CLA.CLA_AGREEMENT_MONEY,
          CLB.CLB_LOAN_MONEY,
          CLB.CLB_BALANCE,
          CLA.CLA_DATE,
          CLA.CLA_DESC,
          CLA.CLA_STATUS,
          CLA.CLA_NO,
          CLA.USER_ID,
          CLA.NEXTCHECKER;
          
CREATE OR REPLACE VIEW V_CMS_REPAY_VIEW AS
SELECT CRL.CRL_ID,  --还款单号
       CLB.CLB_NO, --贷款单号
       CLB.CLB_ID, --台账id
       CLB.CLB_LOAN_CORP_ID AS BL_CORP_ID,
       BL.CORP_NAME AS BL_CORP_NAME,
       CLB.CLB_BORROW_CORP_ID AS BB_CORP_ID,
       BB.CORP_NAME AS BB_CORP_NAME,
       ROUND(NVL(CRL.CRL_MONEY,0), 2) AS CRL_MONEY, --本金
       ROUND(NVL(CRL.CRL_FIXED_MONEY, 0), 2) AS CRL_FIXED_MONEY, --固定占用费
       ROUND(NVL(CRL.CRL_AGREEMENT_MONEY,0), 2) AS CRL_AGREEMENT_MONEY,  -- 协定占用费
       ROUND(NVL(CLB.CLB_LOAN_MONEY,0), 2) AS CLB_LOAN_MONEY,  --贷款本金
       ROUND(NVL(CLB.CLB_BALANCE,0), 2) AS CLB_BALANCE,   --当前余额
       ROUND(NVL(CRL.CRL_MONEY,0)+NVL(CRL.CRL_FIXED_MONEY, 0)+NVL(CRL.CRL_AGREEMENT_MONEY,0), 2) REPAYMONEY,
       CRL.CRL_DATE,
       CRL.CRL_DESC,
       CRL.CRL_STATUS,
       CRL.CRL_NO,
       CRL.USER_ID,
       CRL.NEXTCHECKER
  FROM CMS_REPAY_LOAN CRL
 INNER JOIN CMS_LOAN_BILL CLB ON CLB.CLB_ID = CRL.CLB_ID
 INNER JOIN BT_CORP BL ON CLB.CLB_LOAN_CORP_ID = BL.ID
 INNER JOIN BT_CORP BB ON CLB.CLB_BORROW_CORP_ID = BB.ID
 GROUP BY CRL.CRL_ID,
          CLB.CLB_NO,
          CLB.CLB_ID,
          CLB.CLB_LOAN_CORP_ID,
          BL.CORP_NAME,
          CLB.CLB_BORROW_CORP_ID,
          BB.CORP_NAME,
          CRL.CRL_MONEY,
          CRL.CRL_FIXED_MONEY,
          CRL.CRL_AGREEMENT_MONEY,
          CLB.CLB_LOAN_MONEY,
          CLB.CLB_BALANCE,
          CRL.CRL_DATE,
          CRL.CRL_DESC,
          CRL.CRL_STATUS,
          CRL.CRL_NO,
          CRL.USER_ID,
          CRL.NEXTCHECKER;

CREATE OR REPLACE VIEW V_CMS_PAYMENT_RECORD AS
SELECT CPR.CPR_ID,
       CPR.CPR_NO,
       CLB.CLB_ID, 
       CLB.CLB_NO,
       CLB.CLB_LOAN_CORP_ID AS BL_CORP_ID,
       BL.CORP_CODE AS BL_CORP_CODE,
       BL.CORP_NAME AS BL_CORP_NAME,
       CLB.CLB_BORROW_CORP_ID AS BB_CORP_ID,
       BB.CORP_CODE AS BB_CORP_CODE,
       BB.CORP_NAME AS BB_CORP_NAME,
       ROUND(CPR.CPR_MONEY * 10000, 2) AS CPR_MONEY,
       ROUND(CPR.CPR_FIXED_MONEY, 2) AS CPR_FIXED_MONEY,
       ROUND(CPR.CPR_AGREEMENT_MONEY, 2) AS CPR_AGREEMENT_MONEY,
       ROUND(CPR.CPR_MONEY * 10000 + CPR.CPR_FIXED_MONEY + CPR.CPR_AGREEMENT_MONEY, 2) AS CPR_TOTAL_MONEY,
       CPR.CPR_PAYMENT_DATE,
       CPR.CPR_DESC,
       CPR.CPR_STATUS
  FROM CMS_PAYMENT_RECORDS CPR
 JOIN CMS_LOAN_BILL CLB ON CLB.CLB_ID = CPR.CLB_ID
 JOIN BT_CORP BL ON CLB.CLB_LOAN_CORP_ID = BL.ID
 JOIN BT_CORP BB ON CLB.CLB_BORROW_CORP_ID = BB.ID
 GROUP BY CPR.CPR_ID,
          CPR.CPR_NO,
          CLB.CLB_ID,
          CLB.CLB_NO,
          CLB.CLB_LOAN_CORP_ID,
          BL.CORP_CODE,
          BL.CORP_NAME,
          CLB.CLB_BORROW_CORP_ID,
          BB.CORP_CODE,
          BB.CORP_NAME,
          CPR.CPR_MONEY,
          CPR.CPR_FIXED_MONEY,
          CPR.CPR_AGREEMENT_MONEY,
          CLB.CLB_AGREEMENT_RATE,
          CPR.CPR_PAYMENT_DATE,
          CPR.CPR_DESC,
          CPR.CPR_STATUS;