ALTER VIEW V_CMS_LOAN_BILL AS
SELECT CLI.CORP_ID,
       BC.CORP_CODE,
       BC.CORP_NAME,
       CLI.STATUS AS LOAN_STATE,
       CLI.LOAN_GENRE,
       CONVERT(CHAR(20), CLI.LOAN_DATE, 120) AS LOAN_DATE,
       SUM(ISNULL(CLI.LOAN_MONEY, 0)) AS CONTRACT_SUM,
       SUM(CASE WHEN DATEPART(YEAR, LSOI.LOAN_SEND_OUT_DATE) = DATEPART(YEAR, GETDATE()) THEN LSOI.LOAN_SEND_OUT_MONEY ELSE 0 END) AS LOAN_SUM,
       SUM(ISNULL(LSOI.LOAN_SEND_OUT_MONEY, 0)) AS LOAN_SUM_ALL,       
       SUM(CASE WHEN DATEPART(YEAR, CLR.REPAY_DATE) = DATEPART(YEAR, GETDATE()) AND CLR.STATUS >= 95 THEN CLR.REPAY_MONEY ELSE 0 END) AS REPAY_SUM,
       SUM(CASE WHEN CLR.STATUS >= 95 THEN CLR.REPAY_MONEY ELSE 0 END) AS REPAY_SUM_ALL,
       SUM(ISNULL(LSOI.LOAN_SEND_OUT_MONEY, 0)) AS LOAN_MONEY,
       (SUM(ISNULL(CLI.LOAN_MONEY, 0)) - SUM((CASE WHEN CLR.STATUS >= 95 THEN CLR.REPAY_MONEY ELSE 0 END))) AS LOAN_MONEY_LAST
FROM CMS_LOAN_INFO CLI
LEFT JOIN LOAN_SEND_OUT_INFO LSOI ON CLI.BILL_CODE = LSOI.FATHER_CODE
LEFT JOIN CMS_CONTRACT CCT ON LSOI.BILL_CODE = CCT.LI_CODE
LEFT JOIN CMS_LOAN_REPAY CLR ON CLR.LI_CODE = LSOI.BILL_CODE
LEFT JOIN BT_CORP BC ON CLI.CORP_ID = BC.ID
WHERE CLI.STATUS >= 95
GROUP BY CLI.CORP_ID, BC.CORP_CODE, BC.CORP_NAME, CLI.LOAN_DATE, CLI.STATUS, CLI.LOAN_GENRE;