--修改日期：20120920
--修改人：高枫 
--修改内容：XD-JD03-027 系统功能-贷款还款
--修改内容：系统菜单 增加 贷款台账还款
--参数设置：
INSERT INTO BT_SYS_RES (RES_CODE, RES_NAME, SYS_CODE, FATHER_CODE, RES_URL, FUNC_FLAG, RES_TYPE, LINK_TARGET, STATUS, RES_ORDER, RMK, REVERSE1, REVERSE2, REVERSE3, REVERSE4, REVERSE5, REVERSE6, REVERSE7, REVERSE8, REVERSE9, REVERSE10, RES_LEVEL, RES_ROLE)
SELECT (SELECT MAX(T1.RES_CODE) + 1 FROM BT_SYS_RES T1), '贷款还款台账', 'cms', RES_CODE, '/cms/cmsLoanRepay.do?method=initQuery', '0', '1', '0', '0', (SELECT MAX(T2.RES_ORDER)+1 FROM BT_SYS_RES T2 WHERE T2.FATHER_CODE = T3.RES_CODE AND T2.SYS_CODE = 'cms'), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, '' FROM BT_SYS_RES T3 WHERE T3.RES_NAME = '贷款管理' AND T3.SYS_CODE = 'cms';
COMMIT;

CREATE OR REPLACE VIEW V_CMS_REPAY_VIEW AS
SELECT CRL.CRL_ID,  --还款单号
       CLB.CLB_NO, --贷款单号
       CLB.CLB_ID, --台账id
       CLB.CLB_LOAN_CORP_ID AS BL_CORP_ID,
       BL.CORP_NAME AS BL_CORP_NAME,
       CLB.CLB_BORROW_CORP_ID AS BB_CORP_ID,
       BB.CORP_NAME AS BB_CORP_NAME,
       ROUND(NVL(CRL.CRL_MONEY,0), 2) AS CRL_MONEY, --本金
       ROUND(NVL(CRL.CRL_FIXED_MONEY, 0), 2) AS CRL_FIXED_MONEY, --固定占用费
       ROUND(NVL(CRL.CRL_AGREEMENT_MONEY,0), 2) AS CRL_AGREEMENT_MONEY,  -- 协定占用费
       ROUND(NVL(CLB.CLB_LOAN_MONEY,0), 2) AS CLB_LOAN_MONEY,  --贷款本金
       ROUND(NVL(CLB.CLB_BALANCE,0), 2) AS CLB_BALANCE,   --当前余额
       ROUND(NVL(CRL.CRL_MONEY,0)+NVL(CRL.CRL_FIXED_MONEY, 0)+NVL(CRL.CRL_AGREEMENT_MONEY,0), 2) REPAYMONEY,
       CRL.CRL_DATE,
       CRL.CRL_DESC,
       CRL.CRL_STATUS,
       CRL.CRL_NO,
       CRL.USER_ID,
       CRL.NEXTCHECKER
  FROM CMS_REPAY_LOAN CRL
 INNER JOIN CMS_LOAN_BILL CLB ON CLB.CLB_ID = CRL.CLB_ID
 INNER JOIN BT_CORP BL ON CLB.CLB_LOAN_CORP_ID = BL.ID
 INNER JOIN BT_CORP BB ON CLB.CLB_BORROW_CORP_ID = BB.ID
 GROUP BY CRL.CRL_ID,
          CLB.CLB_NO,
          CLB.CLB_ID,
          CLB.CLB_LOAN_CORP_ID,
          BL.CORP_NAME,
          CLB.CLB_BORROW_CORP_ID,
          BB.CORP_NAME,
          CRL.CRL_MONEY,
          CRL.CRL_FIXED_MONEY,
          CRL.CRL_AGREEMENT_MONEY,
          CLB.CLB_LOAN_MONEY,
          CLB.CLB_BALANCE,
          CRL.CRL_DATE,
          CRL.CRL_DESC,
          CRL.CRL_STATUS,
          CRL.CRL_NO,
          CRL.USER_ID,
          CRL.NEXTCHECKER;       