--修改日期：20120920
--修改人：高枫
--修改内容：XD-JD03-028 系统功能-贷款减免
--修改内容：系统菜单 增加 贷款减免
--参数设置：
INSERT INTO BT_SYS_RES (RES_CODE, RES_NAME, SYS_CODE, FATHER_CODE, RES_URL, FUNC_FLAG, RES_TYPE, LINK_TARGET, STATUS, RES_ORDER, RMK, REVERSE1, REVERSE2, REVERSE3, REVERSE4, REVERSE5, REVERSE6, REVERSE7, REVERSE8, REVERSE9, REVERSE10, RES_LEVEL, RES_ROLE)
SELECT (SELECT MAX(T1.RES_CODE) + 1 FROM BT_SYS_RES T1), '贷款减免', 'cms', RES_CODE, '/cms/cmsLoanAnnul.do?method=initQuery', '0', '1', '0', '0', (SELECT MAX(T2.RES_ORDER)+1 FROM BT_SYS_RES T2 WHERE T2.FATHER_CODE = T3.RES_CODE AND T2.SYS_CODE = 'cms'), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, '' FROM BT_SYS_RES T3 WHERE T3.RES_NAME = '贷款管理' AND T3.SYS_CODE = 'cms';
go

--alter table CMS_LOAN_ABATE add CLA_NO varchar(100);
--go

CREATE OR REPLACE VIEW V_CMS_ABATE_VIEW AS
SELECT CLA.CLA_ID,  --减免单号
       CLB.CLB_NO, --贷款单号
       CLB.CLB_ID, --台账id
       CLB.CLB_LOAN_CORP_ID AS BL_CORP_ID,
       BL.CORP_NAME AS BL_CORP_NAME,
       CLB.CLB_BORROW_CORP_ID AS BB_CORP_ID,
       BB.CORP_NAME AS BB_CORP_NAME,
       CONVERT(MONEY, ROUND(CLA.CLA_MONEY, 2), 120) AS CRL_MONEY, --本金
       CONVERT(MONEY, ROUND(CLA.CLA_FIXED_MONEY, 2), 120) AS CLA_FIXED_MONEY, --固定占用费
       CONVERT(MONEY, ROUND(CLA.CLA_AGREEMENT_MONEY, 2), 120) AS CLA_AGREEMENT_MONEY, -- 协定占用费
       CONVERT(MONEY, ROUND(CLB.CLB_LOAN_MONEY, 2), 120) AS CLB_LOAN_MONEY, --贷款本金
       CONVERT(MONEY, ROUND(CLB.CLB_BALANCE, 2), 120) AS CLB_BALANCE, --当前余额
       CONVERT(MONEY, ROUND(CLA.CLA_MONEY*10000+CLA.CLA_FIXED_MONEY+CLA.CLA_AGREEMENT_MONEY, 2), 120) AS ABATEMONEY, 
       CLA.CLA_DATE,
       CLA.CLA_DESC,
       CLA.CLA_STATUS,
       CLA.CLA_NO,
       CLA.USER_ID,
       CLA.NEXTCHECKER
  FROM CMS_LOAN_ABATE CLA
 INNER JOIN CMS_LOAN_BILL CLB ON CLB.CLB_ID = CLA.CLB_ID
 INNER JOIN BT_CORP BL ON CLB.CLB_LOAN_CORP_ID = BL.ID
 INNER JOIN BT_CORP BB ON CLB.CLB_BORROW_CORP_ID = BB.ID
 GROUP BY CLA.CLA_ID,
          CLB.CLB_NO,
          CLB.CLB_ID,
          CLB.CLB_LOAN_CORP_ID,
          BL.CORP_NAME,
          CLB.CLB_BORROW_CORP_ID,
          BB.CORP_NAME,
          CLA.CLA_MONEY,
          CLA.CLA_FIXED_MONEY,
          CLA.CLA_AGREEMENT_MONEY,
          CLB.CLB_LOAN_MONEY,
          CLB.CLB_BALANCE,
          CLA.CLA_DATE,
          CLA.CLA_DESC,
          CLA.CLA_STATUS,
          CLA.CLA_NO,
          CLA.USER_ID,
          CLA.NEXTCHECKER;
      
alter table CMS_REPAY_LOAN add BILL_BLANCE  NUMERIC(15,2);
go
          
