--修改日期：20120918
--修改人：叶爱军
--需求编号：XD-JD03-027 系统功能-贷款台账
--修改内容：系统菜单 增加 贷款台账
--参数设置：
INSERT INTO BT_SYS_RES (RES_CODE, RES_NAME, SYS_CODE, FATHER_CODE, RES_URL, FUNC_FLAG, RES_TYPE, LINK_TARGET, STATUS, RES_ORDER, RMK, REVERSE1, REVERSE2, REVERSE3, REVERSE4, REVERSE5, REVERSE6, REVERSE7, REVERSE8, REVERSE9, REVERSE10, RES_LEVEL, RES_ROLE)
SELECT (SELECT MAX(T1.RES_CODE) + 1 FROM BT_SYS_RES T1), '贷款台账', 'cms', RES_CODE, '/cms/cmsLoanBill.do?method=toList', '0', '0', '0', '0', (SELECT MAX(T2.RES_ORDER)+1 FROM BT_SYS_RES T2 WHERE T2.FATHER_CODE = T3.RES_CODE AND T2.SYS_CODE = 'cms'), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, '' FROM BT_SYS_RES T3 WHERE T3.RES_NAME = '贷款管理' AND T3.SYS_CODE = 'cms';
GO
--修改日期：20120918
--修改人：余川锋
--需求编号：XD-JD03-029 
--修改内容：系统菜单 增加资金占用费
insert into bt_sys_res (RES_CODE, RES_NAME, SYS_CODE, FATHER_CODE, RES_URL, FUNC_FLAG, RES_TYPE, LINK_TARGET, STATUS, RES_ORDER, RMK, REVERSE1, REVERSE2, REVERSE3, REVERSE4, REVERSE5, REVERSE6, REVERSE7, REVERSE8, REVERSE9, REVERSE10, RES_LEVEL, RES_ROLE)
values ((select max(res_code) + 1 from bt_sys_res), '资金占用费', 'cms', (select res_code from bt_sys_res  where res_name='贷款管理'), '', '0', '1', '0', '0', (select max(t.res_order)+1 from bt_sys_res t  where t.father_code=(select res_code from bt_sys_res  where res_name='贷款管理')), '资金占用费', '', '', '', '', '', null, null, null, null, null, 2, '')
GO
insert into bt_sys_res (RES_CODE, RES_NAME, SYS_CODE, FATHER_CODE, RES_URL, FUNC_FLAG, RES_TYPE, LINK_TARGET, STATUS, RES_ORDER, RMK, REVERSE1, REVERSE2, REVERSE3, REVERSE4, REVERSE5, REVERSE6, REVERSE7, REVERSE8, REVERSE9, REVERSE10, RES_LEVEL, RES_ROLE)
values ((select max(res_code) + 1 from bt_sys_res), '计费', 'cms', (select res_code from bt_sys_res  where res_name='资金占用费' and res_level=2), '/cms/billing.do?method=toList', '0', '1', '0', '0', 1, '证劵资金账号维护', '', '', '', '', '', null, null, null, null, null, 3, '')
GO

--修改日期：20120928
--修改人：叶爱军 
--需求编号：XD-JD03-030 系统功能-缴费记录
--修改内容：系统菜单 增加 缴费记录
--参数设置：
INSERT INTO BT_SYS_RES (RES_CODE, RES_NAME, SYS_CODE, FATHER_CODE, RES_URL, FUNC_FLAG, RES_TYPE, LINK_TARGET, STATUS, RES_ORDER, RMK, REVERSE1, REVERSE2, REVERSE3, REVERSE4, REVERSE5, REVERSE6, REVERSE7, REVERSE8, REVERSE9, REVERSE10, RES_LEVEL, RES_ROLE)
SELECT (SELECT MAX(T1.RES_CODE) + 1 FROM BT_SYS_RES T1), '缴费记录', 'cms', RES_CODE, '/cms/cmsPaymentRecord.do?method=toList', '0', '0', '0', '0', (SELECT MAX(T2.RES_ORDER)+1 FROM BT_SYS_RES T2 WHERE T2.FATHER_CODE = T3.RES_CODE AND T2.SYS_CODE = 'cms'), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, '' FROM BT_SYS_RES T3 WHERE T3.RES_NAME = '资金占用费' AND T3.SYS_CODE = 'cms';
GO
--修改日期：20120920
--修改人：高枫
--修改内容：XD-JD03-028 系统功能-贷款减免
--修改内容：系统菜单 增加 贷款减免
--参数设置：
INSERT INTO BT_SYS_RES (RES_CODE, RES_NAME, SYS_CODE, FATHER_CODE, RES_URL, FUNC_FLAG, RES_TYPE, LINK_TARGET, STATUS, RES_ORDER, RMK, REVERSE1, REVERSE2, REVERSE3, REVERSE4, REVERSE5, REVERSE6, REVERSE7, REVERSE8, REVERSE9, REVERSE10, RES_LEVEL, RES_ROLE)
SELECT (SELECT MAX(T1.RES_CODE) + 1 FROM BT_SYS_RES T1), '贷款减免', 'cms', RES_CODE, '/cms/cmsLoanAnnul.do?method=initQuery', '0', '1', '0', '0', (SELECT MAX(T2.RES_ORDER)+1 FROM BT_SYS_RES T2 WHERE T2.FATHER_CODE = T3.RES_CODE AND T2.SYS_CODE = 'cms'), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, '' FROM BT_SYS_RES T3 WHERE T3.RES_NAME = '贷款管理' AND T3.SYS_CODE = 'cms';
go

--修改日期：20120920
--修改人：高枫 
--修改内容：XD-JD03-027 系统功能-贷款还款
--修改内容：系统菜单 增加 贷款台账还款
--参数设置：
INSERT INTO BT_SYS_RES (RES_CODE, RES_NAME, SYS_CODE, FATHER_CODE, RES_URL, FUNC_FLAG, RES_TYPE, LINK_TARGET, STATUS, RES_ORDER, RMK, REVERSE1, REVERSE2, REVERSE3, REVERSE4, REVERSE5, REVERSE6, REVERSE7, REVERSE8, REVERSE9, REVERSE10, RES_LEVEL, RES_ROLE)
SELECT (SELECT MAX(T1.RES_CODE) + 1 FROM BT_SYS_RES T1), '贷款还款台账', 'cms', RES_CODE, '/cms/cmsLoanRepay.do?method=initQuery', '0', '1', '0', '0', (SELECT MAX(T2.RES_ORDER)+1 FROM BT_SYS_RES T2 WHERE T2.FATHER_CODE = T3.RES_CODE AND T2.SYS_CODE = 'cms'), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, '' FROM BT_SYS_RES T3 WHERE T3.RES_NAME = '贷款管理' AND T3.SYS_CODE = 'cms';
GO

--修改日期：20120921
--修改人：叶爱军
--修改内容：XD-JD03-027 系统功能-贷款台账
--修改内容：担保方式 1,增加 组合担保，其它;2,修改TYPE_NAME;
--参数设置：
UPDATE CMS_PROVIDE_LOAN_TYPE SET TYPE_NAME = '信用/免担保贷款' WHERE TYPE_CODE = '01' AND OPERATION_TYPE = 'A';
UPDATE CMS_PROVIDE_LOAN_TYPE SET TYPE_NAME = '保证贷款' WHERE TYPE_CODE = '02' AND OPERATION_TYPE = 'A';
UPDATE CMS_PROVIDE_LOAN_TYPE SET TYPE_NAME = '抵押贷款' WHERE TYPE_CODE = '03' AND OPERATION_TYPE = 'A';
UPDATE CMS_PROVIDE_LOAN_TYPE SET TYPE_NAME = '质押贷款' WHERE TYPE_CODE = '04' AND OPERATION_TYPE = 'A';
INSERT INTO CMS_PROVIDE_LOAN_TYPE (TYPE_CODE, TYPE_NAME, OPERATION_TYPE) VALUES ('05', '组合担保', 'A');
INSERT INTO CMS_PROVIDE_LOAN_TYPE (TYPE_CODE, TYPE_NAME, OPERATION_TYPE) VALUES ('06', '其他', 'A');
GO

CREATE TABLE CMS_LOAN_ABATE (
   CLA_ID               VARCHAR(32)          NOT NULL,
   CLB_ID               VARCHAR(32)          NULL,
   NEXTCHECKER          VARCHAR(200)         NULL,
   APPROVES             VARCHAR(200)         NULL,
   CORP_ID              VARCHAR(32)          NULL,
   USER_ID              VARCHAR(32)          NULL,
   CLA_NO               VARCHAR(14)          NULL,
   CLA_CREATE_TIME      DATETIME             NULL,
   CLA_DATE             DATETIME             NULL,
   CLA_MONEY            NUMERIC(15,2)        NULL,
   CLA_STATUS           NUMERIC(10)          NULL,
   CLA_FIXED_MONEY      NUMERIC(15,2)        NULL,
   CLA_AGREEMENT_MONEY  NUMERIC(15,2)        NULL,
   CLA_MEMO             VARCHAR(1000)        NULL,
   CLA_DESC             VARCHAR(2000)        NULL,
   CONSTRAINT PK_CMS_LOAN_ABATE PRIMARY KEY NONCLUSTERED (CLA_ID)
)
GO

CREATE TABLE CMS_LOAN_BILL (
   CLB_ID               VARCHAR(32)          NOT NULL,
   NEXTCHECKER          VARCHAR(200)         NULL,
   APPROVES             VARCHAR(200)         NULL,
   CORP_ID              VARCHAR(32)          NULL,
   USER_ID              VARCHAR(32)          NULL,
   CLB_NO               VARCHAR(14)          NULL,
   CLB_CREATE_TIME      DATETIME             NULL,
   CLB_LOAN_CORP_ID     VARCHAR(4)           NULL,
   CLB_BORROW_CORP_ID   VARCHAR(4)           NULL,
   CLB_LOAN_MONEY       NUMERIC(15,2)        NULL,
   CLB_BALANCE          NUMERIC(15,2)        NULL,
   CLB_START_DATE       DATETIME             NULL,
   CLB_END_DATE         DATETIME             NULL,
   CLB_FIXED_RATE       NUMERIC(9,6)         NULL,
   CLB_AGREEMENT_RATE   NUMERIC(9,6)         NULL,
   CLB_ITEM_CODE        VARCHAR(20)          NULL,
   CLB_REPAY_TYPE       VARCHAR(2)           NULL,
   CLB_CONTRACT_TERM    NUMERIC              NULL,
   CLB_LOAN_TYPE        VARCHAR(2)           NULL,
   CLB_CURRENCY         VARCHAR(2)           NULL,
   CLB_LOAN_TERM        NUMERIC              NULL,
   CLB_STATUS           NUMERIC(10)          NULL,
   CLB_GUARANTEE        NUMERIC(15,2)        NULL,
   CLB_GUA_MEMO         VARCHAR(2000)        NULL,
   CLB_LOAN_MEMO        VARCHAR(2000)        NULL,
   CLB_MEMO             VARCHAR(1000)        NULL,
   CLB_FILE             VARCHAR(1000)        NULL,
   CLB_LAST_BILLING_DATE DATETIME            NULL,
   CONSTRAINT PK_CMS_LOAN_BILL PRIMARY KEY NONCLUSTERED (CLB_ID)
)
GO

CREATE TABLE CMS_PAYMENT_RECORDS (
   CPR_ID               VARCHAR(32)          NOT NULL,
   CLB_ID               VARCHAR(32)          NULL,
   CORP_ID              VARCHAR(32)          NULL,
   USER_ID              VARCHAR(32)          NULL,
   NEXTCHECKER          VARCHAR(200)         NULL,
   APPROVES             VARCHAR(200)         NULL,
   CPR_NO               VARCHAR(14)          NULL,
   CPR_MONEY            NUMERIC(15,2)        NULL,
   CPR_FIXED_MONEY      NUMERIC(15,2)        NULL,
   CPR_AGREEMENT_MONEY  NUMERIC(15,2)        NULL,
   CPR_CREATE_TIME      DATETIME             NULL,
   CPR_PAYMENT_DATE     DATETIME             NULL,
   CPR_STATUS           NUMERIC(10)          NULL,
   CPR_DESC             VARCHAR(2000)        NULL,
   CONSTRAINT PK_CMS_PAYMENT_RECORDS PRIMARY KEY NONCLUSTERED (CPR_ID)
)
GO
CREATE TABLE CMS_BILLING (
   BILLING_ID           VARCHAR(32)          NOT NULL,
   FIX_FEE              NUMERIC(15,2)        NULL,
   AGREEMENT_FEE        NUMERIC(15,2)        NULL,
   FIXED_RATE           NUMERIC(9,6)         NULL,
   AGREEMENT_RATE       NUMERIC(9,6)         NULL,
   FEE_DATE             DATETIME             NULL,
   STATUS               NUMERIC(10)          NULL,
   CLB_ID               VARCHAR(32)          NULL,
   CLB_BALANCE          NUMERIC(15,2)        NULL,
   FEE_START_DATE       DATETIME             NULL,
   FEE_END_DATE         DATETIME             NULL,
   NOTICE_NUM           VARCHAR(32)          NULL,
   FIX_FEE_REAL         NUMERIC(15,2)        NULL,
   AGREEMENT_FEE_REAL   NUMERIC(15,2)        NULL,
   MAKER                VARCHAR(16)          NULL,
   AUDITOR              VARCHAR(16)          NULL,
   CONSTRAINT PK_CMS_BILLING PRIMARY KEY NONCLUSTERED (BILLING_ID)
)
go
CREATE TABLE CMS_REPAY_LOAN (
   CRL_ID               VARCHAR(32)          NOT NULL,
   CLB_ID               VARCHAR(32)          NULL,
   NEXTCHECKER          VARCHAR(200)         NULL,
   APPROVES             VARCHAR(200)         NULL,
   CORP_ID              VARCHAR(32)          NULL,
   USER_ID              VARCHAR(32)          NULL,
   CRL_NO               VARCHAR(14)          NULL,
   CRL_CREATE_TIME      DATETIME             NULL,
   CRL_DATE             DATETIME             NULL,
   CRL_MONEY            NUMERIC(15,2)        NULL,
   CRL_STATUS           NUMERIC(10)          NULL,
   CRL_FIXED_MONEY      NUMERIC(15,6)        NULL,
   CRL_AGREEMENT_MONEY  NUMERIC(15,6)        NULL,
   CRL_MEMO             VARCHAR(1000)        NULL,
   CRL_DESC             VARCHAR(2000)        NULL,
   CONSTRAINT PK_CMS_REPAY_LOAN PRIMARY KEY NONCLUSTERED (CRL_ID)
)
GO
alter table CMS_REPAY_LOAN add BILL_BLANCE  NUMERIC(15,2) default(0);
go
--增加贷款减免余额控制
ALTER TABLE CMS_LOAN_ABATE ADD BILL_BLANCE  NUMERIC(15,2) default(0);
go


ALTER TABLE CMS_LOAN_ABATE
   ADD CONSTRAINT FK_CMS_LOAN_REL_BILL__CMS_LOAN FOREIGN KEY (CLB_ID)
      REFERENCES CMS_LOAN_BILL (CLB_ID)
GO

ALTER TABLE CMS_PAYMENT_RECORDS
   ADD CONSTRAINT FK_CMS_PAYM_REL_PAYME_CMS_LOAN FOREIGN KEY (CLB_ID)
      REFERENCES CMS_LOAN_BILL (CLB_ID)
GO

ALTER TABLE CMS_REPAY_LOAN
   ADD CONSTRAINT FK_CMS_REPA_RAL_BILL__CMS_LOAN FOREIGN KEY (CLB_ID)
      REFERENCES CMS_LOAN_BILL (CLB_ID)
GO

--修改日期：20121018
--修改人：叶爱军
--修改内容：CMS_PAYMENT_RECORDS 增加字段 CPR_IS_AUTOMATIC
--参数设置： 
ALTER TABLE CMS_PAYMENT_RECORDS ADD CPR_IS_AUTOMATIC NUMERIC(1);
GO
UPDATE CMS_PAYMENT_RECORDS SET CPR_IS_AUTOMATIC = 0 WHERE CPR_IS_AUTOMATIC IS NULL;
GO
 
--修改日期：20121017
--修改人：叶爱军
--修改内容：CMS_LOAN_BILL 增加字段 应付固定费用 应付协定费用 已付固定费用 已付协定费用 减免固定费用 减免协定费用 待付固定费用 待付协定费用
--参数设置： 
ALTER TABLE CMS_LOAN_BILL ADD CLB_BIIL_FIX NUMERIC(15,2) default(0);
GO
ALTER TABLE CMS_LOAN_BILL ADD CLB_BILL_AGREEMENT NUMERIC(15,2) default(0);
GO
ALTER TABLE CMS_LOAN_BILL ADD CLB_PAY_FIX NUMERIC(15,2) default(0);
GO
ALTER TABLE CMS_LOAN_BILL ADD CLB_PAY_AGREEMENT NUMERIC(15,2) default(0);
GO
ALTER TABLE CMS_LOAN_BILL ADD CLB_ABATE_FIX NUMERIC(15,2) default(0);
GO
ALTER TABLE CMS_LOAN_BILL ADD CLB_ABATE_AGREEMENT NUMERIC(15,2) default(0);
GO
ALTER TABLE CMS_LOAN_BILL ADD CLB_UNPAY_FIX NUMERIC(15,2) default(0);
GO
ALTER TABLE CMS_LOAN_BILL ADD CLB_UNPAY_AGREEMENT NUMERIC(15,2) default(0);

UPDATE CMS_LOAN_BILL SET CLB_BIIL_FIX = 0 WHERE CLB_BIIL_FIX IS NULL;
GO
UPDATE CMS_LOAN_BILL SET CLB_BILL_AGREEMENT = 0 WHERE CLB_BILL_AGREEMENT IS NULL;
GO
UPDATE CMS_LOAN_BILL SET CLB_PAY_FIX = 0 WHERE CLB_PAY_FIX IS NULL;
GO
UPDATE CMS_LOAN_BILL SET CLB_PAY_AGREEMENT = 0 WHERE CLB_PAY_AGREEMENT IS NULL;
GO
UPDATE CMS_LOAN_BILL SET CLB_ABATE_FIX= 0 WHERE CLB_ABATE_FIX IS NULL;
GO
UPDATE CMS_LOAN_BILL SET CLB_ABATE_AGREEMENT = 0 WHERE CLB_ABATE_AGREEMENT IS NULL;
GO
UPDATE CMS_LOAN_BILL SET CLB_UNPAY_FIX = 0 WHERE CLB_UNPAY_FIX IS NULL;
GO
UPDATE CMS_LOAN_BILL SET CLB_UNPAY_AGREEMENT = 0 WHERE CLB_UNPAY_AGREEMENT IS NULL;

--增加协定占用费率
ALTER TABLE CMS_LOAN_INFO ADD CLB_AGREEMENT_RATE NUMERIC(15, 6);
GO
--增加协定占用费率
ALTER TABLE LOAN_SEND_OUT_INFO ADD CLB_AGREEMENT_RATE NUMERIC(15, 6);
GO

UPDATE CMS_LOAN_INFO SET CLB_AGREEMENT_RATE = 0;
GO
UPDATE LOAN_SEND_OUT_INFO SET CLB_AGREEMENT_RATE = 0;
GO

CREATE VIEW V_CMS_LOAN_BOOK AS
SELECT CLB.CLB_ID,
       CLB.CLB_NO,
       CLB.CLB_LOAN_CORP_ID AS BL_CORP_ID,
       BL.CORP_CODE AS BL_CORP_CODE,
       BL.CORP_NAME AS BL_CORP_NAME,
       CLB.CLB_BORROW_CORP_ID AS BB_CORP_ID,
       BB.CORP_CODE AS BB_CORP_CODE,
       BB.CORP_NAME AS BB_CORP_NAME,       
       (SELECT CONVERT(MONEY, ROUND(SUM(CLA.CLA_MONEY), 2), 120) FROM CMS_LOAN_ABATE CLA WHERE CLB.CLB_ID = CLA.CLB_ID) AS CLA_MONEY,
       CONVERT(MONEY, ROUND(CLB.CLB_BALANCE, 2), 120) AS CLB_BALANCE,
       CONVERT(MONEY, ROUND(CLB.CLB_FIXED_RATE, 2), 120) AS CLB_FIXED_RATE,
       CONVERT(MONEY, ROUND(CLB.CLB_AGREEMENT_RATE, 2), 120) AS CLB_AGREEMENT_RATE,
       (SELECT CONVERT(MONEY, ROUND(SUM(CRL.CRL_MONEY), 2), 120) FROM CMS_REPAY_LOAN CRL WHERE CLB.CLB_ID = CRL.CLB_ID) AS CRL_MONEY,
       (SELECT CONVERT(MONEY, ROUND(SUM(CBI.FIX_FEE_REAL), 2), 120) FROM CMS_BILLING CLA WHERE CLB.CLB_ID = CBI.CLB_ID) AS FIX_FEE_REAL,
       (SELECT CONVERT(MONEY, ROUND(SUM(CBI.AGREEMENT_FEE_REAL), 2), 120) FROM CMS_BILLING CLA WHERE CLB.CLB_ID = CBI.CLB_ID) AS AGREEMENT_FEE_REAL,
       (SELECT CONVERT(MONEY, ROUND(SUM(CRL.CRL_FIXED_MONEY), 2), 120) FROM CMS_REPAY_LOAN CRL WHERE CLB.CLB_ID = CRL.CLB_ID) AS CRL_FIXED_MONEY,
       (SELECT CONVERT(MONEY, ROUND(SUM(CRL.CRL_AGREEMENT_MONEY), 2), 120) FROM CMS_REPAY_LOAN CRL WHERE CLB.CLB_ID = CRL.CLB_ID) AS CRL_AGREEMENT_MONEY,
       (SELECT CONVERT(MONEY, ROUND(SUM(CPR.CPR_FIXED_MONEY), 2), 120) FROM CMS_PAYMENT_RECORDS CPR WHERE CLB.CLB_ID = CPR.CLB_ID) AS CPR_FIXED_MONEY,
       (SELECT CONVERT(MONEY, ROUND(SUM(CPR.CPR_AGREEMENT_MONEY), 2), 120) FROM CMS_PAYMENT_RECORDS CPR WHERE CLB.CLB_ID = CPR.CLB_ID) AS CPR_AGREEMENT_MONEY,
       CLB.CLB_START_DATE,
       CLB.CLB_END_DATE,
       CLB.CLB_STATUS
  FROM CMS_LOAN_BILL CLB
 INNER JOIN CMS_LOAN_ABATE CLA ON CLB.CLB_ID = CLA.CLB_ID
 INNER JOIN BT_CORP BL ON CLB.CLB_LOAN_CORP_ID = BL.ID
 INNER JOIN BT_CORP BB ON CLB.CLB_BORROW_CORP_ID = BB.ID
GO
/*==============================================================*/
/* Table: V_CMS_ACCOUNTINGFEE                                   */
/*==============================================================*/
CREATE VIEW V_CMS_ACCOUNTINGFEE AS
SELECT CLB.CLB_ID,
       CLB.CLB_NO,
       CLB.CLB_LOAN_CORP_ID AS BL_CORP_ID,
       BL.CORP_CODE AS BL_CORP_CODE,
       BL.CORP_NAME AS BL_CORP_NAME,
       CLB.CLB_BORROW_CORP_ID AS BB_CORP_ID,
       BB.CORP_CODE AS BB_CORP_CODE,
       BB.CORP_NAME AS BB_CORP_NAME,
       CONVERT(MONEY,ROUND(CLB.CLB_LOAN_MONEY, 2), 120) AS CLB_LOAN_MONEY,
       CONVERT(MONEY,ROUND(SUM(CLA.CLA_MONEY), 2), 120) AS CLA_MONEY,
       CONVERT(MONEY,ROUND(CB.CLB_BALANCE, 2), 120) AS CLB_BALANCE,
       CONVERT(MONEY,ROUND(CLB.CLB_FIXED_RATE, 6), 120) AS CLB_FIXED_RATE,
       CONVERT(MONEY,ROUND(CLB.CLB_AGREEMENT_RATE, 6), 120) AS CLB_AGREEMENT_RATE,
       CLB.CLB_START_DATE,
       CLB.CLB_END_DATE,
       CB.Notice_Num,
       CB.FIX_FEE,
       CB.FIX_FEE_REAL,
       CB.AGREEMENT_FEE,
       CB.AGREEMENT_FEE_REAL,
       CB.BILLING_ID,
       CB.MAKER,
       CB.AUDITOR,
       BU.USER_NAME AS MAKER_NAME,
       BU2.USER_NAME AS AUDITOR_NAME,
       CB.STATUS
FROM CMS_LOAN_BILL CLB
LEFT  JOIN CMS_LOAN_ABATE CLA ON CLB.CLB_ID = CLA.CLB_ID
INNER JOIN BT_CORP BL ON CLB.CLB_LOAN_CORP_ID = BL.ID
INNER JOIN BT_CORP BB ON CLB.CLB_BORROW_CORP_ID = BB.ID
INNER JOIN CMS_BILLING CB ON CLB.CLB_ID = CB.CLB_ID
LEFT  JOIN BT_USER BU ON CB.MAKER=BU.USER_CODE
LEFT  JOIN BT_USER BU2 ON CB.AUDITOR=BU2.USER_CODE
WHERE CLB.CLB_STATUS=95 AND CB.STATUS <> -12
GROUP BY CLB.CLB_ID,
         CLB.CLB_NO,
         CLB.CLB_LOAN_CORP_ID,
         BL.CORP_CODE,
         BL.CORP_NAME,
         CLB.CLB_BORROW_CORP_ID,
         BB.CORP_CODE,
         BB.CORP_NAME,
         CLB.CLB_LOAN_MONEY,
         CLB.CLB_BALANCE,
         CLB.CLB_FIXED_RATE,
         CLB.CLB_AGREEMENT_RATE,
         CLB.CLB_START_DATE,
         CLB.CLB_END_DATE,
         CB.Notice_Num,
         CB.FIX_FEE,
         CB.FIX_FEE_REAL,
         CB.AGREEMENT_FEE,
         CB.AGREEMENT_FEE_REAL,
         BU.USER_NAME,
         BU2.USER_NAME,
         CB.MAKER,
         CB.AUDITOR,
         CB.BILLING_ID,
         CB.STATUS
GO         
CREATE VIEW V_CMS_BILLING AS
SELECT CLB.CLB_ID,
       CLB.CLB_NO,
       CLB.CLB_LOAN_CORP_ID AS BL_CORP_ID,
       BL.CORP_CODE AS BL_CORP_CODE,
       BL.CORP_NAME AS BL_CORP_NAME,
       CLB.CLB_BORROW_CORP_ID AS BB_CORP_ID,
       BB.CORP_CODE AS BB_CORP_CODE,
       BB.CORP_NAME AS BB_CORP_NAME,
       CONVERT(MONEY,ROUND(CLB.CLB_LOAN_MONEY, 2), 120) AS CLB_LOAN_MONEY,
       CONVERT(MONEY,ROUND(SUM(CLA.CLA_MONEY), 2), 120) AS CLA_MONEY,
       CONVERT(MONEY,ROUND(CB.CLB_BALANCE, 2), 120) AS CLB_BALANCE,
       CONVERT(MONEY,ROUND(CLB.CLB_FIXED_RATE, 6), 120) AS CLB_FIXED_RATE,
       CONVERT(MONEY,ROUND(CLB.CLB_AGREEMENT_RATE, 6), 120) AS CLB_AGREEMENT_RATE,
       CLB.CLB_START_DATE,
       CLB.CLB_END_DATE,
       CLB.CLB_LAST_BILLING_DATE
FROM CMS_LOAN_BILL CLB
LEFT JOIN CMS_LOAN_ABATE CLA ON CLB.CLB_ID = CLA.CLB_ID
INNER JOIN BT_CORP BL ON CLB.CLB_LOAN_CORP_ID = BL.ID
INNER JOIN BT_CORP BB ON CLB.CLB_BORROW_CORP_ID = BB.ID
WHERE CLB.CLB_STATUS=95
--AND NOT EXISTS(SELECT 1 FROM CMS_BILLING CB WHERE CLB.CLB_ID = CB.CLB_ID AND CB.STATUS <> -2)
GROUP BY CLB.CLB_NO,CLB.CLB_LOAN_CORP_ID,BL.CORP_CODE,
        BL.CORP_NAME,CLB.CLB_BORROW_CORP_ID,BB.CORP_CODE,BB.CORP_NAME,
        CLB.CLB_LOAN_MONEY,CLB.CLB_BALANCE,CLB.CLB_FIXED_RATE,CLB.CLB_LAST_BILLING_DATE,
        CLB.CLB_AGREEMENT_RATE,CLB.CLB_START_DATE,CLB.CLB_END_DATE,CLB.CLB_ID
GO
CREATE VIEW V_CMS_PAYMENT_RECORD AS
SELECT CPR.CPR_ID,
       CPR.CPR_NO,
       CLB.CLB_ID, 
       CLB.CLB_NO,
       CLB.CLB_LOAN_CORP_ID AS BL_CORP_ID,
       BL.CORP_CODE AS BL_CORP_CODE,
       BL.CORP_NAME AS BL_CORP_NAME,
       CLB.CLB_BORROW_CORP_ID AS BB_CORP_ID,
       BB.CORP_CODE AS BB_CORP_CODE,
       BB.CORP_NAME AS BB_CORP_NAME,
	   CONVERT(MONEY, ROUND(CPR.CPR_MONEY, 2), 120) AS CPR_MONEY,
       CONVERT(MONEY, ROUND(CPR.CPR_FIXED_MONEY, 2), 120) AS CPR_FIXED_MONEY,
       CONVERT(MONEY, ROUND(CPR.CPR_AGREEMENT_MONEY, 2), 120) AS CPR_AGREEMENT_MONEY,
       CONVERT(MONEY, ROUND(CPR.CPR_MONEY + CPR.CPR_FIXED_MONEY + CPR.CPR_AGREEMENT_MONEY, 2), 120) AS CPR_TOTAL_MONEY,
       CPR.CPR_PAYMENT_DATE,
       CPR.CPR_DESC,
       CPR.CPR_STATUS
  FROM CMS_PAYMENT_RECORDS CPR
 JOIN CMS_LOAN_BILL CLB ON CLB.CLB_ID = CPR.CLB_ID
 JOIN BT_CORP BL ON CLB.CLB_LOAN_CORP_ID = BL.ID
 JOIN BT_CORP BB ON CLB.CLB_BORROW_CORP_ID = BB.ID
 GROUP BY CPR.CPR_ID,
          CPR.CPR_NO,
          CLB.CLB_ID,
          CLB.CLB_NO,
          CLB.CLB_LOAN_CORP_ID,
          BL.CORP_CODE,
          BL.CORP_NAME,
          CLB.CLB_BORROW_CORP_ID,
          BB.CORP_CODE,
          BB.CORP_NAME,
          CPR.CPR_MONEY,
          CPR.CPR_FIXED_MONEY,
          CPR.CPR_AGREEMENT_MONEY,
          CLB.CLB_AGREEMENT_RATE,
          CPR.CPR_PAYMENT_DATE,
          CPR.CPR_DESC,
          CPR.CPR_STATUS
GO
CREATE VIEW V_CMS_ABATE_VIEW AS
SELECT CLA.CLA_ID,  --减免单号
       CLB.CLB_NO, --贷款单号
       CLB.CLB_ID, --台账id
       CLB.CLB_LOAN_CORP_ID AS BL_CORP_ID,
       BL.CORP_NAME AS BL_CORP_NAME,
       CLB.CLB_BORROW_CORP_ID AS BB_CORP_ID,
       BB.CORP_NAME AS BB_CORP_NAME,
       CONVERT(MONEY, ROUND(CLA.CLA_MONEY, 2), 120) AS CRL_MONEY, --本金
       CONVERT(MONEY, ROUND(CLA.CLA_FIXED_MONEY, 2), 120) AS CLA_FIXED_MONEY, --固定占用费
       CONVERT(MONEY, ROUND(CLA.CLA_AGREEMENT_MONEY, 2), 120) AS CLA_AGREEMENT_MONEY, -- 协定占用费
       CONVERT(MONEY, ROUND(CLB.CLB_LOAN_MONEY, 2), 120) AS CLB_LOAN_MONEY, --贷款本金
       CONVERT(MONEY, ROUND(CLB.CLB_BALANCE, 2), 120) AS CLB_BALANCE, --当前余额
       CONVERT(MONEY, ROUND(CLA.CLA_MONEY*10000+CLA.CLA_FIXED_MONEY+CLA.CLA_AGREEMENT_MONEY, 2), 120) AS ABATEMONEY, 
       CLA.CLA_DATE,
       CLA.CLA_DESC,
       CLA.CLA_STATUS,
       CLA.CLA_NO,
       CLA.USER_ID,
       CLA.NEXTCHECKER
  FROM CMS_LOAN_ABATE CLA
 INNER JOIN CMS_LOAN_BILL CLB ON CLB.CLB_ID = CLA.CLB_ID
 INNER JOIN BT_CORP BL ON CLB.CLB_LOAN_CORP_ID = BL.ID
 INNER JOIN BT_CORP BB ON CLB.CLB_BORROW_CORP_ID = BB.ID
 GROUP BY CLA.CLA_ID,
          CLB.CLB_NO,
          CLB.CLB_ID,
          CLB.CLB_LOAN_CORP_ID,
          BL.CORP_NAME,
          CLB.CLB_BORROW_CORP_ID,
          BB.CORP_NAME,
          CLA.CLA_MONEY,
          CLA.CLA_FIXED_MONEY,
          CLA.CLA_AGREEMENT_MONEY,
          CLB.CLB_LOAN_MONEY,
          CLB.CLB_BALANCE,
          CLA.CLA_DATE,
          CLA.CLA_DESC,
          CLA.CLA_STATUS,
          CLA.CLA_NO,
          CLA.USER_ID,
          CLA.NEXTCHECKER
GO
CREATE VIEW V_CMS_REPAY_VIEW AS
SELECT CRL.CRL_ID,  --还款单号
       CLB.CLB_NO, --贷款单号
       CLB.CLB_ID, --台账id
       CLB.CLB_LOAN_CORP_ID AS BL_CORP_ID,
       BL.CORP_NAME AS BL_CORP_NAME,
       CLB.CLB_BORROW_CORP_ID AS BB_CORP_ID,
       BB.CORP_NAME AS BB_CORP_NAME,
       CONVERT(MONEY, ROUND(CRL.CRL_MONEY, 2), 120) AS CRL_MONEY, --本金
       CONVERT(MONEY, ROUND(CRL.CRL_FIXED_MONEY, 2), 120) AS CRL_FIXED_MONEY, --固定占用费
       CONVERT(MONEY, ROUND(CRL.CRL_AGREEMENT_MONEY, 2), 120) AS CRL_AGREEMENT_MONEY, -- 协定占用费
       CONVERT(MONEY, ROUND(CLB.CLB_LOAN_MONEY, 2), 120) AS CLB_LOAN_MONEY, --贷款本金
       CONVERT(MONEY, ROUND(CLB.CLB_BALANCE, 2), 120) AS CLB_BALANCE, --当前余额
       CONVERT(MONEY, ROUND(CRL.CRL_MONEY+CRL.CRL_FIXED_MONEY+CRL.CRL_AGREEMENT_MONEY, 2), 120) AS REPAYMONEY,  --sql中是否能 
       CRL.CRL_DATE,
       CRL.CRL_DESC,
       CRL.CRL_STATUS,
       CRL.CRL_NO,
       CRL.USER_ID,
       CRL.NEXTCHECKER
  FROM CMS_REPAY_LOAN CRL
 INNER JOIN CMS_LOAN_BILL CLB ON CLB.CLB_ID = CRL.CLB_ID
 INNER JOIN BT_CORP BL ON CLB.CLB_LOAN_CORP_ID = BL.ID
 INNER JOIN BT_CORP BB ON CLB.CLB_BORROW_CORP_ID = BB.ID
 GROUP BY CRL.CRL_ID,
          CLB.CLB_NO,
          CLB.CLB_ID,
          CLB.CLB_LOAN_CORP_ID,
          BL.CORP_NAME,
          CLB.CLB_BORROW_CORP_ID,
          BB.CORP_NAME,
          CRL.CRL_MONEY,
          CRL.CRL_FIXED_MONEY,
          CRL.CRL_AGREEMENT_MONEY,
          CLB.CLB_LOAN_MONEY,
          CLB.CLB_BALANCE,
          CRL.CRL_DATE,
          CRL.CRL_DESC,
          CRL.CRL_STATUS,
          CRL.CRL_NO,
          CRL.USER_ID,
          CRL.NEXTCHECKER
GO