--修改日期：20130221
--修改人：叶爱军
--VP编号：ZY-CD-03
--修改内容：添加授信记录是否包含保证金，是否循环使用字段
--是否包含保证金[1:包含;0:不包含]
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'INCLUDE_BAILMONEY' AND LTRIM(B.NAME) = 'RAT_BKRATION')
	ALTER TABLE RAT_BKRATION ADD INCLUDE_BAILMONEY CHAR(1)
GO
--是否循环使用 [1:循环;0:不循环]
--IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'IS_LOOP' AND LTRIM(B.NAME) = 'RAT_BKRATION')
--	ALTER TABLE AB_EMIT ADD IS_LOOP NUMBERIC(1)
--GO

--更新历史数据默认原参数设置
UPDATE RAT_BKRATION SET INCLUDE_BAILMONEY = (SELECT T.PARAM_VALUE1 FROM BT_PARAM T WHERE T.SYS_CODE = 'rat' AND T.CODE = 'includeBailMoney');
--UPDATE RAT_BKRATION SET IS_LOOP = 1;
GO

--BS>>基础平台>>系统参数维护>>银行授信管理系统>>删除授信是否包含保证金参数
DELETE FROM BT_PARAM WHERE SYS_CODE = 'rat' AND CODE = 'includeBailMoney';
GO