--修改日期：20130221
--修改人：叶爱军
--VP编号：ZY-CD-03
--修改内容：添加授信记录是否包含保证金，是否循环使用字段
DECLARE
  V_CNT_0 INTEGER;
  --V_CNT_1 INTEGER;
BEGIN
--是否包含保证金[1:包含;0:不包含]
  SELECT COUNT(1) INTO V_CNT_0 FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'RAT_BKRATION' AND COLUMN_NAME = 'INCLUDE_BAILMONEY';
--是否循环使用 [1:循环;0:不循环]
--SELECT COUNT(1) INTO V_CNT_1 FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'RAT_BKRATION' AND COLUMN_NAME = 'IS_LOOP';
  
  IF V_CNT_0 = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE RAT_BKRATION ADD INCLUDE_BAILMONEY CHAR(1)';
  END IF;
--IF V_CNT_1 = 0 THEN
--  EXECUTE IMMEDIATE 'ALTER TABLE RAT_BKRATION ADD IS_LOOP NUMBER(1)';
--END IF;
  COMMIT;
END;
/

--更新历史数据默认原参数设置
UPDATE RAT_BKRATION SET INCLUDE_BAILMONEY = (SELECT T.PARAM_VALUE1 FROM BT_PARAM T WHERE T.SYS_CODE = 'rat' AND T.CODE = 'includeBailMoney');
--UPDATE RAT_BKRATION SET IS_LOOP = 1;

--BS>>基础平台>>系统参数维护>>银行授信管理系统>>删除授信是否包含保证金参数
DELETE FROM BT_PARAM BP WHERE BP.SYS_CODE = 'rat' AND BP.CODE = 'includeBailMoney';
COMMIT;
/