--修改时间2012-12-14
--修改人 叶爱军
--修改内容  RAT_BKRATION 添加字段 IS_AUTONOMY
DECLARE
  VN_COUNT_1 NUMBER;
BEGIN
  SELECT COUNT(COLUMN_NAME) INTO VN_COUNT_1 FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'RAT_BKRATION' AND COLUMN_NAME = 'IS_AUTONOMY';
  IF VN_COUNT_1 = 0 THEN
     EXECUTE IMMEDIATE 'ALTER TABLE RAT_BKRATION ADD IS_AUTONOMY NUMBER(1)';
  END IF;
  COMMIT;
END;
/

DECLARE
  VN_COUNT_1 NUMBER;
BEGIN
  SELECT COUNT(CODE) INTO VN_COUNT_1 FROM BT_PARAM WHERE CODE = 'ratmodel' AND SYS_CODE = 'rat';
  IF VN_COUNT_1 = 0 THEN
     INSERT INTO BT_PARAM (CODE, SYS_CODE, NAME, PARAM_VALUE1, REVERSE1, REVERSE6, REVERSE7) VALUES ('ratmodel', 'rat', '授信模式选择', '1', '0,集团统一分配;1,单位自主录入;2,混合模式', 1.00, 1.00);
  END IF;
  IF VN_COUNT_1 = 1 THEN
     UPDATE BT_PARAM SET REVERSE1 = '0,集团统一分配;1,单位自主录入;2,混合模式' WHERE CODE = 'ratmodel' AND SYS_CODE = 'rat';
  END IF;
  --默认为统一授信
  UPDATE RAT_BKRATION RBK SET RBK.IS_AUTONOMY = 0 WHERE RBK.CORP_ID IN (SELECT BC.ID FROM BT_CORP BC WHERE BC.NET_SIGN = 1);--网点默认是统一
  UPDATE RAT_BKRATION RBK SET RBK.IS_AUTONOMY = 1 WHERE RBK.CORP_ID IN (SELECT BC.ID FROM BT_CORP BC WHERE BC.NET_SIGN = 0);--单位默认是自主
  COMMIT;
END;
/