--修改时间2012-12-14
--修改人 叶爱军
--修改内容  RAT_BKRATION 添加字段 IS_AUTONOMY
IF NOT EXISTS (SELECT A.NAME FROM SYSCOLUMNS A, SYSOBJECTS B WHERE A.ID = B.ID AND LTRIM(A.NAME) = 'IS_AUTONOMY' AND LTRIM(B.NAME) = 'RAT_BKRATION')
	ALTER TABLE RAT_BKRATION ADD IS_AUTONOMY NUMERIC(1)
GO

IF NOT EXISTS (SELECT COUNT(CODE) AS VN_COUNT FROM BT_PARAM WHERE CODE = 'ratmodel' AND SYS_CODE = 'rat')
	INSERT INTO BT_PARAM (CODE, SYS_CODE, NAME, PARAM_VALUE1, REVERSE1, REVERSE6, REVERSE7) VALUES ('ratmodel', 'rat', '授信模式选择', '1', '0,集团统一分配;1,单位自主录入;2,混合模式', 1.00, 1.00);
ELSE
	UPDATE BT_PARAM SET REVERSE1 = '0,集团统一分配;1,单位自主录入;2,混合模式' WHERE CODE = 'ratmodel' AND SYS_CODE = 'rat';
	--默认为统一授信
	UPDATE RAT_BKRATION SET IS_AUTONOMY = 0 WHERE CORP_ID IN (SELECT ID FROM BT_CORP WHERE NET_SIGN = 1);--网点默认是统一
	UPDATE RAT_BKRATION SET IS_AUTONOMY = 1 WHERE CORP_ID IN (SELECT ID FROM BT_CORP WHERE NET_SIGN = 0);--单位默认是自主
GO